Repository kubeshop/tracetest, pull requests merged in 2022-10, with the labels that each got.

#1310 Search not working correctly when using pagination
  web/src/components/InfiniteScroll/InfiniteScroll.tsx
  web/src/components/Pagination/Pagination.styled.ts
  web/src/components/Pagination/Pagination.tsx
  web/src/components/Pagination/index.ts
  web/src/hooks/useInfiniteScroll.ts
  web/src/hooks/usePagination.ts
  web/src/pages/Home/Content.tsx
  web/src/pages/Home/Home.styled.tsx
  web/src/pages/Home/Loading.tsx
  web/src/pages/Home/TestList.tsx
  web/src/pages/Test/TestDetails.tsx
Labels: frontend

#1326 Integrate test last run summary in Home page
  web/src/components/Layout/Layout.tsx
  web/src/components/TestCard/TestCard.styled.ts
  web/src/components/TestCard/TestCard.tsx
  web/src/components/TestCard/TestCardActions.tsx
  web/src/components/TestCard/TestCardV2.styled.ts
  web/src/components/TestCard/TestCardV2.tsx
  web/src/components/TestCard/__tests__/TestCard.test.tsx
  web/src/models/Test.model.ts
  web/src/models/TestSummary.model.ts
  web/src/pages/Home/Content.tsx
  web/src/pages/Home/Home.tsx
  web/src/pages/Test/Test.tsx
  web/src/types/Generated.types.ts
  web/src/types/Test.types.ts
Labels: frontend

#1331 Fix format of expected field
  web/src/redux/actions/TestSpecs.actions.ts
  web/src/redux/apis/TraceTest.api.ts
  web/src/services/TestDefinition.service.ts
Labels: bug, frontend

#1338 🦟 Adding demo enabled check for null values
  web/src/components/CreateTestPlugins/Default/steps/BasicDetails/BasicDetailsForm.tsx
Labels: frontend

#1250 Create new onboarding experience
  web/cypress/support/commands.ts
  web/package-lock.json
  web/package.json
  web/src/App.tsx
  web/src/components/Drawer/Drawer.tsx
  web/src/components/EditTest/EditTest.tsx
  web/src/components/GuidedTour/GuidedTour.tsx
  web/src/components/GuidedTour/NextButton.tsx
  web/src/components/GuidedTour/PreviousButton.tsx
  web/src/components/GuidedTour/StepContent.styled.tsx
  web/src/components/GuidedTour/StepContent.tsx
  web/src/components/GuidedTour/doArrow.tsx
  web/src/components/GuidedTour/homeStepList.tsx
  web/src/components/GuidedTour/testDetailsStepList.tsx
  web/src/components/GuidedTour/traceStepList.tsx
  web/src/components/Header/HeaderMenu.tsx
  web/src/components/Header/ShowOnboardingContent.tsx
  web/src/components/RunDetailLayout/HeaderLeft.tsx
  web/src/components/RunDetailLayout/HeaderRight.tsx
  web/src/components/RunDetailLayout/RunDetailLayout.tsx
  web/src/components/RunDetailTest/RunDetailTest.tsx
  web/src/components/RunDetailTrigger/RunDetailTrigger.styled.ts
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx
  web/src/components/SpanDetail/Header.tsx
  web/src/components/TestResults/Header.tsx
  web/src/providers/GuidedTour/GuidedTour.provider.tsx
  web/src/providers/GuidedTour/useGetTooltipComponent.tsx
  web/src/providers/GuidedTour/useShowOnboardingWhenNotCompletedEffect.tsx
  web/src/providers/GuidedTour/useUpdateStepsBasedOnLocationEffect.tsx
  web/src/services/GuidedTour.service.ts
Labels: frontend

#1339 1334 adding events to cover the new features
  web/src/components/AttributeList/AttributeList.tsx
  web/src/components/AttributeRow/AttributeCheck.tsx
  web/src/components/CreateSteps/CreateStepFooter.tsx
  web/src/components/CreateTestPlugins/Default/steps/SelectPlugin/SelectPlugin.tsx
  web/src/components/Drawer/Drawer.tsx
  web/src/components/EditTest/EditTest.tsx
  web/src/components/HeaderRow/HeaderRow.tsx
  web/src/components/PluginCard/PluginCard.tsx
  web/src/components/RunActionsMenu/RunActionsMenu.tsx
  web/src/components/RunDetailLayout/RunDetailLayout.tsx
  web/src/components/RunDetailTest/RunDetailTest.tsx
  web/src/components/RunDetailTest/Visualization.tsx
  web/src/components/RunDetailTrace/RunDetailTrace.tsx
  web/src/components/RunDetailTrace/Visualization.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx
  web/src/components/SpanDetail/Attributes.tsx
  web/src/components/SpanDetail/SpanDetail.tsx
  web/src/components/TestActions/TestActions.tsx
  web/src/constants/Analytics.constants.ts
  web/src/services/Analytics/AssertionAnalytics.service.ts
  web/src/services/Analytics/CreateAssertionModalAnalytics.service.ts
  web/src/services/Analytics/CreateTestAnalytics.service.ts
  web/src/services/Analytics/HomeAnalytics.service.ts
  web/src/services/Analytics/TestAnalytics.service.ts
  web/src/services/Analytics/TestRunAnalytics.service.ts
  web/src/services/Analytics/TraceAnalytics.service.ts
  web/src/services/Analytics/TraceDiagramAnalytics.service.ts
  web/src/services/Analytics/__tests__/TestAnalytics.service.test.ts
  web/src/services/Analytics/__tests__/TraceAnalytics.service.test.ts
  web/src/services/Analytics/__tests__/TraceDiagramAnalytics.service.test.ts
Labels: frontend

#1343 Create CNAME
  docs/CNAME
Labels: do not merge

#1302 Environment
  web/public/index.html
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsHeadersInput.tsx
  web/src/components/EnvironmentForm/EnvironmentForm.styled.ts
  web/src/components/EnvironmentForm/EnvironmentForm.tsx
  web/src/components/EnvironmentForm/index.ts
  web/src/components/GuidedTour/environmentsStepList.tsx
  web/src/components/Layout/Layout.tsx
  web/src/components/Router/Router.tsx
  web/src/components/TestCard/TestCard.styled.ts
  web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestsSelectionInput.tsx
  web/src/constants/Analytics.constants.ts
  web/src/constants/Test.constants.ts
  web/src/models/Environment.model.ts
  web/src/models/KeyValue.model.ts
  web/src/models/__mocks__/Environment.mock.ts
  web/src/models/__mocks__/KeyValue.mock.ts
  web/src/pages/Environments/Environment.styled.tsx
  web/src/pages/Environments/Environment.tsx
  web/src/pages/Environments/EnvironmentActions.tsx
  web/src/pages/Environments/EnvironmentCard.tsx
  web/src/pages/Environments/EnvironmentContent.tsx
  web/src/pages/Environments/EnvironmentList.tsx
  web/src/pages/Environments/EnvironmentModal.styled.ts
  web/src/pages/Environments/EnvironmentModal.tsx
  web/src/pages/Environments/IEnvironment.ts
  web/src/pages/Environments/index.ts
  web/src/providers/CreateTransaction/CreateTransaction.provider.tsx
  web/src/providers/GuidedTour/useUpdateStepsBasedOnLocationEffect.tsx
  web/src/redux/apis/TraceTest.api.ts
  web/src/services/Analytics/EnvironmentsAnalytics.service.ts
  web/src/services/GuidedTour.service.ts
Labels: frontend

#1355 1353 fixing test card styles
  web/src/components/TestCard/TestCard.styled.ts
  web/src/components/TestCard/TestCard.tsx
  web/src/utils/Date.ts
Labels: frontend

#1362 Add FE env configuration layer
  web/public/index.html
  web/src/components/CreateTestPlugins/Default/steps/BasicDetails/BasicDetailsForm.tsx
  web/src/components/Router/Router.tsx
  web/src/constants/Demo.constants.ts
  web/src/gateways/WebSocket.gateway.ts
  web/src/providers/Transaction/Transaction.provider.tsx
  web/src/services/Analytics/Analytics.service.ts
  web/src/types/Common.types.ts
  web/src/utils/Env.ts
  web/src/utils/ExperimentalFeature.ts
Labels: frontend

#1321 1264 [Transactions] Implement Outputs CRUD
  web/cypress/e2e/TestRunDetail/CreateAssertion.spec.ts
  web/src/components/OutputModal/OutputModal.styled.ts
  web/src/components/OutputModal/OutputModal.tsx
  web/src/components/OutputModal/OutputModalFooter.tsx
  web/src/components/OutputModal/OutputModalForm.tsx
  web/src/components/OutputModal/OutputModalValue.tsx
  web/src/components/OutputModal/hooks/useValidateOutput.ts
  web/src/components/OutputRow/OutputRow.styled.ts
  web/src/components/OutputRow/OutputRow.tsx
  web/src/components/OutputRow/OutputRowActions.tsx
  web/src/components/OutputRow/index.ts
  web/src/components/RunDetailTriggerResponse/ResponseOutputs.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.styled.ts
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx
  web/src/components/TestSpecForm/AssertionCheck.tsx
  web/src/components/TestSpecForm/Fields/AttributeField.styled.tsx
  web/src/components/TestSpecForm/Fields/AttributeField.tsx
  web/src/models/Output.model.ts
  web/src/selectors/TestRun.selectors.ts
  web/src/services/Output.service.ts
  web/src/services/TestRun.service.ts
  web/src/types/Output.types.ts
Labels: frontend

#1371 1235 [Transactions] Wire up environment dropdown with the app
  web/src/components/EnvironmentForm/EnvironmentForm.tsx
  web/src/components/EnvironmentSelector/EnvironmentSelector.tsx
  web/src/components/EnvironmentSelector/index.ts
  web/src/components/Header/Header.tsx
  web/src/components/Layout/Layout.tsx
  web/src/constants/Test.constants.ts
  web/src/models/Environment.model.ts
  web/src/models/__mocks__/Environment.mock.ts
  web/src/pages/Environments/EnvironmentCard.tsx
  web/src/pages/Environments/EnvironmentContent.tsx
  web/src/pages/Environments/EnvironmentList.tsx
  web/src/pages/Environments/EnvironmentModal.tsx
  web/src/pages/Environments/IEnvironment.ts
  web/src/providers/Environment/Environment.provider.tsx
  web/src/providers/Environment/index.ts
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/Environment.endpoint.ts
  web/src/redux/apis/endpoints/Test.endpoint.ts
  web/src/redux/apis/endpoints/TestRun.endpoints.ts
  web/src/redux/apis/endpoints/Transaction.endpoint.ts
  web/src/redux/slices/User.slice.ts
  web/src/redux/store.tsx
  web/src/selectors/Environment.selectors.ts
  web/src/selectors/User.selectors.ts
  web/src/services/UserPreferences.service.ts
  web/src/types/Environment.types.ts
  web/src/types/Test.types.ts
  web/src/types/User.types.ts
Labels: frontend

#1392 Add Selector Language cheat sheet
  web/public/SL_cheat_sheet.pdf
  web/src/components/TestHeader/__tests__/TestHeader.test.tsx
  web/src/components/TestSpecForm/TestSpecForm.styled.ts
  web/src/components/TestSpecForm/TestSpecForm.tsx
  web/src/components/TestSpecs/Empty.tsx
  web/src/components/TransactionHeader/TransactionHeader.tsx
  web/src/components/TransactionHeader/__tests__/TransactionHeader.test.tsx
  web/src/constants/Common.constants.ts
Labels: frontend

#1419 Remove page size select in pagination component
  web/cypress/e2e/utils/Common.ts
  web/cypress/support/commands.ts
  web/src/components/Pagination/Pagination.tsx
Labels: frontend

#1423 🐛 1401 1 of X goes away when cycling through spans
  web/src/components/Header/HeaderMenu.tsx
  web/src/redux/actions/Router.actions.ts
Labels: frontend

#1430 1425 adding basic environments CRUD
  api/environments.yaml
  api/openapi.yaml
  api/tests.yaml
  server/executor/runner.go
  server/executor/runner_test.go
  server/http/controller.go
  server/http/custom_routes.go
  server/http/mappings/tests.go
  server/migrations/12_environments.down.sql
  server/migrations/12_environments.up.sql
  server/model/repository.go
  server/model/tests.go
  server/openapi/api.go
  server/openapi/api_api.go
  server/openapi/model_environment.go
  server/openapi/model_environment_value.go
  server/openapi/model_test_run.go
  server/openapi/model_test_run_information.go
  server/testdb/environments.go
  server/testdb/environments_test.go
  server/testdb/mock.go
  server/testdb/postgres_test.go
  server/testdb/runs.go
  server/testdb/runs_test.go
  server/testdb/tests.go
  tracetesting/definitions/environment_create.yml
  tracetesting/definitions/environment_delete.yml
  tracetesting/definitions/environment_list.yml
  tracetesting/environments.bash
  tracetesting/run.bash
Labels: backend

#1440 [Transactions] Integrate Environments
  web/src/components/Editor/Expression/hooks/useAutoComplete.ts
  web/src/components/Editor/Interpolation/hooks/useAutoComplete.ts
  web/src/components/Editor/hooks/useTooltip.ts
  web/src/components/EnvironmentForm/EnvironmentForm.styled.ts
  web/src/components/EnvironmentForm/EnvironmentForm.tsx
  web/src/models/Environment.model.ts
  web/src/models/__mocks__/Environment.mock.ts
  web/src/pages/Environments/Environment.styled.tsx
  web/src/pages/Environments/Environment.tsx
  web/src/pages/Environments/EnvironmentActions.tsx
  web/src/pages/Environments/EnvironmentCard.tsx
  web/src/pages/Environments/EnvironmentContent.tsx
  web/src/pages/Environments/EnvironmentList.tsx
  web/src/pages/Environments/EnvironmentModal.styled.ts
  web/src/pages/Environments/EnvironmentModal.tsx
  web/src/pages/Environments/EnvironmentModalFooter.tsx
  web/src/providers/Environment/Environment.provider.tsx
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/Environment.endpoint.ts
  web/src/redux/apis/endpoints/Test.endpoint.ts
  web/src/selectors/Environment.selectors.ts
  web/src/types/Common.types.ts
  web/src/types/Environment.types.ts
  web/src/types/Generated.types.ts
  web/src/types/TestRun.types.ts
  web/src/utils/Common.ts
Labels: frontend

#1442 Fix style issue with the Authorization Type in the create test form
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsAuthInput/apiKeyFields.tsx
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsAuthInput/basicFields.tsx
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsAuthInput/bearerFields.tsx
Labels: frontend
