Repository kubeshop/tracetest, pull requests merged in 2022-07, with the labels that each got.

#847 Add new Span node design
  web/src/components/Diagram/components/DAG/SpanNode.styled.ts
  web/src/components/Diagram/components/DAG/SpanNode.tsx
  web/src/components/Diagram/components/Timeline/Timeline.tsx
  web/src/constants/SemanticGroupNames.constants.ts
  web/src/models/Span.model.ts
  web/src/models/__tests__/Span.model.test.ts
  web/src/types/DAG.types.ts
  web/src/types/Span.types.ts
Labels: frontend

#851 Fix timeline graph duration
  web/src/components/Diagram/components/Timeline/Timeline.tsx
Labels: frontend

#848 📃 [Documentation] 841 Adding new features documentation
  docs/edit-test.md
  docs/img/affected-spans-form-dag.png
  docs/img/affected-spans-form.png
  docs/img/affected-spans-select-dag.png
  docs/img/affected-spans-select.png
  docs/img/create-test-basic-details.png
  docs/img/create-test-request-details.png
  docs/img/create-test-select-plugin.png
  docs/img/edit-test-form.png
  docs/img/edit-test-home-dropdown.png
  docs/img/edit-test-trace-dropdown.png
  docs/img/edit-test-trace.png
  docs/img/exports-junit.png
  docs/img/exports-test-definition.png
  docs/img/exports-trace-options.png
  docs/img/text-search-database.png
  docs/img/text-search-http.png
  docs/run-affected-spans.md
  docs/run-exports.md
  docs/run-text-search.md
Labels: documentation, frontend

#880 📈 872 Implement Advanced Editor
  web/cypress/integration/TestDetails/ShowTestDetails.spec.ts
  web/cypress/integration/Trace/CreateAssertion.spec.ts
  web/package-lock.json
  web/package.json
  web/src/components/AdvancedEditor/AdvancedEditor.styled.ts
  web/src/components/AdvancedEditor/AdvancedEditor.tsx
  web/src/components/AdvancedEditor/hooks/useAutoComplete.ts
  web/src/components/AdvancedEditor/hooks/useEditorTheme.ts
  web/src/components/AdvancedEditor/hooks/useLint.ts
  web/src/components/AdvancedEditor/index.ts
  web/src/components/AssertionForm/AssertionForm.styled.ts
  web/src/components/AssertionForm/AssertionForm.tsx
  web/src/components/AssertionForm/AssertionFormSelector.tsx
  web/src/components/AssertionForm/hooks/useAssertionFormValues.ts
  web/src/components/AssertionForm/hooks/useQuerySelector.ts
  web/src/components/Diagram/components/DAG/AffectedSpanControls.tsx
  web/src/constants/AdvancedEditor.constants.ts
  web/src/constants/Common.constants.ts
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/hooks.ts
  web/src/selectors/Assertion.selectors.ts
  web/src/services/Selector.service.ts
  web/src/services/__tests__/Selector.service.test.ts
  web/src/utils/grammar/grammar.js
  web/src/utils/grammar/grammar.terms.js
  web/src/utils/grammar/index.ts
  web/src/utils/grammar/syntax.grammar
Labels: frontend

#890 866 multiple minor fixes
  web/src/components/CreateTestPlugins/Default/steps/SelectPlugin/SelectPlugin.styled.ts
  web/src/components/PluginCard/PluginCard.styled.ts
  web/src/components/PluginCard/PluginCard.tsx
  web/src/components/RunCard/RunCard.tsx
  web/src/components/RunCardList/RunCardList.tsx
Labels: frontend

#907 Update Test Result and Span Detail sections
  web/craco.config.js
  web/src/components/AssertionCard/AssertionCard.styled.ts
  web/src/components/AssertionCard/AssertionCard.tsx
  web/src/components/AssertionCard/AssertionCardSelectorList.tsx
  web/src/components/AssertionCard/__tests__/AssertionCard.test.tsx
  web/src/components/AssertionItem/AssertionActions.tsx
  web/src/components/AssertionItem/AssertionHeader.tsx
  web/src/components/AssertionItem/AssertionItem.styled.ts
  web/src/components/AssertionItem/AssertionItem.tsx
  web/src/components/AssertionItem/CheckItem.tsx
  web/src/components/AssertionItem/SpanActions.tsx
  web/src/components/AssertionItem/SpanHeader.tsx
  web/src/components/AssertionItem/index.ts
  web/src/components/AssertionList/AssertionList.styled.ts
  web/src/components/AssertionList/AssertionList.tsx
  web/src/components/AssertionList/index.ts
  web/src/components/Diagram/components/DAG/SpanNode.styled.ts
  web/src/components/Diagram/components/DAG/SpanNode.tsx
  web/src/components/RunBottomPanel/RunBottomPanel.styled.ts
  web/src/components/RunBottomPanel/RunBottomPanel.tsx
  web/src/components/SkeletonTable/SkeletonTable.tsx
  web/src/components/SkeletonTable/__tests__/SkeletonTable.test.tsx
  web/src/components/SkeletonTable/index.ts
  web/src/components/SpanDetail/SpanDetail.styled.ts
  web/src/components/SpanDetail/SpanDetail.tsx
  web/src/components/SpanDetail/SpanDetailTabs.tsx
  web/src/components/SpanDetail/SpanHeader.tsx
  web/src/components/TestResults/TestResults.tsx
  web/src/components/TestResults/__tests__/TestResults.test.tsx
  web/src/components/TestResults/index.ts
  web/src/constants/SemanticGroupNames.constants.ts
  web/src/models/DAG.model.ts
  web/src/models/Span.model.ts
  web/src/services/Assertion.service.ts
  web/src/services/Span.service.ts
  web/src/services/__tests__/Span.service.test.ts
  web/src/types/Assertion.types.ts
  web/src/types/DAG.types.ts
  web/src/types/Span.types.ts
Labels: frontend

#924 🦟 922 fixing failed trace rerun
  web/src/components/FailedTrace/FailedTrace.tsx
  web/src/pages/Trace/TraceContent.tsx
Labels: frontend

#932 make single word hostname a valid url
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsUrlInput.tsx
  web/src/utils/Validator.ts
  web/src/utils/__tests__/Validator.test.ts
Labels: frontend

#955 🐛 Filtering metadata array for rpc requests
  web/src/services/Triggers/Rpc.service.ts
Labels: frontend

#959 Wizard toggle not working on an assertion that can be represented by a key value mode
  web/src/components/AssertionItem/AssertionHeader.tsx
  web/src/components/AssertionItem/AssertionItem.styled.ts
  web/src/components/AssertionItem/AssertionItem.tsx
  web/src/components/AssertionList/AssertionList.tsx
Labels: frontend

#952 Refactor timeline visualization
  web/package-lock.json
  web/package.json
  web/src/assets/setting.svg
  web/src/components/Diagram/components/Timeline/Collapse.tsx
  web/src/components/Diagram/components/Timeline/Connector.tsx
  web/src/components/Diagram/components/Timeline/Label.tsx
  web/src/components/Diagram/components/Timeline/SpanNode.tsx
  web/src/components/Diagram/components/Timeline/Timeline.styled.ts
  web/src/components/Diagram/components/Timeline/Timeline.tsx
  web/src/components/Diagram/components/Timeline/Visualization.tsx
  web/src/constants/Theme.constants.ts
  web/src/constants/Timeline.constants.ts
  web/src/models/Timeline.model.ts
  web/src/services/Timeline.service.ts
  web/src/styled.d.ts
  web/src/types/Timeline.types.ts
Labels: frontend

#965 ✨ 964 adding demo examples for both GRPC and Postman plugins
  web/cypress/integration/Home/CreateTest.spec.ts
  web/cypress/integration/utils/Common.ts
  web/src/assets/pokeshop.postman_collection.json
  web/src/assets/pokeshop.proto.json
  web/src/components/CreateTestPlugins/Default/steps/BasicDetails/BasicDetails.tsx
  web/src/components/CreateTestPlugins/Default/steps/BasicDetails/BasicDetailsDemoHelper.tsx
  web/src/components/CreateTestPlugins/Default/steps/BasicDetails/BasicDetailsForm.tsx
  web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/UploadCollection.tsx
  web/src/components/CreateTestPlugins/Rpc/steps/RequestDetails/RequestDetails.tsx
  web/src/constants/Plugins.constants.ts
  web/src/constants/Test.constants.ts
  web/src/services/Test.service.ts
  web/src/types/Plugins.types.ts
Labels: frontend

#915 👀 905 Implement segment io for FE analytics
  web/package-lock.json
  web/package.json
  web/public/index.html
  web/src/App.tsx
  web/src/components/Analytics/AnalyticsProvider.tsx
  web/src/components/Analytics/__tests__/AnalyticsProvider.test.tsx
  web/src/components/Analytics/__tests__/useAnalytics.test.tsx
  web/src/components/Analytics/index.ts
  web/src/components/Analytics/useAnalytics.ts
  web/src/components/Navigation/Router.tsx
  web/src/components/WithAnalytics/WithAnalytics.tsx
  web/src/constants/Plugins.constants.ts
  web/src/index.tsx
  web/src/pages/CreateTest/CreateTest.tsx
  web/src/pages/EditTest/EditTest.tsx
  web/src/pages/Home/Home.tsx
  web/src/pages/Home/HomeActions.tsx
  web/src/pages/Test/Test.tsx
  web/src/pages/Trace/Trace.tsx
  web/src/services/Analytics/Analytics.service.ts
  web/src/services/Analytics/__tests__/Analytics.service.test.ts
  web/src/types/Common.types.ts
Labels: frontend

#972 Query language reference link in the app should point to docs version
  web/src/constants/Common.constants.ts
Labels: frontend

#978 Rendering issue in assertion results unless screen is wide
  web/src/components/AssertionItem/AssertionItem.styled.ts
  web/src/components/AssertionItem/CheckItem.tsx
Labels: frontend

#987 🐛 973 fixing minor assertions issues
  web/src/components/AdvancedEditor/AdvancedEditor.tsx
  web/src/components/AssertionForm/AssertionFormSelector.tsx
  web/src/components/AssertionForm/AssertionFormSelectorInput.tsx
  web/src/components/AssertionItem/AssertionHeader.tsx
  web/src/selectors/Assertion.selectors.ts
Labels: frontend

#986 When adding a second check in an assertion, the operator does not default to equals
  web/src/components/AssertionForm/AssertionFormCheck.tsx
Labels: frontend

#990 Fix selected assertion
  web/src/components/AssertionItem/AssertionItem.tsx
  web/src/redux/slices/TestDefinition.slice.ts
  web/src/redux/slices/__tests__/TestDefinition.slice.test.ts
  web/src/services/Assertion.service.ts
  web/src/types/TestDefinition.types.ts
Labels: frontend

#993 Add pagination in Test list
  web/src/gateways/Test.gateway.ts
  web/src/gateways/__tests__/Test.gateway.test.ts
  web/src/pages/Home/Home.styled.tsx
  web/src/pages/Home/NoResults.tsx
  web/src/pages/Home/TestList.tsx
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/__tests__/useGetTestListQuery.test.tsx
Labels: frontend

#996 docs: add information about time units
  docs/test-definition-file.md
Labels: documentation

#1008 🐛🦟 1003 fixing minor frontend bugs
  web/src/App.less
  web/src/components/AdvancedEditor/hooks/useAutoComplete.ts
  web/src/components/AssertionForm/AssertionForm.tsx
  web/src/components/CreateTestPlugins/Grpc/Grpc.ts
  web/src/components/CreateTestPlugins/Grpc/index.ts
  web/src/components/CreateTestPlugins/Grpc/steps/RequestDetails/RequestDetails.styled.ts
  web/src/components/CreateTestPlugins/Grpc/steps/RequestDetails/RequestDetails.tsx
  web/src/components/CreateTestPlugins/Grpc/steps/RequestDetails/RequestDetailsFileInput.tsx
  web/src/components/CreateTestPlugins/Grpc/steps/RequestDetails/RequestDetailsForm.tsx
  web/src/components/CreateTestPlugins/Grpc/steps/RequestDetails/RequestDetailsMetadataInput.tsx
  web/src/components/CreateTestPlugins/Grpc/steps/RequestDetails/index.ts
  web/src/components/CreateTestPlugins/Plugins.ts
  web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/fields/CollectionFileField.tsx
  web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/fields/EnvFileField.tsx
  web/src/components/EditTestForm/EditRequestDetails/Grpc/Grpc.tsx
  web/src/components/RunTopPanel/RunTopPanel.styled.ts
  web/src/components/RunTopPanel/RunTopPanel.tsx
  web/src/constants/Plugins.constants.ts
  web/src/pages/CreateTest/CreateTestContent.tsx
  web/src/providers/CreateTest/CreateTest.provider.tsx
  web/src/redux/slices/CreateTest.slice.ts
  web/src/services/Test.service.ts
  web/src/services/Triggers/Grpc.service.ts
  web/src/types/Test.types.ts
Labels: frontend

#1013 👁 Adding extra server info to all analytics events
  web/src/components/WithAnalytics/WithAnalytics.tsx
  web/src/services/Analytics/Analytics.service.ts
  web/src/types/Common.types.ts
Labels: frontend
