Repository kubeshop/tracetest, pull requests merged in 2022-11, with the labels that each got.

#1435 1434 [Transactions] Environment definition execution
  server/http/controller.go
  server/model/yaml/encoding.go
  server/model/yaml/environment.go
  server/model/yaml/file.go
Labels: backend

#1445 Add click area in test spec detail
  web/src/components/TestSpecDetail/Content.tsx
  web/src/components/TestSpecDetail/TestSpecDetail.styled.ts
Labels: frontend

#1431 [Transactions] Integrate Test Outputs
  api/openapi.yaml
  server/http/controller.go
  server/model/test_changes.go
  server/openapi/api.go
  server/openapi/api_api.go
  web/src/components/OutputModal/OutputModal.styled.ts
  web/src/components/OutputModal/OutputModal.tsx
  web/src/components/OutputModal/OutputModalFooter.tsx
  web/src/components/OutputModal/OutputModalForm.tsx
  web/src/components/OutputModal/hooks/useValidateOutput.ts
  web/src/components/OutputRow/OutputRow.styled.ts
  web/src/components/OutputRow/OutputRow.tsx
  web/src/components/OutputRow/OutputRowActions.tsx
  web/src/components/OutputRow/OutputValue.tsx
  web/src/components/RunDetailTriggerResponse/ResponseOutputs.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.styled.ts
  web/src/models/Output.model.ts
  web/src/models/Test.model.ts
  web/src/models/TestOutput.model.ts
  web/src/models/TestRun.model.ts
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/Test.endpoint.ts
  web/src/redux/store.tsx
  web/src/redux/testOutputs/selectors.ts
  web/src/redux/testOutputs/slice.ts
  web/src/selectors/TestRun.selectors.ts
  web/src/services/Output.service.ts
  web/src/types/Generated.types.ts
  web/src/types/Output.types.ts
  web/src/types/Test.types.ts
  web/src/types/TestOutput.types.ts
  web/src/types/TestRun.types.ts
Labels: frontend

#1451 Add search in span detail
  web/cypress/e2e/TestRunDetail/TestRunDetail.spec.ts
  web/src/components/AttributeList/AttributeList.tsx
  web/src/components/AttributeList/__tests__/AttributeList.test.tsx
  web/src/components/AttributeRow/AttributeRow.styled.ts
  web/src/components/AttributeRow/AttributeRow.tsx
  web/src/components/AttributeRow/__tests__/AttributeRow.test.tsx
  web/src/components/SearchInput/SearchInput.tsx
  web/src/components/SpanDetail/Attributes.tsx
  web/src/components/SpanDetail/SpanDetail.styled.ts
  web/src/components/SpanDetail/SpanDetail.tsx
  web/src/components/SpanDetail/__tests__/SpanDetail.test.tsx
  web/src/components/TestSpecForm/Fields/AttributeField.tsx
  web/src/components/TestSpecForm/hooks/useGetOTELSemanticConventionAttributesInfo.tsx
  web/src/redux/apis/OtelRepo.api.ts
  web/src/services/SpanAttribute.service.ts
  web/src/services/__tests__/SpanAttribute.service.test.ts
Labels: frontend

#1452 1448 transactions resolve trigger values before test execution
  server/executor/runner.go
  server/executor/runner_test.go
  server/executor/trigger/grpc.go
  server/executor/trigger/http.go
  server/executor/trigger/instrument.go
  server/executor/trigger/triggerer.go
  server/http/mappings/http.go
  web/cypress/e2e/Home/CreateTest.spec.ts
  web/cypress/e2e/Home/CreateTestFromCurl.spec.ts
  web/public/index.html
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/BodyField/BodyField.tsx
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsAuthInput/TypeInput.tsx
  web/src/components/Editor/hooks/useTooltip.ts
  web/src/gateways/TestRun.gateway.ts
  web/src/providers/CreateTest/CreateTest.provider.tsx
  web/src/providers/Test/hooks/useTestCrud.ts
  web/src/redux/apis/endpoints/TestRun.endpoints.ts
  web/src/services/Assertion.service.ts
Labels: frontend, backend

#1462 Add tracetest semantic conventions
  web/src/components/AttributeRow/AttributeRow.tsx
  web/src/components/TestSpecForm/hooks/useGetOTELSemanticConventionAttributesInfo.tsx
  web/src/constants/AttributesTags.json
  web/src/constants/TracetestSemanticConventions.json
  web/src/redux/apis/OtelRepo.api.ts
  web/src/services/SpanAttribute.service.ts
Labels: frontend

#1461 1406 [Transactions] Expected Value Dropdown Selection
  api/expressions.yaml
  server/http/controller.go
  server/openapi/impl.go
  server/openapi/model_resolve_response_info.go
  web/cypress/e2e/TestRunDetail/CreateAssertion.spec.ts
  web/cypress/e2e/TestRunDetail/TestRunDetail.spec.ts
  web/cypress/support/commands.ts
  web/src/components/Editor/Expression/Expression.tsx
  web/src/components/Editor/Interpolation/Interpolation.tsx
  web/src/components/Editor/hooks/useTooltip.ts
  web/src/components/TestSpecForm/AssertionCheck.tsx
  web/src/components/TestSpecForm/AssertionCheckList.tsx
  web/src/components/TestSpecForm/AssertionCheckValue.tsx
  web/src/components/TestSpecForm/TestSpecForm.tsx
  web/src/models/Test.model.ts
  web/src/models/Transaction.model.ts
  web/src/models/__mocks__/Transaction.mock.ts
  web/src/redux/apis/endpoints/Expression.endpoint.ts
  web/src/selectors/Assertion.selectors.ts
  web/src/types/Generated.types.ts
Labels: frontend, backend

#1483 1474 [Transactions] Implement transactions run page
  web/src/components/EditTransaction/EditTransaction.tsx
  web/src/components/ResourceCard/ResourceCardSummary.tsx
  web/src/components/ResourceCard/TransactionCard.tsx
  web/src/components/RunCard/TransactionRunCard.tsx
  web/src/components/TransactionHeader/TransactionHeader.styled.ts
  web/src/components/TransactionHeader/TransactionHeader.tsx
  web/src/components/TransactionHeader/__tests__/TransactionHeader.test.tsx
  web/src/components/TransactionRunActionsMenu/TransactionRunActionsMenu.styled.ts
  web/src/components/TransactionRunActionsMenu/TransactionRunActionsMenu.tsx
  web/src/components/TransactionRunActionsMenu/index.ts
  web/src/components/TransactionRunLayout/TransactionRunLayout.tsx
  web/src/components/TransactionRunResult/ExecutionStep.tsx
  web/src/components/TransactionRunResult/TransactionRunResult.styled.ts
  web/src/components/TransactionRunResult/TransactionRunResult.tsx
  web/src/components/TransactionRunResult/Variable.tsx
  web/src/hooks/useDeleteResourceRun.tsx
  web/src/models/TestRun.model.ts
  web/src/models/Transaction.model.ts
  web/src/models/TransactionRun.model.ts
  web/src/models/TransactionRunResult.ts
  web/src/models/__mocks__/Transaction.mock.ts
  web/src/pages/Home/Content.tsx
  web/src/providers/CreateTest/CreateTest.provider.tsx
  web/src/providers/CreateTransaction/CreateTransaction.provider.tsx
  web/src/providers/Transaction/Transaction.provider.tsx
  web/src/providers/Transaction/hooks/useTransactionCrud.ts
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/TransactionRun.endpoint.ts
  web/src/types/Generated.types.ts
  web/src/types/Transaction.types.ts
  web/src/types/TransactionRun.types.ts
Labels: frontend

#1510 Fix environment page header
  web/src/pages/Environments/Environment.styled.tsx
  web/src/pages/Environments/EnvironmentContent.tsx
Labels: frontend

#1507 Display environment variables used for the test run
  web/src/components/KeyValueRow/KeyValueRow.styled.ts
  web/src/components/KeyValueRow/KeyValueRow.tsx
  web/src/components/KeyValueRow/index.ts
  web/src/components/RunDetailTriggerResponse/ResponseEnvironment.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.styled.ts
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx
  web/src/components/TransactionRunResult/TransactionRunResult.styled.ts
  web/src/components/TransactionRunResult/TransactionRunResult.tsx
  web/src/components/TransactionRunResult/Variable.tsx
  web/src/models/TestRun.model.ts
Labels: frontend

#1511 1505 1475 [Transactions] Display test spec summary results for transaction test runs
  web/src/components/ResourceCard/ResourceCardSummary.tsx
  web/src/components/RunDetailLayout/RunDetailLayout.tsx
  web/src/components/TransactionRunLayout/TransactionRunLayout.tsx
  web/src/components/TransactionRunResult/ExecutionStep.tsx
  web/src/components/TransactionRunResult/TransactionRunResult.styled.ts
  web/src/constants/Common.constants.ts
  web/src/hooks/useDocumentTitle.ts
  web/src/pages/Test/Content.tsx
  web/src/pages/Transaction/Content.tsx
  web/src/pages/TransactionRunDetail/Content.tsx
  web/src/providers/TransactionRun/TransactionRun.provider.tsx
  web/src/providers/TransactionRun/index.ts
Labels: frontend

#1508 1503 [Transactions] Allow users create outputs from attributes
  web/src/components/AttributeList/AttributeList.tsx
  web/src/components/AttributeRow/AttributeRow.tsx
  web/src/components/OutputModal/OutputModal.tsx
  web/src/components/RunDetailLayout/RunDetailLayout.tsx
  web/src/components/RunDetailTriggerResponse/ResponseOutputs.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx
  web/src/components/SpanDetail/Attributes.tsx
  web/src/components/SpanDetail/SpanDetail.tsx
  web/src/models/Test.model.ts
  web/src/models/TestOutput.model.ts
  web/src/pages/RunDetail/RunDetail.tsx
  web/src/pages/TransactionRunDetail/TransactionRunDetail.tsx
  web/src/providers/TestOutput/TestOutput.provider.tsx
  web/src/providers/TestOutput/index.ts
  web/src/redux/testOutputs/slice.ts
  web/src/types/TestOutput.types.ts
Labels: frontend

#1514 🐛 Fixing assertion result alignment
  web/src/components/TestSpecDetail/Assertion.tsx
  web/src/components/TestSpecDetail/TestSpecDetail.styled.ts
  web/src/pages/TransactionRunDetail/TransactionRunDetail.tsx
Labels: frontend

#1519 Improve attribute section
  web/src/components/AttributeRow/AttributeRow.styled.ts
  web/src/components/AttributeRow/AttributeRow.tsx
Labels: frontend

#1518 1517 [Transactions] Enable Transaction Runs Service Pagination
  api/openapi.yaml
  docker-compose.yaml
  server/http/controller.go
  server/model/repository.go
  server/openapi/api.go
  server/openapi/api_api.go
  server/testdb/mock.go
  server/testdb/transaction_runs.go
  server/testdb/transactions_runs_test.go
  web/src/components/ResourceCard/TransactionCard.tsx
Labels: backend

#1521 1520 fixing several UI issues
  web/src/components/TestState/TestState.tsx
  web/src/components/TransactionRunResult/ExecutionStep.tsx
  web/src/components/TransactionRunResult/TransactionRunResult.tsx
  web/src/constants/TestRun.constants.ts
  web/src/types/TestRun.types.ts
Labels: frontend

#1531 Remove transactions experimental feature flag
  .github/workflows/pull-request.yaml
  k8s/tracetest.beta.yaml
  web/public/index.html
  web/src/components/Layout/Layout.tsx
  web/src/components/Router/Router.tsx
  web/src/components/RunCard/TestRunCard.tsx
  web/src/components/RunCard/TransactionRunCard.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx
  web/src/components/TestHeader/TestHeader.tsx
  web/src/pages/Home/HomeActions.tsx
  web/src/pages/Test/Content.tsx
  web/src/pages/Transaction/Content.tsx
Labels: frontend

#1529 test: add e2e tests for environments page
  web/cypress/e2e/Environments/Environments.spec.ts
  web/src/components/EnvironmentForm/EnvironmentForm.tsx
  web/src/pages/Environments/EnvironmentCard.tsx
Labels: frontend

#1538 fix(frontend): fixing output selector input
  web/public/index.html
  web/src/components/OutputModal/OutputModalForm.tsx
  web/src/pages/RunDetail/RunDetail.tsx
Labels: frontend

#1556 fix(e2e): change cypress selector to match autocomplete options
  web/cypress/support/commands.ts
  web/cypress/support/index.d.ts
Labels: frontend

#1560 fix(frontend): fixing small UI/UX bugs
  web/cypress/e2e/TestRunDetail/CreateAssertion.spec.ts
  web/cypress/e2e/TestRunDetail/TestRunDetail.spec.ts
  web/cypress/support/commands.ts
  web/public/index.html
  web/src/components/Editor/Editor.styled.ts
  web/src/components/Editor/Expression/Expression.tsx
  web/src/components/Editor/Interpolation/Interpolation.tsx
  web/src/components/Editor/hooks/useTooltip.ts
  web/src/components/TestSpecForm/AssertionCheck.tsx
  web/src/components/TestSpecForm/AssertionCheckValue.tsx
Labels: frontend

#1561 fix(frontend): improving test and transactions details UI and output …
  web/src/components/OutputModal/OutputModalForm.tsx
  web/src/components/TestHeader/TestHeader.styled.ts
  web/src/components/TestHeader/TestHeader.tsx
  web/src/components/TestSpecForm/hooks/useQuerySelector.ts
  web/src/pages/Test/Content.tsx
  web/src/pages/Transaction/Content.tsx
Labels: frontend

#1557 test: adding e2e tests for transactions and transactions runs
  web/cypress/e2e/Home/CreateTest.spec.ts
  web/cypress/e2e/Home/CreateTestFromCurl.spec.ts
  web/cypress/e2e/Home/CreateTestFromPostman.spec.ts
  web/cypress/e2e/Transactions/Transactions.spec.ts
  web/cypress/e2e/Transactions/TransactionsRun.spec.ts
  web/cypress/e2e/constants/Transactions.ts
  web/cypress/e2e/utils/Common.ts
  web/cypress/e2e/utils/Transactions.ts
  web/cypress/support/commands.ts
  web/cypress/support/index.d.ts
  web/src/components/CreateModal/CreateModal.tsx
  web/src/components/CreateSteps/CreateStepFooter.tsx
  web/src/components/CreateSteps/CreateSteps.tsx
  web/src/components/CreateTestModal/CreateTestModal.tsx
  web/src/components/CreateTransactionModal/CreateTransactionModal.tsx
  web/src/components/TransactionHeader/TransactionHeader.tsx
  web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestsSelectionInput.tsx
  web/src/components/TransactionRunResult/ExecutionStep.tsx
Labels: frontend

#1575 fix(frontend): fixing assertion value autocomplete overlap
  web/cypress/support/commands.ts
  web/src/components/Editor/Editor.tsx
  web/src/components/Editor/Expression/Expression.tsx
  web/src/components/Editor/Expression/grammar/__tests__/cases.txt
  web/src/components/Editor/Expression/grammar/grammar.js
  web/src/components/Editor/Expression/grammar/grammar.terms.js
  web/src/components/Editor/Expression/grammar/syntax.grammar
  web/src/components/Editor/Expression/hooks/useAutoComplete.ts
  web/src/components/TestSpecForm/AssertionCheckValue.tsx
  web/src/services/Editor.service.ts
Labels: frontend

#1551 test: add e2e tests for create/run test using environment
  web/cypress/e2e/Environments/Environments.spec.ts
  web/cypress/e2e/Home/CreateTest.spec.ts
  web/cypress/e2e/Home/CreateTestFromCurl.spec.ts
  web/cypress/e2e/Home/CreateTestFromPostman.spec.ts
  web/cypress/e2e/Home/CreateTestWithAuthentication.spec.ts
  web/cypress/e2e/Transactions/Transactions.spec.ts
  web/cypress/e2e/Transactions/TransactionsRun.spec.ts
  web/cypress/support/commands.ts
  web/cypress/support/index.d.ts
  web/src/components/AttributeList/__tests__/AttributeList.test.tsx
  web/src/components/AttributeRow/__tests__/AttributeRow.test.tsx
  web/src/components/EnvironmentSelector/EnvironmentSelector.tsx
  web/src/components/KeyValueRow/KeyValueRow.styled.ts
  web/src/pages/Home/HomeActions.tsx
Labels: frontend

#1590 fix(frontend): fix useEffect loop in transaction form
  web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestsSelectionInput.tsx
Labels: frontend

#1596 fix(frontend): remove flamegraph
  k8s/tracetest.beta.yaml
  web/package-lock.json
  web/package.json
  web/public/index.html
  web/src/components/RunDetailTest/Visualization.tsx
  web/src/components/RunDetailTrace/RunDetailTrace.tsx
  web/src/components/RunDetailTrace/Visualization.tsx
  web/src/components/Visualization/components/Flame/Flame.styled.tsx
  web/src/components/Visualization/components/Flame/Flame.tsx
  web/src/components/Visualization/components/Flame/__tests__/FlameView.test.tsx
  web/src/components/Visualization/components/Switch/Switch.styled.ts
  web/src/components/Visualization/components/Switch/Switch.tsx
  web/src/services/Flamegraph.service.ts
Labels: frontend

#1602 test: add e2e tests for outputs
  web/cypress/e2e/TestRunDetail/Outputs.spec.ts
  web/cypress/support/commands.ts
  web/src/components/AttributeRow/AttributeRow.tsx
  web/src/components/OutputModal/OutputModal.tsx
  web/src/components/OutputModal/OutputModalFooter.tsx
  web/src/components/OutputModal/OutputModalForm.tsx
  web/src/components/OutputRow/OutputRow.tsx
  web/src/components/OutputRow/OutputRowActions.tsx
  web/src/components/RunDetailTriggerResponse/ResponseOutputs.tsx
  web/src/components/SpanDetail/SpanDetail.tsx
  web/src/components/TestHeader/__tests__/TestHeader.test.tsx
  web/src/providers/TestOutput/TestOutput.provider.tsx
Labels: frontend

#1606 feature(frontend): moving navigation logic to use anchor tags when possible
  web/src/components/Layout/Layout.tsx
  web/src/components/ResourceCard/ResourceCardRuns.tsx
  web/src/components/ResourceCard/TestCard.tsx
  web/src/components/ResourceCard/TransactionCard.tsx
  web/src/components/RunDetailLayout/HeaderLeft.tsx
  web/src/components/RunDetailLayout/RunDetailLayout.styled.ts
  web/src/components/RunDetailLayout/RunDetailLayout.tsx
  web/src/components/TestHeader/TestHeader.tsx
  web/src/components/TransactionHeader/TransactionHeader.tsx
  web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestItem.tsx
  web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestsSelectionInput.styled.ts
  web/src/components/TransactionRunLayout/TransactionRunLayout.tsx
  web/src/components/TransactionRunResult/ExecutionStep.tsx
  web/src/pages/Home/Content.tsx
  web/src/pages/Test/Content.tsx
  web/src/pages/Transaction/Content.tsx
Labels: frontend

#1607 fix(frontend): deleting the last remaining test when creating a transaction has issues
  web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestItem.tsx
  web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestItemList.tsx
  web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestsSelectionInput.tsx
Labels: frontend
