Repository kubeshop/tracetest, pull requests merged in 2022-12, with the labels that each got.

#1619 fix(frontend): fix broken documentation link
  web/src/constants/Common.constants.ts
Labels: frontend

#1620 fix: remove partial test update endpoints
  api/openapi.yaml
  cli/openapi/api_api.go
  server/http/controller.go
  server/model/test_changes.go
  server/openapi/api.go
  server/openapi/api_api.go
  server/testdb/tests.go
  web/cypress/e2e/TestRunDetail/TestRunDetail.spec.ts
  web/src/components/TestHeader/__tests__/TestHeader.test.tsx
  web/src/components/TransactionHeader/__tests__/TransactionHeader.test.tsx
  web/src/gateways/Test.gateway.ts
  web/src/gateways/TestSpecs.gateway.ts
  web/src/gateways/__tests__/TestSpecs.gateway.test.ts
  web/src/providers/TestOutput/TestOutput.provider.tsx
  web/src/providers/TestRun/TestRun.provider.tsx
  web/src/providers/TestSpecs/TestSpecs.provider.tsx
  web/src/providers/TestSpecs/__tests__/TestSpecs.provider.test.tsx
  web/src/providers/TestSpecs/hooks/useTestSpecsCrud.ts
  web/src/redux/actions/TestSpecs.actions.ts
  web/src/redux/actions/__tests_/TestSpecs.actions.test.ts
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/Test.endpoint.ts
  web/src/redux/testOutputs/slice.ts
  web/src/services/Test.service.ts
  web/src/services/TestDefinition.service.ts
  web/src/types/Generated.types.ts
Labels: frontend, backend

#1649 feat(frontend): add initial settings page
  web/src/components/Layout/Layout.styled.ts
  web/src/components/Layout/Layout.tsx
  web/src/components/Router/Router.tsx
  web/src/components/Settings/DataStore/DataStore.tsx
  web/src/components/Settings/DataStore/index.ts
  web/src/pages/Settings/Content.tsx
  web/src/pages/Settings/Settings.styled.ts
  web/src/pages/Settings/Settings.tsx
  web/src/pages/Settings/index.ts
Labels: frontend

#1652 feature(frontend): adding base logic for the data store config form
  web/src/components/Settings/DataStore/DataStore.styled.ts
  web/src/components/Settings/DataStore/DataStore.tsx
  web/src/components/Settings/DataStoreForm/DataStoreForm.styled.ts
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/components/Settings/DataStoreForm/index.ts
  web/src/components/Settings/DataStorePlugin/DataStoreComponentFactory.tsx
  web/src/components/Settings/DataStorePlugin/DataStorePlugin.tsx
  web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx
  web/src/components/Settings/DataStorePlugin/forms/GrpcClient/index.ts
  web/src/components/Settings/DataStorePlugin/forms/OpenSearch/OpenSearch.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenSearch/index.ts
  web/src/components/Settings/DataStorePlugin/forms/SignalFx/SignalFx.tsx
  web/src/components/Settings/DataStorePlugin/forms/SignalFx/index.ts
  web/src/components/Settings/DataStorePlugin/index.ts
  web/src/pages/Settings/Content.tsx
  web/src/providers/SetupConfig/SetupConfig.provider.tsx
  web/src/providers/SetupConfig/index.ts
  web/src/redux/setupConfig/selectors.ts
  web/src/redux/setupConfig/slice.ts
  web/src/redux/store.tsx
  web/src/services/DataStores/GrpcClient.service.ts
  web/src/services/DataStores/OpenSearch.service.ts
  web/src/services/DataStores/SignalFx.service.ts
  web/src/services/SetupConfig.service.ts
  web/src/services/Triggers/Http.service.ts
  web/src/types/Config.types.ts
Labels: frontend

#1658 feature(frontend): adding open search data store form
  web/src/components/DataStoreForm/DataStoreForm.styled.ts
  web/src/components/DataStoreForm/DataStoreForm.tsx
  web/src/components/DataStoreForm/index.ts
  web/src/components/DataStorePlugin/DataStoreComponentFactory.tsx
  web/src/components/DataStorePlugin/DataStorePlugin.tsx
  web/src/components/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx
  web/src/components/DataStorePlugin/forms/GrpcClient/index.ts
  web/src/components/DataStorePlugin/forms/OpenSearch/OpenSearch.tsx
  web/src/components/DataStorePlugin/forms/OpenSearch/index.ts
  web/src/components/DataStorePlugin/forms/SignalFx/SignalFx.tsx
  web/src/components/DataStorePlugin/forms/SignalFx/index.ts
  web/src/components/DataStorePlugin/index.ts
  web/src/components/Settings/DataStore/DataStore.styled.ts
  web/src/components/Settings/DataStore/DataStore.tsx
  web/src/components/Settings/DataStoreForm/DataStoreForm.styled.ts
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/components/Settings/DataStoreForm/DataStoreSelectionInput.tsx
  web/src/components/Settings/DataStorePlugin/DataStorePluginForm.styled.ts
  web/src/components/Settings/DataStorePlugin/forms/OpenSearch/AddressesList.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenSearch/OpenSearch.tsx
  web/src/pages/Settings/Settings.tsx
  web/src/providers/SetupConfig/SetupConfig.provider.tsx
  web/src/services/DataStores/OpenSearch.service.ts
  web/src/services/SetupConfig.service.ts
  web/src/types/Config.types.ts
Labels: frontend

#1659 feature(frontend): prepare FE for granular data store service update
  api/config.yaml
  api/openapi.yaml
  web/src/App.tsx
  web/src/components/Settings/DataStore/DataStore.tsx
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/components/Settings/DataStorePlugin/DataStorePlugin.tsx
  web/src/components/SetupAlert/SetupAlert.tsx
  web/src/models/Config.model.ts
  web/src/models/DataStore.model.ts
  web/src/models/DataStoreConfig.model.ts
  web/src/models/ServerConfig.model.ts
  web/src/models/TelemetryConfig.model.ts
  web/src/models/__mocks__/Config.mock.ts
  web/src/models/__mocks__/DataStoreConfig.mock.ts
  web/src/pages/Home/Home.tsx
  web/src/pages/Settings/Content.tsx
  web/src/pages/Settings/Settings.tsx
  web/src/providers/Config/index.ts
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/providers/DataStore/index.ts
  web/src/providers/DataStoreConfig/DataStoreConfig.provider.tsx
  web/src/providers/DataStoreConfig/index.ts
  web/src/providers/SetupConfig/SetupConfig.provider.tsx
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/Config.endpoint.ts
  web/src/redux/setupConfig/selectors.ts
  web/src/redux/setupConfig/slice.ts
  web/src/redux/store.tsx
  web/src/services/DataStore.service.ts
  web/src/services/DataStores/OpenSearch.service.ts
  web/src/types/Config.types.ts
  web/src/types/Generated.types.ts
Labels: frontend

#1660 feature(frontend): adding signal fx data store form
  web/src/components/Settings/DataStorePlugin/forms/OpenSearch/OpenSearch.tsx
  web/src/components/Settings/DataStorePlugin/forms/SignalFx/SignalFx.tsx
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/redux/apis/endpoints/Config.endpoint.ts
  web/src/services/DataStore.service.ts
  web/src/services/DataStores/SignalFx.service.ts
Labels: frontend

#1666 feature(frontend): adding docs banner to data store config forms
  web/src/components/Settings/DataStoreDocsBanner/DataStoreDocsBanner.styled.ts
  web/src/components/Settings/DataStoreDocsBanner/DataStoreDocsBanner.tsx
  web/src/components/Settings/DataStoreDocsBanner/index.ts
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/constants/DataStore.constants.ts
  web/src/services/DataStore.service.ts
Labels: frontend

#1668 feature(frontend): test connection data store logic
  api/config.yaml
  web/src/components/Settings/DataStore/DataStore.tsx
  web/src/constants/Theme.constants.ts
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/redux/apis/endpoints/Config.endpoint.ts
  web/src/styled.d.ts
  web/src/types/Config.types.ts
  web/src/types/Generated.types.ts
Labels: frontend

#1675 feat(frontend): add file upload for cert files in grpc data store config
  web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClientSecure.tsx
  web/src/services/DataStores/GrpcClient.service.ts
  web/src/types/Config.types.ts
Labels: frontend

#1673 feature(frontend): multiple in app config updates
  web/src/components/Settings/DataStore/DataStore.styled.ts
  web/src/components/Settings/DataStore/DataStore.tsx
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/constants/DataStore.constants.ts
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/services/DataStore.service.ts
Labels: frontend

#1677 feature(frontend): adding no tracing mode warning
  web/src/App.tsx
  web/src/components/Header/Header.styled.tsx
  web/src/components/Header/Header.tsx
  web/src/components/Layout/Layout.tsx
  web/src/components/NoTracingPopover/NoTracingPopover.styled.ts
  web/src/components/NoTracingPopover/NoTracingPopover.tsx
  web/src/components/SetupAlert/SetupAlert.tsx
  web/src/constants/Theme.constants.ts
  web/src/styled.d.ts
Labels: frontend

#1682 feature(frontend): adding support for the otel collector as data store
  api/config.yaml
  local-config/collector.config.yaml
  web/src/assets/otlp.svg
  web/src/components/Settings/DataStoreForm/DataStoreForm.styled.ts
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/components/Settings/DataStoreForm/DataStoreSelectionInput.tsx
  web/src/components/Settings/DataStorePlugin/DataStorePlugin.tsx
  web/src/components/Settings/DataStorePlugin/DataStorePluginForm.styled.ts
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.styled.ts
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/index.ts
  web/src/constants/DataStore.constants.ts
  web/src/constants/DataStore.constants.tsx
  web/src/providers/DataStoreConfig/DataStoreConfig.provider.tsx
  web/src/services/DataStore.service.ts
  web/src/services/DataStores/GrpcClient.service.ts
  web/src/services/DataStores/OtelCollector.service.ts
  web/src/types/Config.types.ts
  web/src/types/Generated.types.ts
Labels: frontend

#1681 fix(frontend): fix eslint config and enable it in CI
  .github/workflows/pull-request.yaml
  web/.eslintrc.js
  web/package.json
  web/src/components/AttributeRow/AttributeRow.tsx
  web/src/components/Header/__tests__/Header.test.tsx
Labels: frontend

#1699 feature(backend): adding the open search test connection logic
  api/config.yaml
  api/openapi.yaml
  cli/openapi/api_api.go
  cli/openapi/model_test_connection_response.go
  examples/tracetest-opensearch/docker-compose.yml
  examples/tracetest-opensearch/tests/list-tests.yaml
  examples/tracetest-opensearch/tracetest-config.yaml
  server/openapi/impl.go
  server/openapi/model_test_connection_response.go
  server/tracedb/opensearchdb.go
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/redux/apis/endpoints/Config.endpoint.ts
  web/src/types/Config.types.ts
  web/src/types/Generated.types.ts
Labels: backend

#1690 feat(server): add data stores CRUD API
  api/config.yaml
  api/dataStores.yaml
  api/openapi.yaml
  cli/go.mod
  cli/go.sum
  cli/openapi/api_api.go
  cli/openapi/model_data_store.go
  cli/openapi/model_grpc_client_settings.go
  cli/openapi/model_open_search.go
  cli/openapi/model_signal_fx.go
  cli/openapi/model_supported_data_stores.go
  cli/openapi/model_tls.go
  cli/openapi/model_tls_setting.go
  server/http/controller.go
  server/http/custom_routes.go
  server/http/mappings/data_store.go
  server/migrations/16_data_stores.down.sql
  server/migrations/16_data_stores.up.sql
  server/model/data_stores.go
  server/model/repository.go
  server/openapi/api.go
  server/openapi/api_api.go
  server/openapi/model_data_store.go
  server/openapi/model_grpc_client_settings.go
  server/openapi/model_open_search.go
  server/openapi/model_signal_fx.go
  server/openapi/model_supported_data_stores.go
  server/openapi/model_tls.go
  server/openapi/model_tls_setting.go
  server/testdb/data_stores.go
  server/testdb/data_stores_test.go
  server/testdb/mock.go
  server/testdb/postgres.go
  server/testdb/postgres_test.go
  web/src/models/DataStore.model.ts
  web/src/types/Common.types.ts
  web/src/types/Config.types.ts
  web/src/types/Generated.types.ts
Labels: backend

#1705 feature(backend): adding tempo test connection logic
  server/tracedb/tempodb.go
Labels: backend

#1701 feature(backend): adding signalfx test connection logic
  server/tracedb/signalfxdb.go
Labels: backend

#1718 fix(frontend): change SetupAlert to work with a unique preference key
  web/src/components/SetupAlert/SetupAlert.styled.ts
  web/src/components/SetupAlert/SetupAlert.tsx
  web/src/providers/DataStoreConfig/DataStoreConfig.provider.tsx
  web/src/services/UserPreferences.service.ts
  web/src/types/User.types.ts
Labels: frontend

#1724 feature(frontend): adding frontend test connection notification
  web/package-lock.json
  web/package.json
  web/src/components/Settings/DataStorePlugin/forms/SignalFx/SignalFx.tsx
  web/src/components/TestConnectionNotification/TestConnectionNotification.styled.ts
  web/src/components/TestConnectionNotification/TestConnectionNotification.tsx
  web/src/components/TestConnectionNotification/TestConnectionStep.tsx
  web/src/constants/Theme.constants.ts
  web/src/models/ConnectionResult.model.ts
  web/src/models/ConnectionResultStep.model.ts
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/providers/DataStore/hooks/useTestConnectionNotification.tsx
  web/src/redux/apis/endpoints/Config.endpoint.ts
  web/src/services/DataStore.service.ts
  web/src/styled.d.ts
  web/src/types/Config.types.ts
Labels: frontend

#1713 feat(frontend): add dataStores api integration
  api/config.yaml
  api/dataStores.yaml
  api/openapi.yaml
  cli/openapi/model_grpc_client_settings.go
  server/http/mappings/data_store.go
  server/openapi/model_grpc_client_settings.go
  web/cypress/e2e/Home/ShowTestList.spec.ts
  web/cypress/e2e/TestRunDetail/CreateAssertion.spec.ts
  web/cypress/support/commands.ts
  web/src/components/Settings/DataStore/DataStore.tsx
  web/src/components/Settings/DataStoreForm/DataStoreForm.styled.ts
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx
  web/src/components/SetupAlert/SetupAlert.tsx
  web/src/models/DataStoreConfig.model.ts
  web/src/models/__mocks__/DataStoreConfig.mock.ts
  web/src/pages/Home/ConfigCTA.tsx
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/providers/DataStoreConfig/DataStoreConfig.provider.tsx
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/Config.endpoint.ts
  web/src/services/DataStore.service.ts
  web/src/services/DataStores/GrpcClient.service.ts
  web/src/services/DataStores/OpenSearch.service.ts
  web/src/services/DataStores/SignalFx.service.ts
  web/src/types/Config.types.ts
  web/src/types/Generated.types.ts
Labels: frontend

#1726 fix(frontend): fix data store confirmation message
  web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/providers/DataStore/hooks/useDataStoreNotification.tsx
Labels: frontend

#1719 feature(cli): improve installer experience
  cli/installer/configuration.go
  cli/installer/docker_compose.go
  cli/installer/installer.go
  cli/installer/kubernetes.go
  cli/installer/tracetest.go
  cli/installer/windows.go
  examples/collector/collector.config.yaml
  k8s/collector.yml
Labels: CLI

#1729 feature(cli): removing the remove vs local k8 question
  cli/installer/kubernetes.go
Labels: CLI

#1736 fix(frontend): fix update dataStores service
  server/model/data_stores.go
  server/testdb/data_stores.go
  server/testdb/data_stores_test.go
  web/src/services/DataStore.service.ts
Labels: frontend, backend

#1737 fix(cli): fixing rabbitMQ version
  examples/docker-compose.demo.yaml
Labels: backend

#1744 fix(server): fix tracetest testing in our pipeline
  k8s/tracetest.beta.yaml
  server/model/data_stores.go
Labels: backend

#1740 fix(frontend): fix delete data store confirmation message
  web/src/providers/DataStore/DataStore.provider.tsx
Labels: frontend

#1747 fix(frontend): improve data store connection message
  web/src/components/TestConnectionNotification/TestConnectionNotification.styled.ts
  web/src/components/TestConnectionNotification/TestConnectionNotification.tsx
  web/src/components/TestConnectionNotification/TestConnectionStep.tsx
  web/src/providers/DataStore/hooks/useDataStoreNotification.tsx
Labels: frontend

#1752 fix(frontend): add standard layout for data store forms and ui fixes
  web/src/components/Settings/DataStore/DataStore.tsx
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenSearch/OpenSearch.tsx
  web/src/components/Settings/DataStorePlugin/forms/SignalFx/SignalFx.tsx
  web/src/pages/Settings/Content.tsx
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/services/DataStore.service.ts
  web/src/services/DataStores/OpenSearch.service.ts
Labels: frontend
