Repository kubeshop/tracetest, pull requests merged in 2023-04, with the labels that each got.

#2317 fix(server): fix TestRunEvent mapping in WebSocket
  server/http/websocket/subscribe.go
Labels: backend

#2294 feat(frontend): add websocket subscription for test run events
  web/src/components/RunEvents/RunEventsTrace.tsx
  web/src/components/TestResults/TestResults.tsx
  web/src/components/TestSpecs/TestSpecs.tsx
  web/src/constants/TestRunEvents.constants.ts
  web/src/redux/apis/endpoints/TestRun.endpoints.ts
  web/src/services/TestRun.service.ts
Labels: frontend

#2321 fix(server): standardize events title and description
  server/model/events/events.go
Labels: backend

#2366 feature(frontend): adding test spec snippets
  web/src/components/TestResults/AddTestSpecButton.tsx
  web/src/components/TestResults/Header.tsx
  web/src/components/TestResults/TestResults.styled.ts
  web/src/components/TestResults/TestResults.tsx
  web/src/constants/TestSpecs.constants.ts
Labels: frontend

#2371 fix(frontend): add minor improvements for error handling
  web/src/components/RunDetailLayout/HeaderRight.tsx
  web/src/components/RunDetailTest/RunDetailTest.tsx
  web/src/components/SpanDetail/Header.tsx
Labels: frontend

#2372 feature(frontend): adding persistent page number for list
  web/src/components/Pagination/Pagination.tsx
  web/src/components/RunDetailLayout/HeaderLeft.tsx
  web/src/components/RunDetailLayout/RunDetailLayout.tsx
  web/src/components/TestHeader/TestHeader.tsx
  web/src/components/TransactionHeader/TransactionHeader.tsx
  web/src/hooks/usePagination.ts
Labels: frontend

#2375 feature(backend): adding analytics events for test run checkpoints
  server/analytics/analytics.go
  server/app/app.go
  server/executor/assertion_runner.go
  server/executor/runner.go
  server/executor/trace_poller.go
  server/http/custom_routes.go
Labels: backend

#2295 feat(frontend): stop a test run
  .github/workflows/pull-request.yaml
  web/src/components/RunCard/RunCard.styled.ts
  web/src/components/RunCard/TestRunCard.tsx
  web/src/components/RunDetailLayout/HeaderRight.tsx
  web/src/components/RunDetailLayout/RunDetailLayout.styled.ts
  web/src/components/RunDetailTest/Visualization.tsx
  web/src/components/RunDetailTrace/Visualization.tsx
  web/src/components/RunEvents/RunEvents.styled.ts
  web/src/components/RunEvents/RunEventsTrace.tsx
  web/src/components/RunEvents/TraceHeader/FailedTraceHeader.tsx
  web/src/components/RunEvents/TraceHeader/FailedTriggerHeader.tsx
  web/src/components/RunEvents/TraceHeader/LoadingHeader.tsx
  web/src/components/RunEvents/TraceHeader/StoppedHeader.tsx
  web/src/constants/TestRun.constants.ts
  web/src/models/TestRun.model.ts
  web/src/providers/TestRun/TestRun.provider.tsx
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/TestRun.endpoints.ts
  web/src/services/TestRun.service.ts
Labels: frontend

#2394 fix(cli): fix TRACETEST_DEV in docker compose installer
  cli/analytics/analytics.go
  cli/installer/docker_compose.go
Labels: CLI

#2384 feature(backend): defaulting url trigger to http if no scheme is present
  server/executor/trigger/http.go
Labels: backend

#2396 feature(frontned): adding FE text event log
  web/src/assets/terminal.svg
  web/src/components/EventLogPopover/EventLogContent.tsx
  web/src/components/EventLogPopover/EventLogPopover.styled.ts
  web/src/components/EventLogPopover/EventLogPopover.tsx
  web/src/components/EventLogPopover/index.ts
  web/src/components/RunDetailLayout/HeaderRight.tsx
  web/src/components/RunEvents/RunEventsTrace.tsx
  web/src/models/TestRunEvent.model.ts
  web/src/services/EventLog.service.ts
Labels: frontend

#2397 fix(frontend): update discord menu to online chat
  web/src/components/Header/Menu.tsx
Labels: frontend

#2398 feature(frontend): improving error messaging for the trace results
  server/executor/trace_poller.go
  web/src/components/RunEvents/RunEventDataStore.tsx
  web/src/components/RunEvents/RunEvents.styled.ts
Labels: frontend, backend

#2405 fix: improvements to the test run events
  server/executor/assertion_runner.go
  server/executor/poller_executor.go
  server/executor/trace_poller.go
  server/model/events/events.go
  web/src/components/RunEvents/RunEventPolling.tsx
Labels: frontend, backend

#2399 feat(frontend): improve test specs error handling
  web/src/components/TestSpec/Header.tsx
  web/src/components/TestSpec/TestSpec.styled.ts
  web/src/components/TestSpec/TestSpec.tsx
  web/src/components/TestSpecDetail/Assertion.tsx
  web/src/components/TestSpecDetail/TestSpecDetail.styled.ts
  web/src/services/Assertion.service.ts
Labels: frontend

#2404 feat: improve test outputs error handling
  api/tests.yaml
  cli/openapi/model_test_run_outputs_inner.go
  server/executor/assertion_runner.go
  server/executor/outputs_processor.go
  server/http/mappings/tests.go
  server/model/events/events.go
  server/model/json.go
  server/model/tests.go
  server/openapi/model_test_run_outputs_inner.go
  web/src/components/TestOutput/TestOutput.styled.ts
  web/src/components/TestOutput/TestOutput.tsx
  web/src/models/TestOutput.model.ts
  web/src/models/TestRunOutput.model.ts
  web/src/redux/testOutputs/slice.ts
  web/src/types/Generated.types.ts
Labels: frontend, backend

#2412 feature(backend): Adding support for HTTP OTLP server
  examples/collector/docker-compose.yml
  server/app/app.go
  server/go.mod
  server/go.sum
  server/otlp/grpc_server.go
  server/otlp/http_server.go
  server/otlp/ingester.go
Labels: backend

#2427 feature(backend): adding event logs for otlp endpoints
  server/app/app.go
  server/model/events/events.go
  server/otlp/grpc_server.go
  server/otlp/http_server.go
  server/otlp/ingester.go
Labels: backend

#2423 Add data store as resource on FE
  api/dataStores.yaml
  api/openapi.yaml
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/models/DataStore.model.ts
  web/src/models/DataStoreConfig.model.ts
  web/src/models/__mocks__/DataStoreConfig.mock.ts
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/providers/SettingsValues/SettingsValues.provider.tsx
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/DataStore.endpoint.ts
  web/src/services/DataStore.service.ts
  web/src/types/DataStore.types.ts
  web/src/types/Generated.types.ts
Labels: frontend

#2433 fix(cli): fix resources URLs
  cli/cmd/config.go
Labels: CLI

#2422 Add data store as resource on CLI
  cli/actions/apply_datastore_action.go
  cli/actions/config.go
  cli/actions/datastore.go
  cli/actions/demo.go
  cli/actions/export_datastore_action.go
  cli/actions/list_datastore_action.go
  cli/actions/polling.go
  cli/actions/resource.go
  cli/actions/resource_actions.go
  cli/actions/run_test_action.go
  cli/cmd/config.go
  cli/cmd/datastore_apply_cmd.go
  cli/cmd/datastore_cmd.go
  cli/cmd/datastore_export_cmd.go
  cli/cmd/datastore_legacy_cmd.go
  cli/cmd/datastore_list_cmd.go
  cli/cmd/list_cmd.go
  cli/openapi/api_api.go
  cli/openapi/api_resource_api.go
  cli/utils/api.go
  server/model/yaml/file.go
Labels: CLI

#2429 chore(docs): update data store docs and examples
  TESTING.md
  docs/docs/cli/creating-data-stores.md
  docs/docs/configuration/connecting-to-data-stores/awsxray.md
  docs/docs/configuration/connecting-to-data-stores/datadog.md
  docs/docs/configuration/connecting-to-data-stores/elasticapm.md
  docs/docs/configuration/connecting-to-data-stores/jaeger.md
  docs/docs/configuration/connecting-to-data-stores/lightstep.md
  docs/docs/configuration/connecting-to-data-stores/new-relic.md
  docs/docs/configuration/connecting-to-data-stores/opensearch.md
  docs/docs/configuration/connecting-to-data-stores/opentelemetry-collector.md
  docs/docs/configuration/connecting-to-data-stores/signalfx.md
  docs/docs/configuration/connecting-to-data-stores/tempo.md
  docs/docs/configuration/provisioning.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-elasticapm.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-jaeger.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-new-relic.md
  docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store-with-manual-instrumentation.md
  examples/collector/tracetest-provision.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part1/tracetest/tracetest-provision.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part2.1/tracetest/tracetest-provision.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part2.2/tracetest/tracetest-provision.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part3.1/tracetest/tracetest-provision.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part3.2/tracetest/tracetest-provision.yaml
  examples/quick-start-datadog-nodejs/tracetest/tracetest-provision.yaml
  examples/quick-start-go/tracetest/tracetest-provision.yaml
  examples/quick-start-jaeger-nodejs/tracetest/tracetest-provision.yaml
  examples/quick-start-net-core/tracetest-provision.yaml
  examples/quick-start-nodejs-manual-instrumentation/tracetest/tracetest-provision.yaml
  examples/quick-start-nodejs/tracetest/tracetest-provision.yaml
  examples/quick-start-python/tracetest/tracetest-provision.yaml
  examples/quick-start-ruby-on-rails/tracetest/tracetest-provision.yaml
  examples/quick-start-ruby-sinatra/tracetest/tracetest-provision.yaml
  examples/tracetest-new-relic-otel-demo/tracetest/tracetest-provision.yaml
  examples/tracetest-new-relic/tracetest/tracetest-provision.yaml
  examples/tracetest-provisioning-env/tracetest-provision.yaml
  local-config/tracetest.provision.yaml
Labels: documentation

#2437 feature(frontend): enabling environments as resources
  api/environments.yaml
  api/openapi.yaml
  server/environment/manager_test.go
  web/src/components/EnvironmentForm/EnvironmentForm.tsx
  web/src/components/EnvironmentModal/EnvironmentModal.tsx
  web/src/components/FileViewerModal/FileViewerModal.provider.tsx
  web/src/models/Environment.model.ts
  web/src/models/TestRun.model.ts
  web/src/models/TransactionRun.model.ts
  web/src/providers/Environment/Environment.provider.tsx
  web/src/providers/Environment/hooks/useEnvironmentCrud.ts
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/Environment.endpoint.ts
  web/src/redux/apis/endpoints/Resource.endpoint.ts
  web/src/services/Environment.service.ts
  web/src/types/Generated.types.ts
Labels: frontend

#2428 chore(docs): updating Tracetest OTLP port
  cli/installer/tracetest.go
  docs/docs/configuration/connecting-to-data-stores/datadog.md
  docs/docs/configuration/connecting-to-data-stores/lightstep.md
  docs/docs/configuration/connecting-to-data-stores/new-relic.md
  docs/docs/configuration/connecting-to-data-stores/opentelemetry-collector.md
  docs/docs/examples-tutorials/recipes/running-python-app-with-opentelemetry-collector-and-tracetest.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-aws-x-ray-adot.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-datadog.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-lightstep.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-new-relic.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-testkube.md
  docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store-with-manual-instrumentation.md
  docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store.md
  examples/quick-start-datadog-nodejs/tracetest/collector.config.yaml
  examples/quick-start-go/tracetest/collector.config.yaml
  examples/quick-start-nodejs-manual-instrumentation/tracetest/collector.config.yaml
  examples/quick-start-nodejs/tracetest/collector.config.yaml
  examples/quick-start-python/tracetest/collector.config.yaml
  examples/quick-start-ruby-on-rails/tracetest/collector.config.yaml
  examples/quick-start-ruby-sinatra/tracetest/collector.config.yaml
  examples/tracetest-amazon-x-ray-adot/collector.config.yaml
  examples/tracetest-datadog/tracetest/collector.config.yaml
  examples/tracetest-lightstep-otel-demo/README.md
  examples/tracetest-lightstep-otel-demo/otelcollector/otelcol-config-extras.yml
  examples/tracetest-lightstep/tracetest/collector.config.yaml
  examples/tracetest-new-relic-otel-demo/README.md
  examples/tracetest-new-relic-otel-demo/otelcollector/otelcol-config-extras.yml
  examples/tracetest-new-relic/tracetest/collector.config.yaml
  local-config/collector.config.yaml
  web/src/constants/CollectorConfig.constants.ts
Labels: documentation, do not merge

#2454 Updating mappings for DataStores
  api/dataStores.yaml
  cli/formatters/datastore_list.go
  cli/openapi/api_resource_api.go
  cli/openapi/model_data_store.go
  cli/openapi/model_data_store_resource.go
  cli/openapi/model_supported_data_stores.go
  server/http/mappings/datastore.go
  server/openapi/api_resource_api_service.go
  server/openapi/model_data_store.go
  server/openapi/model_data_store_resource.go
  server/openapi/model_supported_data_stores.go
  server/tracedb/datastoreresource/repository_test.go
  server/tracedb/datastoreresource/resource_types.go
  web/src/models/DataStore.model.ts
  web/src/services/DataStores/SignalFx.service.ts
  web/src/types/DataStore.types.ts
  web/src/types/Generated.types.ts
Labels: frontend, backend, CLI

#2446 feature(cli): enabling environments as resources
  api/openapi.yaml
  cli/actions/apply_environment_action.go
  cli/actions/config.go
  cli/actions/datastore.go
  cli/actions/demo.go
  cli/actions/environments.go
  cli/actions/polling.go
  cli/actions/resource_actions.go
  cli/actions/run_test_action.go
  cli/cmd/config.go
  cli/cmd/environment_apply.go
  cli/cmd/environment_cmd.go
  cli/cmd/environment_legacy_cmd.go
  cli/cmd/test_run_cmd.go
  cli/file/definition.go
  cli/openapi/api_resource_api.go
  cli/utils/api.go
  cli/utils/common.go
  server/openapi/api_resource_api_service.go
  tracetesting/features/environment/01_create_environment.yml
  tracetesting/features/environment/02_list_environment.yml
  tracetesting/features/environment/03_delete_environment.yml
  web/src/types/Generated.types.ts
Labels: CLI

#2450 examples+docs(github-actions): Add example app and CI/CD docs
  docs/docs/ci-cd-automation/github-actions-pipeline.md
  docs/docs/ci-cd-automation/overview.md
  docs/docs/configuration/overview.md
  docs/docs/deployment/overview.md
  docs/docs/examples-tutorials/overview.md
  docs/docs/examples-tutorials/recipes.md
  docs/docs/examples-tutorials/recipes/running-python-app-with-opentelemetry-collector-and-tracetest.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-aws-terraform.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-aws-x-ray-adot.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-aws-x-ray-pokeshop.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-aws-x-ray.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-datadog.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-elasticapm.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-jaeger.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-lightstep.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-new-relic.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-opensearch.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-step-functions-terraform.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-tempo.md
  docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store-with-manual-instrumentation.md
  docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store.md
  docs/docs/getting-started/installation.mdx
  docs/docs/tools-and-integrations/k6.md
  docs/docs/tools-and-integrations/overview.md
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/css/custom.css
  examples/quick-start-github-actions/.github/workflows/start-and-test-on-main.yaml
  examples/quick-start-github-actions/.github/workflows/start-and-test-on-schedule.yaml
  examples/quick-start-github-actions/.gitignore
  examples/quick-start-github-actions/Dockerfile
  examples/quick-start-github-actions/app.js
  examples/quick-start-github-actions/availability.js
  examples/quick-start-github-actions/docker-compose.yaml
  examples/quick-start-github-actions/package-lock.json
  examples/quick-start-github-actions/package.json
  examples/quick-start-github-actions/readme.md
  examples/quick-start-github-actions/tracetest/collector.config.yaml
  examples/quick-start-github-actions/tracetest/docker-compose.yaml
  examples/quick-start-github-actions/tracetest/tests/test-api-and-av.yaml
  examples/quick-start-github-actions/tracetest/tests/test-api.yaml
  examples/quick-start-github-actions/tracetest/tests/transaction-api.yaml
  examples/quick-start-github-actions/tracetest/tracetest-config.yaml
  examples/quick-start-github-actions/tracetest/tracetest-provision.yaml
  examples/quick-start-github-actions/tracing.otel.grpc.js
  examples/quick-start-github-actions/tracing.otel.http.js
Labels: documentation, examples
