Repository kubeshop/tracetest, pull requests merged in 2023-09, with the labels that each got.

#3121 feat(cli): cleanup and dynamic endpoint support
  api/version.yaml
  cli/cmd/config.go
  cli/cmd/legacy_test_cmd.go
  cli/cmd/resource_select_cmd.go
  cli/cmd/resources.go
  cli/cmd/root.go
  cli/cmd/start_cmd.go
  cli/config/config.go
  cli/config/configurator.go
  cli/openapi/model_version.go
  cli/pkg/starter/starter.go
  server/http/controller.go
  server/openapi/model_version.go
  web/src/types/Generated.types.ts
Labels: CLI

#3118 feat(frontend): add UI components to allow user actions
  web/src/components/AllowButton/AllowButton.tsx
  web/src/components/EditTest/EditTest.tsx
  web/src/components/EditTestSuite/EditTestSuite.tsx
  web/src/components/ResourceCard/ResourceCardActions.tsx
  web/src/components/RunActionsMenu/RunActionsMenu.tsx
  web/src/components/Settings/Analytics/AnalyticsForm.tsx
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/components/Settings/Demo/DemoForm.tsx
  web/src/components/Settings/Linter/LinterForm.tsx
  web/src/components/Settings/Polling/PollingForm.tsx
  web/src/components/Settings/TestRunner/TestRunnerForm.tsx
  web/src/components/TestOutputForm/TestOutputForm.tsx
  web/src/components/TestSpecForm/TestSpecForm.tsx
  web/src/components/TestSuiteRunActionsMenu/TestSuiteRunActionsMenu.tsx
  web/src/components/VariableSetSelector/VariableSetSelector.tsx
  web/src/components/VariableSetSelector/VariableSetSelectorEntry.tsx
  web/src/pages/Home/CreateButton.tsx
  web/src/pages/TestSuites/TestSuites.styled.tsx
  web/src/pages/VariableSet/VariableSet.styled.tsx
  web/src/pages/VariableSet/VariableSetCard.tsx
  web/src/pages/VariableSet/VariableSetContent.tsx
  web/src/pages/VariableSet/VariableSetList.tsx
Labels: frontend

#3122 feat(frontend): add flag to toggle the analytics page
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/BodyField/BodyFieldContainer.tsx
  web/src/components/CustomizationWrapper/CustomizationWrapper.tsx
  web/src/constants/Theme.constants.ts
  web/src/pages/Settings/Content.tsx
  web/src/providers/Customization/Customization.provider.tsx
  web/src/providers/Customization/index.ts
Labels: frontend

#3127 fix(frontend): fix method to parse url
  web/src/utils/Common.ts
Labels: frontend

#3134 fix(frontend): fix resource type in automate command
  web/src/services/CliCommand.service.ts
Labels: frontend

#3151 feat: add fe polling and disable websocket
  web/src/gateways/WebSocket.gateway.ts
  web/src/models/TestSuiteRun.model.ts
  web/src/providers/TestRun/TestRun.provider.tsx
  web/src/providers/TestSuiteRun/TestSuite.provider.tsx
  web/src/redux/apis/Tracetest/endpoints/Setting.endpoint.ts
  web/src/redux/apis/Tracetest/endpoints/TestRun.endpoint.ts
  web/src/redux/apis/Tracetest/endpoints/TestSuiteRun.endpoint.ts
Labels: frontend

#3155 fix(server): add composite primary key for single row resources
  server/config/demo/demo_repository.go
  server/datastore/datastore_repository.go
  server/executor/pollingprofile/polling_profile_repository.go
  server/executor/testrunner/testrunner_repository.go
  server/linter/analyzer/analyzer_repository.go
  server/migrations/33_add_composite_pkey.down.sql
  server/migrations/33_add_composite_pkey.up.sql
  server/pkg/sqlutil/tenant.go
Labels: backend

#3169 fix(cli): fix oauth flow
  cli/config/config.go
  cli/config/configurator.go
  cli/pkg/oauth/oauth.go
Labels: CLI

#3179 feat(server): support event properties header
  server/analytics/analytics.go
  server/app/app.go
  server/executor/assertion_runner.go
  server/executor/linter_runner.go
  server/executor/trace_poller.go
  server/executor/tracepollerworker/evaluator_worker.go
  server/executor/trigger_result_processor_worker.go
Labels: backend

#3185 fix(frontend): add posthog key as environment variable
  web/public/index.html
  web/src/services/Analytics/Analytics.service.ts
  web/src/types/Common.types.ts
  web/src/utils/Env.ts
Labels: frontend

#3193 feat(server): add segment user id
  server/analytics/segment.go
Labels: backend
