Repository kubeshop/tracetest, pull requests merged in 2023-01, with the labels that each got.

#1753 fix(server): fix test data store connection results
  server/tracedb/jaegerdb.go
  server/tracedb/opensearchdb.go
  server/tracedb/signalfxdb.go
  server/tracedb/tempodb.go
Labels: backend

#1757 fix(frontend): fixing overlapping icon
  web/src/components/FileViewerModal/FileViewerModal.styled.ts
Labels: frontend

#1758 fix(backend): ignoring incoming otel collector traffic when data store is not enabled
  local-config/collector.config.yaml
  server/otlp/server.go
Labels: backend

#1759 fix(frontend): fixing minor UX/UI issues
  web/src/components/AttributeRow/AttributeTitle.tsx
  web/src/components/CreateTestPlugins/Grpc/steps/RequestDetails/RequestDetails.styled.ts
  web/src/components/CreateTestPlugins/Grpc/steps/RequestDetails/RequestDetailsForm.tsx
  web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/UploadCollection.styled.ts
  web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/UploadCollectionForm.tsx
  web/src/components/OutputModal/OutputModal.styled.ts
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.styled.ts
  web/src/pages/Environments/EnvironmentModal.styled.ts
Labels: frontend

#1762 feature(backend): adding open api specs for variables
  api/openapi.yaml
  api/variables.yaml
  cli/openapi/api_api.go
  server/openapi/impl.go
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx
  web/src/models/DataStoreConfig.model.ts
  web/src/services/DataStore.service.ts
  web/src/services/DataStores/GrpcClient.service.ts
  web/src/services/DataStores/OpenSearch.service.ts
  web/src/services/DataStores/OtelCollector.service.ts
  web/src/services/DataStores/SignalFx.service.ts
  web/src/types/Generated.types.ts
Labels: backend

#1775 feature(frontend): implementing frontend logic for missing variables
  api/tests.yaml
  api/variables.yaml
  cli/openapi/model_run_information.go
  cli/openapi/model_test_variables.go
  examples/collector/collector.config.yaml
  server/expression/variables.go
  server/http/controller.go
  server/http/mappings/tests.go
  server/openapi/model_run_information.go
  server/openapi/model_test_variables.go
  server/testdb/runs.go
  web/src/components/Header/Header.tsx
  web/src/components/Layout/Layout.tsx
  web/src/components/MissingVariablesModal/MissingVariablesModal.styled.ts
  web/src/components/MissingVariablesModal/MissingVariablesModal.tsx
  web/src/components/MissingVariablesModal/MissingVariablesModalFooter.tsx
  web/src/components/MissingVariablesModal/MissingVariablesModalForm.tsx
  web/src/components/MissingVariablesModal/TestVariablesInput/TestListVariablesInput.tsx
  web/src/components/MissingVariablesModal/TestVariablesInput/TestVariableEntry.tsx
  web/src/components/MissingVariablesModal/hooks/useValidateVariablesDraft.ts
  web/src/components/MissingVariablesModal/index.ts
  web/src/components/NoTracingPopover/index.ts
  web/src/components/ResourceCard/TestCard.tsx
  web/src/components/ResourceCard/TransactionCard.tsx
  web/src/components/RunDetailLayout/HeaderRight.tsx
  web/src/components/TransactionHeader/TransactionHeader.tsx
  web/src/models/TestVariables.model.ts
  web/src/models/TransactionVariables.model.ts
  web/src/pages/Home/Resources.tsx
  web/src/pages/Test/Content.tsx
  web/src/pages/Transaction/Content.tsx
  web/src/providers/CreateTest/CreateTest.provider.tsx
  web/src/providers/CreateTransaction/CreateTransaction.provider.tsx
  web/src/providers/MissingVariablesModal/MissingVariablesModal.provider.tsx
  web/src/providers/MissingVariablesModal/index.ts
  web/src/providers/Test/Test.provider.tsx
  web/src/providers/Test/hooks/useTestCrud.ts
  web/src/providers/Transaction/Transaction.provider.tsx
  web/src/providers/Transaction/hooks/useTransactionCrud.ts
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/Test.endpoint.ts
  web/src/redux/apis/endpoints/TestRun.endpoints.ts
  web/src/redux/apis/endpoints/Transaction.endpoint.ts
  web/src/redux/apis/endpoints/TransactionRun.endpoint.ts
  web/src/services/Variables.service.ts
  web/src/types/Common.types.ts
  web/src/types/Generated.types.ts
  web/src/types/Variables.types.ts
Labels: frontend, backend

#1787 docs: add docs about creating test outputs using the UI
  docs/docs/img/test-outputs-01.png
  docs/docs/img/test-outputs-02.png
  docs/docs/img/test-outputs-03.png
  docs/docs/img/test-outputs-04.png
  docs/docs/img/test-outputs-05.png
  docs/docs/img/test-outputs-06.png
  docs/docs/img/test-outputs-07.png
  docs/docs/web-ui/creating-test-outputs.md
  docs/docs/web-ui/creating-test-specifications.md
  docs/sidebars.js
Labels: documentation

#1769 feat(frontend): redesign test outputs
  web/cypress/e2e/TestRunDetail/Outputs.spec.ts
  web/src/components/OutputModal/OutputModal.styled.ts
  web/src/components/OutputModal/OutputModal.tsx
  web/src/components/OutputModal/OutputModalFooter.tsx
  web/src/components/OutputModal/OutputModalForm.tsx
  web/src/components/OutputRow/OutputRowActions.tsx
  web/src/components/OutputRow/OutputValue.tsx
  web/src/components/RunDetailLayout/HeaderRight.tsx
  web/src/components/RunDetailTest/RunDetailTest.styled.ts
  web/src/components/RunDetailTest/RunDetailTest.tsx
  web/src/components/RunDetailTriggerResponse/ResponseOutputs.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx
  web/src/components/SpanDetail/SpanDetail.tsx
  web/src/components/TestActions/TestActions.tsx
  web/src/components/TestOutput/Actions.tsx
  web/src/components/TestOutput/TestOutput.styled.ts
  web/src/components/TestOutput/TestOutput.tsx
  web/src/components/TestOutput/index.ts
  web/src/components/TestOutputForm/SelectorInput.tsx
  web/src/components/TestOutputForm/TestOutputForm.styled.ts
  web/src/components/TestOutputForm/TestOutputForm.tsx
  web/src/components/TestOutputForm/hooks/useValidateOutput.ts
  web/src/components/TestOutputs/Empty.tsx
  web/src/components/TestOutputs/TestOutputs.styled.ts
  web/src/components/TestOutputs/TestOutputs.tsx
  web/src/components/TestOutputs/index.ts
  web/src/components/TestResults/Header.tsx
  web/src/components/TestResults/TestResults.styled.ts
  web/src/components/TestResults/TestResults.tsx
  web/src/components/TestSpecForm/TestSpecForm.provider.tsx
  web/src/constants/Common.constants.ts
  web/src/models/TestOutput.model.ts
  web/src/providers/TestOutput/TestOutput.provider.tsx
  web/src/redux/actions/TestSpecs.actions.ts
  web/src/redux/testOutputs/selectors.ts
  web/src/types/TestOutput.types.ts
Labels: frontend

#1792 chore(frontend): remove unused web docker file
  web/Dockerfile
Labels: frontend

#1805 feat: add elastic search as data store
  api/dataStores.yaml
  cli/installer/tracetest.go
  cli/openapi/api_api.go
  cli/openapi/model_data_store.go
  cli/openapi/model_elastic_search.go
  cli/openapi/model_supported_data_stores.go
  examples/quick-start-nodejs/docker-compose.yaml
  examples/quick-start-nodejs/tracing.otel.grpc.js
  server/config/config.go
  server/go.mod
  server/go.sum
  server/http/mappings/data_store.go
  server/model/data_stores.go
  server/openapi/model_data_store.go
  server/openapi/model_elastic_search.go
  server/openapi/model_open_search.go
  server/openapi/model_supported_data_stores.go
  server/testdb/data_stores.go
  server/testdb/data_stores_test.go
  server/tracedb/elasticsearchdb.go
  server/tracedb/opensearchdb.go
  server/tracedb/tracedb.go
  web/src/assets/elastic.svg
  web/src/components/Settings/DataStoreForm/DataStoreForm.styled.ts
  web/src/components/Settings/DataStorePlugin/DataStorePlugin.tsx
  web/src/components/Settings/DataStorePlugin/forms/ElasticSearch/AddressesList.tsx
  web/src/components/Settings/DataStorePlugin/forms/ElasticSearch/ElasticSearch.tsx
  web/src/components/Settings/DataStorePlugin/forms/ElasticSearch/index.ts
  web/src/constants/DataStore.constants.tsx
  web/src/models/DataStore.model.ts
  web/src/services/DataStore.service.ts
  web/src/services/DataStores/ElasticSearch.service.ts
  web/src/services/DataStores/OpenSearch.service.ts
  web/src/types/Config.types.ts
  web/src/types/Generated.types.ts
Labels: frontend, backend

#1813 fix(frontend): fix elastic search validation
  web/src/services/DataStores/ElasticSearch.service.ts
Labels: frontend

#1815 feature: adding support for new relic and lighstep
  api/dataStores.yaml
  cli/openapi/model_supported_data_stores.go
  server/model/data_stores.go
  server/openapi/model_supported_data_stores.go
  server/tracedb/tracedb.go
  web/src/assets/elastic.svg
  web/src/assets/jaeger.svg
  web/src/assets/openSearch.svg
  web/src/assets/otlp.svg
  web/src/assets/signalFx.svg
  web/src/assets/tempo.svg
  web/src/components/DataStoreIcon/DataStoreIcon.tsx
  web/src/components/DataStoreIcon/Icons/Elastic.tsx
  web/src/components/DataStoreIcon/Icons/Jaeger.tsx
  web/src/components/DataStoreIcon/Icons/Lightstep.tsx
  web/src/components/DataStoreIcon/Icons/NewrRelic.tsx
  web/src/components/DataStoreIcon/Icons/OpenSearch.tsx
  web/src/components/DataStoreIcon/Icons/Otlp.tsx
  web/src/components/DataStoreIcon/Icons/SignalFx.tsx
  web/src/components/DataStoreIcon/Icons/Tempo.tsx
  web/src/components/Settings/DataStore/DataStore.styled.ts
  web/src/components/Settings/DataStore/DataStore.tsx
  web/src/components/Settings/DataStoreForm/DataStoreForm.styled.ts
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/components/Settings/DataStoreForm/DataStoreSelectionInput.tsx
  web/src/components/Settings/DataStorePlugin/DataStorePlugin.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.styled.ts
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.tsx
  web/src/constants/CollectorConfig.constants.ts
  web/src/constants/DataStore.constants.tsx
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/providers/DataStore/hooks/useDataStoreNotification.tsx
  web/src/services/DataStore.service.ts
  web/src/services/DataStores/OtelCollector.service.ts
  web/src/types/Config.types.ts
  web/src/types/Generated.types.ts
Labels: frontend, backend

#1830 fix(frontend): fixing documentation links
  web/src/constants/DataStore.constants.tsx
Labels: frontend

#1840 feat(server): add traceid trigger
  api/traceid.yaml
  api/triggers.yaml
  go.work.sum
  server/app/app.go
  server/executor/runner.go
  server/executor/trigger/traceid.go
  server/http/controller.go
  server/http/mappings/tests.go
  server/http/mappings/traceid.go
  server/model/tests.go
  server/model/traceid.go
  server/model/yaml/test.go
  server/model/yaml/traceid.go
  server/openapi/impl.go
  server/openapi/model_traceid_request.go
  server/openapi/model_traceid_response.go
  server/openapi/model_trigger_result_trigger_result.go
  server/openapi/model_trigger_trigger_settings.go
  web/src/components/CreateTestPlugins/Plugins.ts
  web/src/components/CreateTestPlugins/TraceID/TraceID.ts
  web/src/components/CreateTestPlugins/TraceID/index.ts
  web/src/components/CreateTestPlugins/TraceID/steps/Value/Value.tsx
  web/src/components/CreateTestPlugins/TraceID/steps/Value/ValueForm.tsx
  web/src/components/CreateTestPlugins/TraceID/steps/Value/index.ts
  web/src/components/EditTestForm/EditRequestDetails/EditRequestDetails.tsx
  web/src/components/EditTestForm/EditRequestDetails/TraceID/TraceID.tsx
  web/src/components/EditTestForm/EditRequestDetails/TraceID/index.ts
  web/src/components/RunDetailTrigger/RunDetailTrigger.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerData.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponseFactory.tsx
  web/src/constants/Common.constants.ts
  web/src/constants/Plugins.constants.ts
  web/src/constants/Test.constants.ts
  web/src/models/TraceIDRequest.model.ts
  web/src/models/Trigger.model.ts
  web/src/models/TriggerResult.model.ts
  web/src/services/Test.service.ts
  web/src/services/Triggers/TraceID.service.ts
  web/src/types/Common.types.ts
  web/src/types/Generated.types.ts
  web/src/types/Test.types.ts
Labels: frontend, backend

#1856 fix(frontend): remove required test description
  web/src/components/CreateTestPlugins/Default/steps/BasicDetails/BasicDetailsForm.tsx
  web/src/services/Test.service.ts
Labels: frontend

#1860 feature(frontend): updating trace id trigger form
  web/src/components/CreateTestPlugins/TraceID/TraceID.ts
  web/src/components/CreateTestPlugins/TraceID/steps/VariableName/VariableName.tsx
  web/src/components/CreateTestPlugins/TraceID/steps/VariableName/VariableNameForm.tsx
  web/src/components/CreateTestPlugins/TraceID/steps/VariableName/index.ts
  web/src/components/EditTestForm/EditRequestDetails/TraceID/TraceID.tsx
  web/src/constants/Plugins.constants.ts
  web/src/services/Triggers/TraceID.service.ts
Labels: frontend

#1861 feat(frontend): add empty state in environment tab
  web/src/components/RunDetailTriggerResponse/ResponseEnvironment.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.styled.ts
  web/src/constants/Common.constants.ts
Labels: frontend

#1862 fix(frontend): fix output container styles
  web/src/components/TestOutput/TestOutput.styled.ts
Labels: frontend

#1865 fix(frontend): add transaction definition option in run card
  web/src/components/RunCard/TransactionRunCard.tsx
Labels: frontend

#1864 feat(frontend): pre fill selector when adding an output
  web/cypress/e2e/TestRunDetail/Outputs.spec.ts
  web/src/components/TestOutputForm/SelectorInput.tsx
  web/src/components/TestOutputForm/TestOutputForm.tsx
  web/src/components/TestOutputs/TestOutputs.tsx
  web/src/constants/Common.constants.ts
Labels: frontend

#1869 fix(frontend): multiple UX-UI fixes
  web/src/components/CreateTestPlugins/TraceID/steps/VariableName/VariableName.tsx
  web/src/components/KeyValueRow/KeyValueRow.styled.ts
  web/src/components/TestSpecForm/TestSpecForm.tsx
  web/src/components/TestSpecForm/hooks/useOnValuesChange.ts
  web/src/components/TransactionRunResult/ExecutionStep.tsx
  web/src/components/TransactionRunResult/TransactionRunResult.styled.ts
Labels: frontend

#1868 feat(frontend): add data store warning when saving config
  web/src/components/ConfirmationModal/ConfirmationModal.tsx
  web/src/providers/ConfirmationModal/ConfirmationModal.provider.tsx
  web/src/providers/DataStore/DataStore.provider.tsx
Labels: frontend

#1872 fix(frontend): fixing home page not refreshing after transaction or test run
  web/src/components/TransactionPlugin/steps/BasicDetails/BasicDetails.tsx
  web/src/redux/apis/endpoints/TestRun.endpoints.ts
  web/src/redux/apis/endpoints/TransactionRun.endpoint.ts
Labels: frontend

#1863 feat: missing variable detection on test/transaction run
  api/openapi.yaml
  api/variables.yaml
  cli/openapi/api_api.go
  cli/openapi/model_missing_variable.go
  cli/openapi/model_missing_variables_error.go
  cli/openapi/model_test_variables.go
  cli/openapi/model_variable.go
  cli/openapi/model_variables.go
  go.work.sum
  server/executor/runner_test.go
  server/executor/trigger/grpc.go
  server/executor/trigger/http.go
  server/executor/trigger/instrument.go
  server/executor/trigger/traceid.go
  server/executor/trigger/triggerer.go
  server/expression/executor.go
  server/expression/executor_test.go
  server/expression/linting/missing_variables.go
  server/expression/linting/missing_variables_test.go
  server/expression/parser_rules.go
  server/expression/parser_test.go
  server/expression/reflection_test.go
  server/expression/tokens.go
  server/expression/variables.go
  server/http/controller.go
  server/http/mappings/tests.go
  server/http/validation/variable.go
  server/model/grpc.go
  server/model/http.go
  server/model/tests.go
  server/openapi/api.go
  server/openapi/api_api.go
  server/openapi/impl.go
  server/openapi/model_missing_variable.go
  server/openapi/model_missing_variables.go
  server/openapi/model_missing_variables_error.go
  server/openapi/model_test_variables.go
  server/openapi/model_variable.go
  server/openapi/model_variables.go
  server/testdb/runs.go
  web/src/components/MissingVariablesModal/MissingVariablesModal.tsx
  web/src/components/MissingVariablesModal/MissingVariablesModalForm.tsx
  web/src/components/MissingVariablesModal/TestVariablesInput/TestListVariablesInput.tsx
  web/src/components/MissingVariablesModal/TestVariablesInput/TestVariableEntry.tsx
  web/src/models/RunError.model.ts
  web/src/models/TestVariables.model.ts
  web/src/models/TransactionVariables.model.ts
  web/src/providers/MissingVariablesModal/MissingVariablesModal.provider.tsx
  web/src/providers/Test/hooks/useTestCrud.ts
  web/src/providers/Transaction/hooks/useTransactionCrud.ts
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/Test.endpoint.ts
  web/src/redux/apis/endpoints/TestRun.endpoints.ts
  web/src/redux/apis/endpoints/Transaction.endpoint.ts
  web/src/redux/apis/endpoints/TransactionRun.endpoint.ts
  web/src/services/TestRun.service.ts
  web/src/services/Variables.service.ts
  web/src/types/Generated.types.ts
  web/src/types/TestRun.types.ts
  web/src/types/Variables.types.ts
Labels: frontend, backend

#1879 chore(k6): update examples and readme
  examples/tracetest-k6/README.md
  examples/tracetest-k6/import-pokemon.js
Labels: documentation

#1878 feature: adding summary report for transactions
  api/transactions.yaml
  cli/openapi/model_transaction_run.go
  server/http/mappings/tests.go
  server/migrations/18_add_transaction_run_result_counts.down.sql
  server/migrations/18_add_transaction_run_result_counts.up.sql
  server/model/tests.go
  server/model/transactions.go
  server/openapi/model_transaction_run.go
  server/testdb/runs.go
  server/testdb/transaction_runs.go
  server/testdb/transactions.go
  web/src/components/ResourceCard/ResourceCardSummary.tsx
  web/src/components/ResourceCard/TransactionCard.tsx
  web/src/components/RunCard/TransactionRunCard.tsx
  web/src/components/TransactionRunResult/ExecutionStep.tsx
  web/src/hooks/useValidateTransactionDraft.ts
  web/src/models/TransactionRun.model.ts
  web/src/types/Generated.types.ts
Labels: frontend, backend

#1896 feature: adding test run outputs UX/UI improvements
  api/tests.yaml
  cli/openapi/model_test_run_outputs.go
  server/executor/assertion_runner.go
  server/executor/outputs_processor.go
  server/executor/transaction_runner.go
  server/executor/transaction_runner_test.go
  server/http/mappings/tests.go
  server/model/run.go
  server/model/tests.go
  server/openapi/model_test_run_outputs.go
  server/testdb/runs.go
  server/testdb/runs_test.go
  web/src/components/AttributeList/AttributeList.tsx
  web/src/components/AttributeList/__tests__/AttributeList.test.tsx
  web/src/components/AttributeRow/AttributeRow.styled.ts
  web/src/components/AttributeRow/AttributeRow.tsx
  web/src/components/AttributeRow/__tests__/AttributeRow.test.tsx
  web/src/components/Editor/Expression/hooks/useAutoComplete.ts
  web/src/components/Editor/Interpolation/hooks/useAutoComplete.ts
  web/src/components/RunDetailTest/RunDetailTest.tsx
  web/src/components/SpanDetail/Attributes.tsx
  web/src/components/SpanDetail/SpanDetail.tsx
  web/src/components/TestOutput/TestOutput.styled.ts
  web/src/components/TestOutput/TestOutput.tsx
  web/src/components/TestOutputForm/TestOutputForm.tsx
  web/src/components/TestOutputMark/TestOutputMark.styled.ts
  web/src/components/TestOutputMark/TestOutputMark.tsx
  web/src/components/TestOutputMark/index.ts
  web/src/components/Visualization/components/DAG/SpanNode.styled.ts
  web/src/components/Visualization/components/DAG/SpanNode.tsx
  web/src/models/TestOutput.model.ts
  web/src/providers/TestOutput/TestOutput.provider.tsx
  web/src/redux/actions/TestSpecs.actions.ts
  web/src/redux/slices/DAG.slice.ts
  web/src/redux/slices/Span.slice.ts
  web/src/redux/testOutputs/selectors.ts
  web/src/redux/testOutputs/slice.ts
  web/src/selectors/Environment.selectors.ts
  web/src/services/SpanAttribute.service.ts
  web/src/types/Generated.types.ts
  web/src/types/TestOutput.types.ts
Labels: frontend, backend

#1902 fix(docs): fixing elasticapm docs url
  web/src/constants/DataStore.constants.tsx
Labels: documentation

#1901 chore(docs): adding k6 tracetest extension docs
  docs/docs/tools-and-integrations/integrations/k6.md
  docs/docs/tools-and-integrations/overview.md
  docs/sidebars.js
  examples/tracetest-k6/README.md
  examples/tracetest-k6/import-pokemon.js
Labels: documentation

#1903 feature: adding part of transaction info to the test run page
  api/tests.yaml
  cli/openapi/api_api.go
  cli/openapi/model_test_run.go
  server/http/mappings/tests.go
  server/model/tests.go
  server/openapi/model_test_run.go
  server/testdb/runs.go
  web/src/components/RunActionsMenu/RunActionsMenu.tsx
  web/src/components/RunCard/TestRunCard.tsx
  web/src/components/RunDetailLayout/HeaderLeft.tsx
  web/src/components/RunDetailLayout/HeaderRight.tsx
  web/src/components/RunDetailLayout/RunDetailLayout.styled.ts
  web/src/models/TestRun.model.ts
  web/src/types/Generated.types.ts
Labels: frontend, backend

#1900 fix(frontend): fix custom syntax linter in json editor
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/BodyField/useLanguageExtensionsMemo.tsx
  web/src/services/Editor.service.ts
Labels: frontend

#1906 fix(docs): fixing k6 docs
  docs/docs/tools-and-integrations/integrations/k6.md
Labels: documentation

#1908 fix(backend): fixing the get test run query join condition
  server/testdb/runs.go
Labels: backend
