Repository kubeshop/tracetest, pull requests merged in 2023-08, with the labels that each got.

#3018 chore(cli): Adding support for Variable Sets
  cli/cmd/legacy_test_cmd.go
  cli/cmd/middleware.go
  cli/cmd/resource_run_cmd.go
  cli/cmd/resources.go
  cli/openapi/api_resource_api.go
  cli/openapi/model_list_variable_sets_200_response.go
  cli/openapi/model_resolve_context.go
  cli/openapi/model_run_information.go
  cli/openapi/model_test_run.go
  cli/openapi/model_transaction_run.go
  cli/openapi/model_variable_set.go
  cli/openapi/model_variable_set_resource.go
  cli/openapi/model_variable_set_resource_list.go
  cli/openapi/model_variable_set_value.go
  cli/pkg/resourcemanager/apply.go
  cli/pkg/resourcemanager/client.go
  cli/pkg/resourcemanager/options.go
  cli/pkg/resourcemanager/registry.go
  cli/preprocessor/variableset.go
  cli/runner/orchestrator.go
  cli/runner/var_set.go
  examples/table-driven-test/table-test.bash
  testing/cli-e2etest/Makefile
  testing/cli-e2etest/README.md
  testing/cli-e2etest/testscenarios/environment/apply_environment_test.go
  testing/cli-e2etest/testscenarios/test/resources/deprecated-environment.yaml
  testing/cli-e2etest/testscenarios/test/resources/environment-file.yaml
  testing/cli-e2etest/testscenarios/test/resources/variableSet-file.yaml
  testing/cli-e2etest/testscenarios/test/run_test_test.go
  testing/cli-e2etest/testscenarios/types/environment.go
  testing/cli-e2etest/testscenarios/variableset/apply_variableset_test.go
  testing/cli-e2etest/testscenarios/variableset/delete_variableset_test.go
  testing/cli-e2etest/testscenarios/variableset/get_variableset_test.go
  testing/cli-e2etest/testscenarios/variableset/list_variablesets_test.go
  testing/cli-e2etest/testscenarios/variableset/resources/another-varSet.yaml
  testing/cli-e2etest/testscenarios/variableset/resources/deprecated-environment.yaml
  testing/cli-e2etest/testscenarios/variableset/resources/new-varSet.yaml
  testing/cli-e2etest/testscenarios/variableset/resources/one-more-varSet.yaml
  testing/cli-e2etest/testscenarios/variableset/resources/updated-new-varSet.yaml
  testing/server-tracetesting/features/environment/_test_suite.yml
  testing/server-tracetesting/features/variableset/01_create_variableset.yml
  testing/server-tracetesting/features/variableset/02_list_variableset.yml
  testing/server-tracetesting/features/variableset/03_delete_variableset.yml
  testing/server-tracetesting/features/variableset/_test_suite.yml
  testing/server-tracetesting/run.bash
  web/src/components/VariableSetSelector/AddVariableSet.tsx
  web/src/services/CliCommand.service.ts
Labels: CLI

#3031 fix(frontend): add history package to our dependencies
  web/package-lock.json
  web/package.json
Labels: frontend

#3055 fix(frontend): Improving attribute menu tooltip
  web/src/components/PulseButton/PulseButton.styled.ts
  web/src/components/PulseButton/index.ts
  web/src/components/ResizablePanels/LeftPanel.tsx
  web/src/components/ResizablePanels/ResizablePanels.styled.ts
  web/src/components/ResizablePanels/Splitter.tsx
  web/src/components/RunDetailTest/SpanDetailsPanel.tsx
  web/src/components/RunDetailTrace/SpanDetailsPanel.tsx
  web/src/hooks/useAttributePanelTooltip.ts
  web/src/services/UserPreferences.service.ts
  web/src/types/User.types.ts
Labels: frontend

#3051 chore(docs): Reflect the Transactions to Test Suites
  docs/docs/ci-cd-automation/github-actions-pipeline.md
  docs/docs/cli/creating-test-outputs.md
  docs/docs/cli/creating-test-suites.md
  docs/docs/cli/creating-transactions.md
  docs/docs/cli/running-test-suites.md
  docs/docs/cli/running-tests.md
  docs/docs/cli/undefined-variables.md
  docs/docs/concepts/ad-hoc-testing.md
  docs/docs/concepts/test-suites.md
  docs/docs/concepts/transactions.md
  docs/docs/concepts/variable-sets.md
  docs/docs/configuration/tracetest-analyzer.md
  docs/docs/getting-started/no-otel.mdx
  docs/docs/img/create-testsuite.png
  docs/docs/img/running-testsuite.png
  docs/docs/live-examples/opentelemetry-store/overview.md
  docs/docs/live-examples/opentelemetry-store/use-cases/user-purchasing-products.md
  docs/docs/live-examples/pokeshop/use-cases/get-pokemon-by-id.md
  docs/docs/tools-and-integrations/k6.md
  docs/docs/web-ui/creating-test-outputs.md
  docs/docs/web-ui/creating-test-suites.md
  docs/docs/web-ui/creating-transactions.md
  docs/docs/web-ui/editing-tests.md
  docs/docs/web-ui/undefined-variables.md
  docs/docusaurus.config.js
  docs/sidebars.js
Labels: documentation, do not merge

#3078 docs+examples: Add Signoz
  docs/docs/configuration/connecting-to-data-stores/signoz.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-honeycomb.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-signoz-pokeshop.md
  docs/sidebars.js
  examples/tracetest-signoz-pokeshop/.gitignore
  examples/tracetest-signoz-pokeshop/README.md
  examples/tracetest-signoz-pokeshop/docker-compose.yml
  examples/tracetest-signoz-pokeshop/signoz/alertmanager.yml
  examples/tracetest-signoz-pokeshop/signoz/alerts.yml
  examples/tracetest-signoz-pokeshop/signoz/clickhouse-cluster.xml
  examples/tracetest-signoz-pokeshop/signoz/clickhouse-config.xml
  examples/tracetest-signoz-pokeshop/signoz/clickhouse-storage.xml
  examples/tracetest-signoz-pokeshop/signoz/clickhouse-users.xml
  examples/tracetest-signoz-pokeshop/signoz/common/nginx-config.conf
  examples/tracetest-signoz-pokeshop/signoz/custom-function.xml
  examples/tracetest-signoz-pokeshop/signoz/otel-collector-config.yaml
  examples/tracetest-signoz-pokeshop/signoz/otel-collector-metrics-config.yaml
  examples/tracetest-signoz-pokeshop/signoz/prometheus.yml
  examples/tracetest-signoz-pokeshop/signoz/user_scripts/histogramQuantile
  examples/tracetest-signoz-pokeshop/signoz/user_scripts/histogramQuantile.go
  examples/tracetest-signoz-pokeshop/tests/curl_get.sh
  examples/tracetest-signoz-pokeshop/tests/curl_post.sh
  examples/tracetest-signoz-pokeshop/tests/test.yaml
  examples/tracetest-signoz-pokeshop/tracetest/collector.config.yaml
  examples/tracetest-signoz-pokeshop/tracetest/tracetest-config.yaml
  examples/tracetest-signoz-pokeshop/tracetest/tracetest-provision.yaml
Labels: documentation

#3079 fix(frontend): update antd layout background
  web/src/antd-theme/tracetest-antd-theme.less
Labels: frontend

#3100 feature(cli): Adding CLI cloud login and auth logic
  cli/actions/configure_action.go
  cli/cmd/config.go
  cli/cmd/configure_cmd.go
  cli/cmd/login_cmd.go
  cli/cmd/middleware.go
  cli/cmd/resources.go
  cli/cmd/root.go
  cli/config/config.go
  cli/pkg/oauth/oauth.go
  cli/pkg/resourcemanager/client.go
  cli/utils/api.go
Labels: CLI

#3112 feature(frontend): Adding customizable logic
  web/src/App.tsx
  web/src/BaseApp.tsx
  web/src/components/AllowButton/AllowButton.tsx
  web/src/components/AllowButton/index.ts
  web/src/components/CustomizationWrapper/CustomizationWrapper.tsx
  web/src/components/CustomizationWrapper/index.ts
  web/src/components/Header/Header.tsx
  web/src/components/Layout/Layout.tsx
  web/src/components/Router/Router.tsx
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/providers/Customization/Customization.provider.tsx
  web/src/providers/Customization/WithCustomization.tsx
  web/src/providers/Customization/index.ts
Labels: frontend
