Repository kubeshop/tracetest, pull requests merged in 2023-03, with the labels that each got.

#2064 feature(examples): adding aws step functions example
  examples/tracetest-aws-step-functions/.gitignore
  examples/tracetest-aws-step-functions/README.md
  examples/tracetest-aws-step-functions/assets/functions.png
  examples/tracetest-aws-step-functions/assets/settings.png
  examples/tracetest-aws-step-functions/infra/.terraform.lock.hcl
  examples/tracetest-aws-step-functions/infra/README.md
  examples/tracetest-aws-step-functions/infra/alb.tf
  examples/tracetest-aws-step-functions/infra/main.tf
  examples/tracetest-aws-step-functions/infra/network.tf
  examples/tracetest-aws-step-functions/infra/outputs.tf
  examples/tracetest-aws-step-functions/infra/tracetest.tf
  examples/tracetest-aws-step-functions/infra/variables.tf
  examples/tracetest-aws-step-functions/src/.gitignore
  examples/tracetest-aws-step-functions/src/AWSStepFunctionsPlagiarismDemo.sln
  examples/tracetest-aws-step-functions/src/AdminActionTask/AdminActionTask.csproj
  examples/tracetest-aws-step-functions/src/AdminActionTask/Function.cs
  examples/tracetest-aws-step-functions/src/Plagiarism/ExamNotFoundException.cs
  examples/tracetest-aws-step-functions/src/Plagiarism/Incident.cs
  examples/tracetest-aws-step-functions/src/Plagiarism/IncidentNotFoundException.cs
  examples/tracetest-aws-step-functions/src/Plagiarism/Plagiarism.csproj
  examples/tracetest-aws-step-functions/src/Plagiarism/StudentExceededAllowableExamRetries.cs
  examples/tracetest-aws-step-functions/src/PlagiarismRepository.Tests/PlagiarismRepository.Tests.csproj
  examples/tracetest-aws-step-functions/src/PlagiarismRepository.Tests/RepositoryTests.cs
  examples/tracetest-aws-step-functions/src/PlagiarismRepository/IIncidentRepository.cs
  examples/tracetest-aws-step-functions/src/PlagiarismRepository/IncidentRepository.cs
  examples/tracetest-aws-step-functions/src/PlagiarismRepository/PlagiarismRepository.csproj
  examples/tracetest-aws-step-functions/src/README.md
  examples/tracetest-aws-step-functions/src/RegisterIncidentTask/Function.cs
  examples/tracetest-aws-step-functions/src/RegisterIncidentTask/RegisterIncidentTask.csproj
  examples/tracetest-aws-step-functions/src/ResolveIncidentTask.Tests/FunctionTests.cs
  examples/tracetest-aws-step-functions/src/ResolveIncidentTask.Tests/ResolveIncidentTask.Tests.csproj
  examples/tracetest-aws-step-functions/src/ResolveIncidentTask/Function.cs
  examples/tracetest-aws-step-functions/src/ResolveIncidentTask/ResolveIncidentTask.csproj
  examples/tracetest-aws-step-functions/src/ScheduleExamTask/Function.cs
  examples/tracetest-aws-step-functions/src/ScheduleExamTask/ScheduleExamTask.csproj
  examples/tracetest-aws-step-functions/src/SendNotificationTask.Tests/FunctionTests.cs
  examples/tracetest-aws-step-functions/src/SendNotificationTask.Tests/SendNotificationTask.Tests.csproj
  examples/tracetest-aws-step-functions/src/SendNotificationTask/Function.cs
  examples/tracetest-aws-step-functions/src/SendNotificationTask/SendNotificationTask.csproj
  examples/tracetest-aws-step-functions/src/SubmitExamTask.Tests/FunctionTests.cs
  examples/tracetest-aws-step-functions/src/SubmitExamTask.Tests/SubmitExamTask.Tests.csproj
  examples/tracetest-aws-step-functions/src/SubmitExamTask.Tests/event.json
  examples/tracetest-aws-step-functions/src/SubmitExamTask/Function.cs
  examples/tracetest-aws-step-functions/src/SubmitExamTask/SubmitExamTask.csproj
  examples/tracetest-aws-step-functions/src/omnisharp.json
  examples/tracetest-aws-step-functions/src/state-machine.asl.json
  examples/tracetest-aws-step-functions/src/template.yaml
  examples/tracetest-aws-step-functions/tests/exam.yaml
  examples/tracetest-aws-step-functions/tests/incident.yaml
  examples/tracetest-aws-step-functions/tests/transaction.yaml
  server/executor/trigger/http.go
  server/tracedb/awsxray.go
Labels: backend, examples

#2088 docs: update examples config an documentation
  docs/docs/examples-tutorials/recipes/running-tracetest-with-jaeger.md
  docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store.md
  examples/tracetest-datadog/tracetest/tracetest.config.yaml
  examples/tracetest-elasticapm-with-elastic-agent/docker-compose.yaml
  examples/tracetest-elasticapm-with-elastic-agent/tracetest-config.yaml
  examples/tracetest-elasticapm-with-elastic-agent/tracetest-provision.yaml
  examples/tracetest-elasticapm-with-otel/docker-compose.yaml
  examples/tracetest-elasticapm-with-otel/tracetest-config.yaml
  examples/tracetest-elasticapm-with-otel/tracetest-provision.yaml
  examples/tracetest-jaeger/docker-compose.yml
  examples/tracetest-jaeger/tracetest-config.yaml
  examples/tracetest-jaeger/tracetest-provision.yaml
  examples/tracetest-signalfx/docker-compose.yml
  examples/tracetest-signalfx/tracetest-config.yaml
  examples/tracetest-signalfx/tracetest-provision.yaml
  examples/tracetest-tempo/docker-compose.yml
  examples/tracetest-tempo/tracetest-config.yaml
  examples/tracetest-tempo/tracetest-provision.yaml
Labels: examples

#2089 docs: fix examples to use provision file
  examples/collector/docker-compose.yml
  examples/collector/tracetest-provision.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part1/tracetest/docker-compose.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part1/tracetest/tracetest-provision.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part1/tracetest/tracetest.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part2.1/tracetest/docker-compose.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part2.1/tracetest/tracetest-provision.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part2.1/tracetest/tracetest.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part2.2/tracetest/docker-compose.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part2.2/tracetest/tracetest-provision.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part2.2/tracetest/tracetest.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part3.1/tracetest/docker-compose.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part3.1/tracetest/tracetest-provision.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part3.1/tracetest/tracetest.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part3.2/tracetest/docker-compose.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part3.2/tracetest/tracetest-provision.yaml
  examples/observability-driven-development-go-tracetest/bookstore/part3.2/tracetest/tracetest.yaml
  examples/quick-start-datadog-nodejs/tracetest/docker-compose.yaml
  examples/quick-start-datadog-nodejs/tracetest/tracetest-provision.yaml
  examples/quick-start-datadog-nodejs/tracetest/tracetest.config.yaml
  examples/quick-start-go/tracetest/docker-compose.yaml
  examples/quick-start-go/tracetest/tracetest-provision.yaml
  examples/quick-start-go/tracetest/tracetest.config.yaml
  examples/quick-start-jaeger-nodejs/tracetest/docker-compose.yaml
  examples/quick-start-jaeger-nodejs/tracetest/tracetest-provision.yaml
  examples/quick-start-jaeger-nodejs/tracetest/tracetest.config.yaml
Labels: examples

#2091 fix(examples): fix config examples and docs
  docs/docs/examples-tutorials/recipes/running-tracetest-with-lightstep.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-new-relic.md
  examples/tracetest-k6/docker-compose.yml
  examples/tracetest-k6/tracetest-config.yaml
  examples/tracetest-k6/tracetest-provision.yaml
  examples/tracetest-lightstep-otel-demo/README.md
  examples/tracetest-lightstep-otel-demo/docker-compose.yaml
  examples/tracetest-lightstep-otel-demo/tracetest/tracetest-provision.yaml
  examples/tracetest-lightstep-otel-demo/tracetest/tracetest.config.yaml
  examples/tracetest-lightstep/tracetest/docker-compose.yaml
  examples/tracetest-lightstep/tracetest/tracetest-provision.yaml
  examples/tracetest-lightstep/tracetest/tracetest.config.yaml
  examples/tracetest-new-relic-otel-demo/README.md
  examples/tracetest-new-relic-otel-demo/docker-compose.yaml
  examples/tracetest-new-relic-otel-demo/tracetest/tracetest-provision.yaml
  examples/tracetest-new-relic-otel-demo/tracetest/tracetest.config.yaml
  examples/tracetest-new-relic/tracetest/docker-compose.yaml
  examples/tracetest-new-relic/tracetest/tracetest-provision.yaml
  examples/tracetest-new-relic/tracetest/tracetest.config.yaml
Labels: examples

#2097 Updating examples with our latest config changes
  docs/docs/examples-tutorials/recipes.md
  docs/sidebars.js
  examples/tracetest-open-telemetry-store-demo/README.md
  examples/tracetest-open-telemetry-store-demo/docker-compose.yml
  examples/tracetest-open-telemetry-store-demo/tracetest-config.yaml
  examples/tracetest-open-telemetry-store-demo/tracetest-provision.yaml
  examples/tracetest-opensearch/README.md
  examples/tracetest-opensearch/docker-compose.yml
  examples/tracetest-opensearch/tracetest-config.yaml
  examples/tracetest-opensearch/tracetest-provision.yaml
  examples/tracetest-otel-demo/README.md
  examples/tracetest-provisioning-env/README.md
Labels: examples

#2000 feat(frontend): add analytics and polling settings
  web/src/components/DataStoreIcon/DataStoreIcon.tsx
  web/src/components/Layout/Layout.tsx
  web/src/components/Settings/Analytics/Analytics.tsx
  web/src/components/Settings/Analytics/AnalyticsForm.tsx
  web/src/components/Settings/Analytics/index.ts
  web/src/components/Settings/DataStore/DataStore.tsx
  web/src/components/Settings/DataStoreDocsBanner/DataStoreDocsBanner.tsx
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/components/Settings/DataStoreForm/DataStoreSelectionInput.tsx
  web/src/components/Settings/DataStorePlugin/DataStoreComponentFactory.tsx
  web/src/components/Settings/DataStorePlugin/DataStorePlugin.tsx
  web/src/components/Settings/DataStorePlugin/forms/AwsXRay/AwsXRay.tsx
  web/src/components/Settings/DataStorePlugin/forms/BaseClient/BaseClient.tsx
  web/src/components/Settings/DataStorePlugin/forms/ElasticSearch/ElasticSearch.tsx
  web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx
  web/src/components/Settings/DataStorePlugin/forms/HttpClient/HttpClient.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.tsx
  web/src/components/Settings/DataStorePlugin/forms/SignalFx/SignalFx.tsx
  web/src/components/Settings/Demo/Demo.tsx
  web/src/components/Settings/Demo/DemoForm.tsx
  web/src/components/Settings/Demo/OtelFields.tsx
  web/src/components/Settings/Demo/PokeshopFields.tsx
  web/src/components/Settings/Demo/index.ts
  web/src/components/Settings/Polling/Polling.tsx
  web/src/components/Settings/Polling/PollingForm.tsx
  web/src/components/Settings/Polling/index.ts
  web/src/components/Settings/common/Settings.styled.ts
  web/src/components/TestConnectionNotification/TestConnectionNotification.tsx
  web/src/components/TestConnectionNotification/TestConnectionStep.tsx
  web/src/constants/CollectorConfig.constants.ts
  web/src/constants/Common.constants.ts
  web/src/constants/DataStore.constants.tsx
  web/src/models/DataStore.model.ts
  web/src/models/DataStoreConfig.model.ts
  web/src/pages/Settings/Content.tsx
  web/src/pages/Settings/Settings.tsx
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/providers/DataStore/hooks/useDataStoreNotification.tsx
  web/src/providers/DataStoreConfig/DataStoreConfig.provider.tsx
  web/src/providers/Settings/Settings.provider.tsx
  web/src/providers/Settings/index.ts
  web/src/redux/apis/endpoints/Config.endpoint.ts
  web/src/services/DataStore.service.ts
  web/src/services/DataStores/AwsXRay.service.ts
  web/src/services/DataStores/BaseClient.service.ts
  web/src/services/DataStores/ElasticSearch.service.ts
  web/src/services/DataStores/GrpcClient.service.ts
  web/src/services/DataStores/HttpClient.service.ts
  web/src/services/DataStores/Jaeger.service.ts
  web/src/services/DataStores/OtelCollector.service.ts
  web/src/services/DataStores/SignalFx.service.ts
  web/src/types/DataStore.types.ts
  web/src/types/Settings.types.ts
Labels: frontend

#2093 chore(docs): Adding terraform x AWS Fargate recipe page
  docs/docs/examples-tutorials/img/terraform-output.png
  docs/docs/examples-tutorials/img/terraform-serverless-diagram.png
  docs/docs/examples-tutorials/recipes.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-aws-terraform.md
  docs/sidebars.js
  examples/tracetest-aws-terraform-serverless/alb.tf
  examples/tracetest-aws-terraform-serverless/api.tf
  examples/tracetest-aws-terraform-serverless/apigateway.tf
  examples/tracetest-aws-terraform-serverless/jaeger.tf
  examples/tracetest-aws-terraform-serverless/lambda.tf
  examples/tracetest-aws-terraform-serverless/network.tf
  examples/tracetest-aws-terraform-serverless/s3.tf
  examples/tracetest-aws-terraform-serverless/tracetest.tf
  examples/tracetest-aws-terraform-serverless/variables.tf
Labels: documentation, examples

#2099 chore(docs): adding aws step functions recipe documentation
  docs/docs/examples-tutorials/img/aws-step-functions.png
  docs/docs/examples-tutorials/img/awsxray-settings.png
  docs/docs/examples-tutorials/img/sam-step-functions.png
  docs/docs/examples-tutorials/img/terraform-step-functions.png
  docs/docs/examples-tutorials/recipes/running-tracetest-with-step-functions-terraform.md
  docs/sidebars.js
  examples/tracetest-aws-step-functions/infra/alb.tf
  examples/tracetest-aws-step-functions/infra/network.tf
Labels: documentation, examples

#2126 feature(cli): adding support for config resource
  cli/actions/config.go
  cli/actions/resource.go
  cli/cmd/apply_cmd.go
  cli/cmd/config.go
  cli/cmd/configure_cmd.go
  cli/cmd/datastore_apply_cmd.go
  cli/cmd/datastore_export_cmd.go
  cli/cmd/datastore_list_cmd.go
  cli/cmd/delete_cmd.go
  cli/cmd/environment_apply.go
  cli/cmd/get_cmd.go
  cli/cmd/list_cmd.go
  cli/cmd/test_export_cmd.go
  cli/cmd/test_list_cmd.go
  cli/cmd/test_run_cmd.go
  cli/formatters/config.go
  cli/openapi/api_api.go
  cli/openapi/api_resource_api.go
  cli/openapi/client.go
  cli/openapi/model_configuration_resource.go
  cli/openapi/model_configuration_resource_spec.go
  cli/openapi/model_polling_profile.go
  cli/openapi/model_polling_profile_spec.go
  cli/openapi/model_polling_profile_spec_periodic.go
  cli/utils/api.go
  go.work.sum
  server/model/yaml/encoding.go
  server/model/yaml/encoding_test.go
  server/model/yaml/file.go
  server/model/yaml/testdata/config_resource.yaml
  server/resourcemanager/encoding.go
Labels: CLI

#2108 feat(frontend): integrate config settings with API
  web/package-lock.json
  web/package.json
  web/public/index.html
  web/src/App.tsx
  web/src/components/Layout/Layout.tsx
  web/src/components/Settings/Analytics/AnalyticsForm.tsx
  web/src/components/Settings/DataStore/DataStore.tsx
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/components/Settings/DataStoreForm/DataStoreSelectionInput.tsx
  web/src/components/Settings/Demo/DemoForm.tsx
  web/src/components/Settings/Polling/PollingForm.tsx
  web/src/components/SetupAlert/SetupAlert.tsx
  web/src/constants/Test.constants.ts
  web/src/index.tsx
  web/src/models/Config.model.ts
  web/src/models/Polling.model.ts
  web/src/pages/Home/Home.tsx
  web/src/pages/Settings/Content.tsx
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/providers/DataStoreConfig/index.ts
  web/src/providers/Settings/Settings.provider.tsx
  web/src/providers/SettingsValues/SettingsValues.provider.tsx
  web/src/providers/SettingsValues/index.ts
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/DataStore.endpoint.ts
  web/src/redux/apis/endpoints/Setting.endpoint.ts
  web/src/services/Analytics/Analytics.service.ts
  web/src/types/Common.types.ts
  web/src/types/Settings.types.ts
  web/src/utils/Env.ts
Labels: frontend

#2140 feat(frontend): integrate pollingprofile settings with API
  web/src/components/Settings/Polling/PollingForm.tsx
  web/src/models/Polling.model.ts
  web/src/pages/Settings/Content.tsx
  web/src/types/Settings.types.ts
Labels: frontend

#2139 feat(server): add config analytics provision
  server/app/app.go
  server/provisioning/config.go
  server/provisioning/data_stores_test.go
  server/provisioning/provisioning.go
  server/provisioning/provisioning_test.go
Labels: backend

#2129 feat(frontend): integrate demo settings with API
  api/config.yaml
  web/cypress/e2e/Home/CreateTest.spec.ts
  web/cypress/e2e/Home/CreateTestFromCurl.spec.ts
  web/cypress/e2e/Home/CreateTestFromPostman.spec.ts
  web/cypress/e2e/Home/CreateTestWithAuthentication.spec.ts
  web/cypress/e2e/TraceDetails/ShowTestDetails.spec.ts
  web/cypress/e2e/constants/Test.ts
  web/cypress/e2e/constants/Transactions.ts
  web/cypress/support/commands.ts
  web/cypress/support/index.d.ts
  web/public/index.html
  web/src/components/CreateTestPlugins/Default/steps/BasicDetails/BasicDetails.tsx
  web/src/components/CreateTestPlugins/Default/steps/BasicDetails/BasicDetailsForm.tsx
  web/src/components/Settings/Analytics/AnalyticsForm.tsx
  web/src/components/Settings/Demo/DemoForm.tsx
  web/src/components/Settings/Demo/OtelFields.tsx
  web/src/components/Settings/Demo/PokeshopFields.tsx
  web/src/components/Settings/Polling/PollingForm.tsx
  web/src/constants/Demo.constants.ts
  web/src/constants/Plugins.constants.ts
  web/src/models/Config.model.ts
  web/src/models/Demo.model.ts
  web/src/models/Polling.model.ts
  web/src/pages/Settings/Content.tsx
  web/src/providers/CreateTest/CreateTest.provider.tsx
  web/src/providers/Settings/Settings.provider.tsx
  web/src/providers/SettingsValues/SettingsValues.provider.tsx
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/Setting.endpoint.ts
  web/src/selectors/CreateTest.selectors.ts
  web/src/selectors/__tests__/CreateTest.selectors.test.ts
  web/src/services/Setting.service.ts
  web/src/types/Common.types.ts
  web/src/types/Generated.types.ts
  web/src/types/Settings.types.ts
  web/src/utils/Env.ts
Labels: frontend

#2113 feature(frontend): implementing notification system
  web/src/components/AttributeList/AttributeList.tsx
  web/src/components/AttributeRow/AttributeRow.tsx
  web/src/components/AttributeRow/__tests__/AttributeRow.test.tsx
  web/src/components/FileViewerModal/FileViewerModal.tsx
  web/src/components/HeaderRow/HeaderRow.tsx
  web/src/components/Layout/Layout.tsx
  web/src/components/RunDetailLayout/RunDetailLayout.tsx
  web/src/components/RunDetailTriggerResponse/ResponseHeaders.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.tsx
  web/src/constants/Theme.constants.ts
  web/src/hooks/useCopy.ts
  web/src/hooks/useDeleteResource.tsx
  web/src/hooks/useNotification.tsx
  web/src/providers/ConfirmationModal/ConfirmationModal.provider.tsx
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/providers/DataStore/hooks/useDataStoreNotification.tsx
  web/src/providers/Environment/hooks/useEnvironmentCrud.ts
  web/src/providers/GuidedTour/GuidedTour.provider.tsx
  web/src/providers/Notification/Notification.provider.tsx
  web/src/providers/Notification/index.ts
  web/src/providers/Settings/Settings.provider.tsx
  web/src/providers/TestSpecs/hooks/useTestSpecsCrud.ts
  web/src/styled.d.ts
Labels: frontend

#2160 feature(cli): adding support for the demo resource
  cli/actions/config.go
  cli/actions/demo.go
  cli/actions/polling.go
  cli/actions/resource.go
  cli/cmd/config.go
  cli/cmd/export_cmd.go
  cli/file/definition.go
  cli/formatters/config.go
  cli/formatters/pollingprofile.go
  cli/formatters/pollingprofile_list.go
  cli/openapi/model_demo_open_telemetry_store.go
  cli/openapi/model_demo_pokeshop.go
  cli/openapi/model_demo_spec.go
  cli/openapi/model_polling_profile_spec.go
  cli/utils/api.go
  cli/utils/common.go
  server/model/yaml/encoding.go
  server/model/yaml/encoding_test.go
  server/model/yaml/testdata/config_resource.yaml
Labels: CLI

#2172 feature(frontend): adding live updates for analytics changes
  web/src/models/Config.model.ts
  web/src/redux/apis/endpoints/Setting.endpoint.ts
Labels: frontend

#2195 feature(cli): adding resource cmd CLI validations
  cli/actions/demo.go
  cli/cmd/apply_cmd.go
  cli/cmd/delete_cmd.go
  cli/cmd/export_cmd.go
  cli/cmd/get_cmd.go
Labels: CLI

#2211 chore(examples): fixing second batch of examples
  examples/tracetest-aws-step-functions/infra/tracetest.tf
  examples/tracetest-aws-step-functions/infra/variables.tf
  examples/tracetest-datadog/docker-compose.yaml
  examples/tracetest-datadog/http-test.yaml
  examples/tracetest-datadog/tracetest/docker-compose.yaml
  examples/tracetest-datadog/tracetest/tracetest-config.yaml
  examples/tracetest-elasticapm-with-elastic-agent/docker-compose.yaml
  examples/tracetest-elasticapm-with-otel/docker-compose.yaml
  examples/tracetest-k6/docker-compose.yml
  examples/tracetest-lightstep-otel-demo/docker-compose.yaml
  examples/tracetest-lightstep-otel-demo/tracetest/tracetest-provision.yaml
  examples/tracetest-lightstep-otel-demo/tracetest/tracetest.config.yaml
  examples/tracetest-lightstep/docker-compose.yaml
  examples/tracetest-lightstep/tracetest/tracetest-provision.yaml
Labels: examples

#2226 fix(frontend): fixing multiple UX/UI issues
  web/src/assets/more.svg
  web/src/components/AttributeRow/AttributeRow.styled.ts
  web/src/components/AttributeRow/AttributeRow.tsx
  web/src/components/CreateTestPlugins/Default/steps/BasicDetails/BasicDetailsForm.tsx
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsHeadersInput.tsx
  web/src/components/GuidedTour/testRunSteps.ts
  web/src/components/Settings/DataStorePlugin/DataStorePluginForm.styled.ts
  web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx
  web/src/components/Settings/DataStorePlugin/forms/HttpClient/HttpClient.tsx
Labels: frontend

#2239 fix(frontend): rename publish button to save
  web/src/components/TestActions/TestActions.tsx
  web/src/providers/TestSpecs/hooks/useTestSpecsCrud.ts
Labels: frontend

#2240 fix(docs): fix deployment page to match new config file
  docs/docs/deployment/docker.md
  docs/docs/deployment/overview.md
Labels: documentation

#2243 fix(frontend): fix links in test run tabs
  web/src/components/RunDetailLayout/RunDetailLayout.styled.ts
Labels: frontend

#2238 fix(frontend): remove settings confirmation modal
  web/cypress/support/commands.ts
  web/src/providers/Settings/Settings.provider.tsx
Labels: frontend

#2274 feat(frontend): add error handling for trigger section
  web/src/components/FailedTrace/FailedTrace.styled.ts
  web/src/components/FailedTrace/FailedTrace.tsx
  web/src/components/FailedTrace/__tests__/FailedTrace.test.tsx
  web/src/components/RunDetailLayout/RunDetailLayout.tsx
  web/src/components/RunDetailTrigger/RunDetailTrigger.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.styled.ts
  web/src/components/RunDetailTriggerResponse/SkeletonResponse.tsx
  web/src/components/RunEvents/RunEvent.tsx
  web/src/components/RunEvents/RunEvents.styled.ts
  web/src/components/RunEvents/RunEvents.tsx
  web/src/components/RunEvents/RunEventsTrigger.tsx
  web/src/components/RunEvents/index.ts
  web/src/models/TestRunEvent.model.ts
  web/src/models/__mocks__/TestRunEvent.mock.ts
  web/src/providers/TestRun/TestRun.provider.tsx
  web/src/redux/apis/TraceTest.api.ts
  web/src/redux/apis/endpoints/TestRun.endpoints.ts
  web/src/services/TestRun.service.ts
  web/src/types/Common.types.ts
Labels: frontend

#2282 feat(frontend): add error handling for trace section
  web/src/components/RunDetailLayout/RunDetailLayout.tsx
  web/src/components/RunDetailTest/RunDetailTest.tsx
  web/src/components/RunDetailTest/Visualization.tsx
  web/src/components/RunDetailTrace/RunDetailTrace.tsx
  web/src/components/RunDetailTrace/Visualization.tsx
  web/src/components/RunDetailTrigger/RunDetailTrigger.tsx
  web/src/components/RunEvents/RunEvent.tsx
  web/src/components/RunEvents/RunEventDataStore.tsx
  web/src/components/RunEvents/RunEventPolling.tsx
  web/src/components/RunEvents/RunEvents.styled.ts
  web/src/components/RunEvents/RunEvents.tsx
  web/src/components/RunEvents/RunEventsTrace.tsx
  web/src/components/RunEvents/RunEventsTrigger.tsx
  web/src/components/SkeletonDiagram/SkeletonDiagram.styled.ts
  web/src/components/SkeletonDiagram/SkeletonDiagram.tsx
  web/src/components/SkeletonDiagram/SkeletonNode.tsx
  web/src/components/SkeletonDiagram/__tests__/SkeletonDiagram.test.tsx
  web/src/components/SkeletonDiagram/index.ts
  web/src/constants/TestRunEvents.constants.ts
  web/src/models/TestRunEvent.model.ts
  web/src/redux/apis/endpoints/TestRun.endpoints.ts
  web/src/services/TestRun.service.ts
Labels: frontend
