Repository kubeshop/tracetest, pull requests merged in 2023-02, with the labels that each got.

#1922 feat(frontend): add outputs for each test in transaction page
  web/src/components/TransactionRunResult/ExecutionStep.tsx
  web/src/components/TransactionRunResult/TransactionRunResult.styled.ts
Labels: frontend

#1943 fix(docs): fix docker compose installation note
  docs/docs/getting-started/installation.md
Labels: documentation

#1917 feature: add support for test specs names
  cli/formatters/test_run.go
  cli/formatters/test_run_test.go
  web/src/components/RunDetailTest/RunDetailTest.tsx
  web/src/components/TestResults/TestResults.tsx
  web/src/components/TestSpec/Header.tsx
  web/src/components/TestSpec/TestSpec.styled.ts
  web/src/components/TestSpec/TestSpec.tsx
  web/src/components/TestSpecDetail/Content.tsx
  web/src/components/TestSpecDetail/Header.tsx
  web/src/components/TestSpecDetail/TestSpecDetail.styled.ts
  web/src/components/TestSpecDetail/TestSpecDetail.tsx
  web/src/components/TestSpecForm/TestSpecForm.provider.tsx
  web/src/components/TestSpecForm/TestSpecForm.tsx
  web/src/components/TestSpecs/TestSpecs.tsx
  web/src/models/AssertionResults.model.ts
  web/src/models/TestSpecs.model.ts
  web/src/providers/TestSpecs/TestSpecs.provider.tsx
  web/src/providers/TestSpecs/hooks/useTestSpecsCrud.ts
  web/src/redux/actions/Router.actions.ts
  web/src/redux/slices/TestSpecs.slice.ts
  web/src/redux/slices/__tests__/TestSpecs.slice.test.ts
  web/src/services/TestDefinition.service.ts
  web/src/services/__tests__/TestDefinition.service.test.ts
  web/src/types/Test.types.ts
  web/src/types/TestSpecs.types.ts
Labels: frontend

#1951 feat(frontend): add posthog script
  web/package-lock.json
  web/package.json
  web/src/services/Analytics/Analytics.service.ts
Labels: frontend

#1955 fix(cli): check TRACETEST_DEV env to disable analytics
  cli/analytics/analytics.go
  server/app/app.go
Labels: CLI

#1985 docs: add testkube integration docs
  docs/docs/tools-and-integrations/integrations/testkube.md
  docs/docs/tools-and-integrations/overview.md
  docs/sidebars.js
Labels: documentation

#1940 added quick-start golang app in example
  examples/quick-start-go/Dockerfile
  examples/quick-start-go/docker-compose.yaml
  examples/quick-start-go/go.mod
  examples/quick-start-go/go.sum
  examples/quick-start-go/main.go
  examples/quick-start-go/readme.md
  examples/quick-start-go/test-api.yaml
  examples/quick-start-go/tracetest/collector.config.yaml
  examples/quick-start-go/tracetest/docker-compose.yaml
  examples/quick-start-go/tracetest/tracetest.config.yaml
  examples/quick-start-python/Dockerfile
  examples/quick-start-python/__pycache__/app.cpython-38.pyc
  examples/quick-start-python/app.py
  examples/quick-start-python/docker-compose.yaml
  examples/quick-start-python/readme.md
  examples/quick-start-python/requirements.txt
  examples/quick-start-python/test-api.yaml
  examples/quick-start-python/tracetest/collector.config.yaml
  examples/quick-start-python/tracetest/docker-compose.yaml
  examples/quick-start-python/tracetest/tracetest.config.yaml
Labels: examples, user-request

#1984 Update docs structure and config guides
  docs/docs/configuration/connecting-to-data-stores/datadog.md
  docs/docs/configuration/connecting-to-data-stores/elasticapm.md
  docs/docs/configuration/connecting-to-data-stores/jaeger.md
  docs/docs/configuration/connecting-to-data-stores/lightstep.md
  docs/docs/configuration/connecting-to-data-stores/new-relic.md
  docs/docs/configuration/connecting-to-data-stores/opensearch.md
  docs/docs/configuration/connecting-to-data-stores/opentelemetry-collector.md
  docs/docs/configuration/connecting-to-data-stores/signalfx.md
  docs/docs/configuration/connecting-to-data-stores/tempo.md
  docs/docs/configuration/opentelemetry-collector-configuration-file-reference.md
  docs/docs/configuration/overview.md
  docs/docs/examples-tutorials/recipes.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-elasticapm.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-jaeger.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-lightstep.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-new-relic.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-opensearch.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-tempo.md
  docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store.md
  docs/docs/tools-and-integrations/k6.md
  docs/docs/tools-and-integrations/keptn.md
  docs/docs/tools-and-integrations/overview.md
  docs/docs/tools-and-integrations/testkube.md
  docs/docusaurus.config.js
  docs/sidebars.js
  examples/quick-start-tempo-nodejs/tracetest/docker-compose.yaml
  examples/quick-start-tempo-nodejs/tracetest/tracetest.config.yaml
Labels: documentation

#1978 feature(examples): adding net core x tracetest example
  examples/quick-start-net-core/Dockerfile
  examples/quick-start-net-core/README.md
  examples/quick-start-net-core/collector.config.yaml
  examples/quick-start-net-core/docker-compose.yaml
  examples/quick-start-net-core/src/.gitignore
  examples/quick-start-net-core/src/Controllers/WeatherForecastController.cs
  examples/quick-start-net-core/src/Program.cs
  examples/quick-start-net-core/src/Properties/launchSettings.json
  examples/quick-start-net-core/src/WeatherForecast.cs
  examples/quick-start-net-core/src/appsettings.Development.json
  examples/quick-start-net-core/src/appsettings.json
  examples/quick-start-net-core/src/quick-start-net-core.csproj
  examples/quick-start-net-core/tests/test.yaml
  examples/quick-start-net-core/tracetest-config.yaml
Labels: examples

#2025 fix(frontend): fix postman trigger validation
  web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/UploadCollection.tsx
  web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/UploadCollectionForm.tsx
  web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/fields/CollectionFileField.tsx
  web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/fields/SelectTestFromCollection.tsx
  web/src/services/Triggers/Postman.service.tsx
Labels: frontend

#2027 fix(frontend): fix required URL in test create form
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetails.tsx
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsUrlInput.tsx
Labels: frontend

#2041 feature(frontend): environment ux improvements
  web/src/components/EnvironmentForm/EnvironmentForm.tsx
  web/src/components/EnvironmentModal/EnvironmentModal.styled.ts
  web/src/components/EnvironmentModal/EnvironmentModal.tsx
  web/src/components/EnvironmentModal/EnvironmentModalFooter.tsx
  web/src/components/EnvironmentModal/index.ts
  web/src/components/EnvironmentSelector/AddEnvironment.tsx
  web/src/components/EnvironmentSelector/EnvironmentSelector.styled.ts
  web/src/components/EnvironmentSelector/EnvironmentSelector.tsx
  web/src/components/EnvironmentSelector/EnvironmentSelectorEntry.tsx
  web/src/components/Header/Header.tsx
  web/src/components/Layout/Layout.tsx
  web/src/pages/Environments/Environment.styled.tsx
  web/src/pages/Environments/EnvironmentCard.tsx
  web/src/pages/Environments/EnvironmentContent.tsx
  web/src/providers/Environment/Environment.provider.tsx
  web/src/providers/Environment/hooks/useEnvironmentCrud.ts
Labels: frontend

#2044 feature(frontend): updating empty state UX/UI
  web/src/components/Empty/Empty.styled.ts
  web/src/components/Empty/Empty.tsx
  web/src/components/TestSpecForm/TestSpecForm.tsx
  web/src/pages/Environments/EnvironmentList.tsx
  web/src/pages/Home/HomeFilters.tsx
  web/src/pages/Home/Resources.tsx
Labels: frontend

#2049 fix(frontend): rename create test button
  web/src/components/CreateSteps/CreateStepFooter.tsx
Labels: frontend

#2048 fix: fix tracetest config in jaeger example
  docs/docs/examples-tutorials/recipes/running-tracetest-with-jaeger.md
  examples/quick-start-jaeger-nodejs/tracetest/docker-compose.yaml
  examples/quick-start-jaeger-nodejs/tracetest/tracetest.config.yaml
Labels: documentation

#1987 feature: adding support for AWS X-RAY
  .gitignore
  api/dataStores.yaml
  cli/openapi/api_api.go
  cli/openapi/model_aws_x_ray.go
  cli/openapi/model_data_store.go
  cli/openapi/model_supported_data_stores.go
  go.work.sum
  server/app/app.go
  server/executor/runner.go
  server/executor/runner_test.go
  server/go.mod
  server/go.sum
  server/http/mappings/data_store.go
  server/id/generator.go
  server/model/data_stores.go
  server/model/spans.go
  server/model/yaml/datastore.go
  server/model/yaml/yamlconvert/datastore.go
  server/openapi/model_aws_x_ray.go
  server/openapi/model_data_store.go
  server/openapi/model_supported_data_stores.go
  server/provisioning/data_stores.go
  server/testdb/data_stores_test.go
  server/tracedb/awsxray.go
  server/tracedb/connection/trace_polling_step.go
  server/tracedb/elasticsearchdb.go
  server/tracedb/opensearchdb.go
  server/tracedb/signalfxdb.go
  server/tracedb/tracedb.go
  web/src/components/DataStoreIcon/DataStoreIcon.tsx
  web/src/components/DataStoreIcon/Icons/AwsXRay.tsx
  web/src/components/Settings/DataStorePlugin/DataStorePlugin.tsx
  web/src/components/Settings/DataStorePlugin/forms/AwsXRay/AwsXRay.tsx
  web/src/components/Settings/DataStorePlugin/forms/AwsXRay/index.ts
  web/src/constants/DataStore.constants.tsx
  web/src/models/DataStore.model.ts
  web/src/services/DataStore.service.ts
  web/src/services/DataStores/AwsXRay.service.ts
  web/src/types/Config.types.ts
  web/src/types/Generated.types.ts
Labels: frontend, backend, tracing backend

#2030 feature(examples) adding tracetest x aws-xray examples
  examples/tracetest-amazon-x-ray-adot/.env
  examples/tracetest-amazon-x-ray-adot/.gitignore
  examples/tracetest-amazon-x-ray-adot/Dockerfile
  examples/tracetest-amazon-x-ray-adot/README.md
  examples/tracetest-amazon-x-ray-adot/collector.config.yaml
  examples/tracetest-amazon-x-ray-adot/docker-compose.yml
  examples/tracetest-amazon-x-ray-adot/src/index.html
  examples/tracetest-amazon-x-ray-adot/src/index.js
  examples/tracetest-amazon-x-ray-adot/src/package-lock.json
  examples/tracetest-amazon-x-ray-adot/src/package.json
  examples/tracetest-amazon-x-ray-adot/tests/test.yaml
  examples/tracetest-amazon-x-ray-adot/tracetest-config.yaml
  examples/tracetest-amazon-x-ray-adot/tracetest.provision.yaml
  examples/tracetest-amazon-x-ray-pokeshop/.env
  examples/tracetest-amazon-x-ray-pokeshop/.gitignore
  examples/tracetest-amazon-x-ray-pokeshop/README.md
  examples/tracetest-amazon-x-ray-pokeshop/collector.config.yaml
  examples/tracetest-amazon-x-ray-pokeshop/docker-compose.yml
  examples/tracetest-amazon-x-ray-pokeshop/tests/test.yaml
  examples/tracetest-amazon-x-ray-pokeshop/tracetest.config.yaml
  examples/tracetest-amazon-x-ray-pokeshop/tracetest.provision.yaml
  examples/tracetest-amazon-x-ray/.env
  examples/tracetest-amazon-x-ray/.gitignore
  examples/tracetest-amazon-x-ray/Dockerfile
  examples/tracetest-amazon-x-ray/README.md
  examples/tracetest-amazon-x-ray/docker-compose.yml
  examples/tracetest-amazon-x-ray/src/index.html
  examples/tracetest-amazon-x-ray/src/index.js
  examples/tracetest-amazon-x-ray/src/package-lock.json
  examples/tracetest-amazon-x-ray/src/package.json
  examples/tracetest-amazon-x-ray/tests/test.yaml
  examples/tracetest-amazon-x-ray/tracetest-config.yaml
  examples/tracetest-amazon-x-ray/tracetest.provision.yaml
  go.work.sum
Labels: examples

#2051 fix(frontend): improve data store endpoint placeholder
  web/src/components/Settings/DataStorePlugin/forms/ElasticSearch/AddressesList.tsx
  web/src/components/Settings/DataStorePlugin/forms/ElasticSearch/ElasticSearch.tsx
  web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx
  web/src/components/Settings/DataStorePlugin/forms/SignalFx/SignalFx.tsx
  web/src/constants/DataStore.constants.tsx
Labels: frontend
