Repository kubeshop/tracetest, pull requests merged in 2023-12, with the labels that each got.

#3421 fix: add full height to FrameCodeBlock
  web/src/components/CodeBlock/CodeBlock.styled.ts
  web/src/components/CodeBlock/CodeBlock.tsx
  web/src/components/CodeBlock/FramedCodeBlock.tsx
  web/src/components/RunDetailAutomate/RunDetailAutomate.styled.ts
  web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.styled.ts
  web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.tsx
  web/src/components/RunDetailLayout/RunDetailLayout.styled.ts
Labels: frontend

#3422 example: add new opentelemetry filter to filter tracetest traces
  docs/docs/configuration/sampling-tracetest-spans.mdx
  examples/collector-filtering/collector.config.yaml
  examples/collector-filtering/docker-compose.yml
  examples/collector-filtering/tests/list-tests.yaml
  examples/collector-filtering/tracetest-config.yaml
  examples/collector-filtering/tracetest-provision.yaml
Labels: documentation, examples

#3426 fix: environment URL in CLI
  agent/runner/runstrategy_desktop.go
  web/src/components/Router/Router.tsx
Labels: frontend, CLI

#3429 fix(server): add context event properties
  server/app/app.go
  server/executor/assertion_runner.go
  server/executor/linter_runner.go
  server/executor/queue.go
  server/executor/trace_poller.go
  server/executor/tracepollerworker/evaluator_worker.go
  server/executor/trigger_result_processor_worker.go
  server/http/middleware/analytics.go
Labels: backend

#3439 feat: add cypress trigger type
  agent/workers/trigger/triggerer.go
  api/triggers.yaml
  server/executor/trigger/traceid.go
  server/executor/trigger/triggerer.go
  server/executor/trigger_resolver_worker.go
  server/http/mappings/tests.go
  server/test/trigger/traceid.go
  server/test/trigger/trigger.go
  server/test/trigger/trigger_json.go
  web/src/components/CreateTest/Header.tsx
  web/src/components/ResourceCard/TestCard.tsx
  web/src/components/RunDetailLayout/HeaderRight.tsx
  web/src/components/RunDetailLayout/RunDetailLayout.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponseFactory.tsx
  web/src/components/TestHeader/TestHeader.tsx
  web/src/components/TestPlugins/EntryPointFactory.tsx
  web/src/components/TestPlugins/FormFactory.tsx
  web/src/components/TriggerTypeModal/TriggerTypeModal.tsx
  web/src/constants/Common.constants.ts
  web/src/constants/Demo.constants.ts
  web/src/constants/Plugins.constants.ts
  web/src/constants/Test.constants.ts
  web/src/models/Test.model.ts
  web/src/models/Trigger.model.ts
  web/src/models/TriggerResult.model.ts
  web/src/pages/Test/Content.tsx
  web/src/services/Test.service.ts
  web/src/services/Triggers/Cypress.service.ts
  web/src/types/Generated.types.ts
  web/src/types/Plugins.types.ts
  web/src/types/Test.types.ts
Labels: frontend, backend

#3442 feat(frontend): improve cypress trigger and automate tabs
  web/src/components/ResourceCard/TestCard.tsx
  web/src/components/RunDetailAutomate/RunDetailAutomate.tsx
  web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.tsx
  web/src/components/RunDetailAutomateMethods/RunDetailAutomateMethods.tsx
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/CliCommand.tsx
  web/src/components/RunDetailAutomateMethods/methods/Cypress/Cypress.styled.ts
  web/src/components/RunDetailAutomateMethods/methods/Cypress/Cypress.tsx
  web/src/components/RunDetailAutomateMethods/methods/Cypress/index.ts
  web/src/components/RunDetailAutomateMethods/methods/DeepLink/DeepLink.tsx
  web/src/components/RunDetailLayout/HeaderLeft.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerData.tsx
  web/src/constants/Automate.constants.ts
Labels: frontend

#3452 chore: Tracetest Cloud x K6 example
  examples/tracetest-cloud-k6/.env.template
  examples/tracetest-cloud-k6/.gitignore
  examples/tracetest-cloud-k6/README.md
  examples/tracetest-cloud-k6/assets/assertions.gif
  examples/tracetest-cloud-k6/collector.config.yaml
  examples/tracetest-cloud-k6/docker-compose.yml
  examples/tracetest-cloud-k6/import-pokemon.js
  examples/tracetest-cloud-k6/tests/test.yaml
  examples/tracetest-cloud-k6/tracetest-config.yaml
  examples/tracetest-cloud-k6/tracetest-provision.yaml
Labels: examples

#3455 feat(frontend): add additional test events
  web/src/components/AnalyzerErrorsPopover/AnalyzerErrorsPopover.tsx
  web/src/components/AnalyzerResult/Plugins.tsx
  web/src/components/AnalyzerResult/Rule.tsx
  web/src/components/AnalyzerResult/RuleLink.tsx
  web/src/components/Collapse/Collapse.tsx
  web/src/components/CreateModal/CreateSteps/CreateStepFooter.tsx
  web/src/components/CreateTest/CreateTest.tsx
  web/src/components/CreateTest/Header.tsx
  web/src/components/DemoSelector/DemoSelector.tsx
  web/src/components/ImportModal/ImportModal.tsx
  web/src/components/TriggerTypeModal/TriggerTypeModal.tsx
  web/src/components/Visualization/components/DAG/TraceSpanNode/AnalyzerErrors.tsx
  web/src/constants/Analytics.constants.ts
  web/src/pages/TestSuites/TestSuites.tsx
  web/src/services/Analytics/Analytics.service.ts
  web/src/services/Analytics/CreateTest.service.ts
  web/src/services/Analytics/CreateTestAnalytics.service.ts
  web/src/services/Analytics/CreateTestSuite.service.ts
  web/src/services/Analytics/TraceAnalyzer.service.ts
  web/src/services/Analytics/__tests__/CreateTestAnalytics.service.test.ts
Labels: frontend

#3468 feat(frontend): add otel tracing backend improvements
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/Configuration.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/Ingestor.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.styled.ts
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.tsx
  web/src/models/DataStore.model.ts
  web/src/services/DataStores/AzureAppInsights.service.ts
  web/src/services/DataStores/OtelCollector.service.ts
Labels: frontend

#3475 fix(frontend): fix tracing backend selected tab
  web/src/components/Inputs/DataStoreSelection/DataStoreSelection.tsx
Labels: frontend
