Repository kubeshop/tracetest, pull requests merged in 2023-06, with the labels that each got.

#2641 fix(backend): fixing analyzer runner return logic
  server/executor/linter_runner.go
Labels: backend

#2642 feature(frontend): Adding Analyzer empty state
  web/src/components/AnalyzerResult/AnalyzerResult.styled.ts
  web/src/components/AnalyzerResult/AnalyzerResult.tsx
  web/src/components/AnalyzerResult/CollapseIcon.tsx
  web/src/components/AnalyzerResult/Empty.tsx
  web/src/components/AnalyzerResult/Plugins.tsx
  web/src/components/AnalyzerResult/index.ts
  web/src/components/RunDetailTrace/LintResults.tsx
  web/src/components/RunDetailTrace/RunDetailTrace.tsx
Labels: frontend

#2648 fix(frontend): fix analyzer description
  web/src/components/AnalyzerResult/AnalyzerResult.tsx
  web/src/components/Settings/Linter/Linter.tsx
Labels: frontend

#2651 fix(cli): adding skip of version mismatch for the server install cmd
  cli/cmd/config.go
  cli/cmd/server_cmd.go
  cli/cmd/server_install_cmd.go
Labels: CLI

#2674 fix(frontend): fix analyzer results in trace DAG
  web/cypress/e2e/TestRunDetail/Outputs.spec.ts
  web/cypress/e2e/TestRunDetail/TestRunDetail.spec.ts
  web/src/components/Drawer/Drawer.tsx
  web/src/components/RunDetailTrace/RunDetailTrace.styled.ts
  web/src/components/RunDetailTrace/Visualization.tsx
  web/src/components/Visualization/components/DAG/AnalyzerResults.styled.ts
  web/src/components/Visualization/components/DAG/AnalyzerResults.tsx
  web/src/components/Visualization/components/DAG/SpanNode.styled.ts
  web/src/components/Visualization/components/DAG/SpanNode.tsx
  web/src/hooks/__tests__/useElementSize.test.tsx
  web/src/hooks/useElementSize.tsx
  web/src/hooks/useOnClickOutside.tsx
  web/src/redux/slices/Trace.slice.ts
  web/src/selectors/Trace.selectors.ts
  web/src/services/Span.service.ts
Labels: frontend

#2691 feature: Azure Application Insights Integration
  api/dataStores.yaml
  cli/openapi/model_azure_app_insights.go
  cli/openapi/model_data_store.go
  cli/openapi/model_supported_connection_types.go
  cli/openapi/model_supported_data_stores.go
  go.work.sum
  server/go.mod
  server/go.sum
  server/http/mappings/datastore.go
  server/openapi/model_azure_app_insights.go
  server/openapi/model_data_store.go
  server/openapi/model_supported_connection_types.go
  server/openapi/model_supported_data_stores.go
  server/tracedb/awsxray.go
  server/tracedb/azureappinsights.go
  server/tracedb/datastoreresource/resource_types.go
  server/tracedb/tracedb.go
  web/src/components/DataStoreIcon/DataStoreIcon.tsx
  web/src/components/DataStoreIcon/Icons/AzureAppInsights.tsx
  web/src/components/Settings/DataStorePlugin/DataStorePlugin.tsx
  web/src/components/Settings/DataStorePlugin/forms/AzureAppInsights/AzureAppInsights.tsx
  web/src/components/Settings/DataStorePlugin/forms/AzureAppInsights/index.ts
  web/src/constants/CollectorConfig.constants.ts
  web/src/constants/DataStore.constants.tsx
  web/src/models/DataStore.model.ts
  web/src/providers/DataStore/DataStore.provider.tsx
  web/src/providers/DataStore/hooks/useDataStoreNotification.tsx
  web/src/services/DataStore.service.ts
  web/src/services/DataStores/AwsXRay.service.ts
  web/src/services/DataStores/AzureAppInsights.service.ts
  web/src/services/DataStores/BaseClient.service.ts
  web/src/services/DataStores/ElasticSearch.service.ts
  web/src/services/DataStores/Jaeger.service.ts
  web/src/services/DataStores/OtelCollector.service.ts
  web/src/services/DataStores/SignalFx.service.ts
  web/src/types/DataStore.types.ts
  web/src/types/Generated.types.ts
Labels: tracing backend

#2690 fix(frontend): add no matches message in trace search
  web/src/components/RunDetailTrace/RunDetailTrace.styled.ts
  web/src/components/RunDetailTrace/Search.tsx
Labels: frontend

#2689 feat(frontend): update help menu
  web/src/assets/discord.svg
  web/src/components/Header/Header.styled.tsx
  web/src/components/Header/Header.tsx
  web/src/components/Header/HelpMenu.tsx
  web/src/components/Header/Menu.tsx
Labels: frontend

#2684 feat(server): add analytics middleware
  cli/analytics/analytics.go
  cli/utils/api.go
  server/app/app.go
  server/http/custom_routes.go
  server/resourcemanager/resource_manager.go
  web/src/redux/apis/TraceTest.api.ts
Labels: backend

#2699 feature(frontend): enabling first attribute check deletion
  web/src/components/TestSpecForm/AssertionCheck.tsx
Labels: frontend

#2698 fix(frontend): fixing select spans visual bug
  web/src/components/CurrentSpanSelector/CurrentSpanSelector.styled.ts
  web/src/components/CurrentSpanSelector/CurrentSpanSelector.tsx
Labels: frontend

#2696 fix(frontend): fix missing dep in useEffect in TestSpec form
  web/src/components/TestSpecForm/TestSpecForm.tsx
Labels: frontend

#2700 feature(frontend): adding auto scroll to assertion result
  web/src/components/TestSpecDetail/Content.tsx
  web/src/hooks/useScrollTo.ts
Labels: frontend

#2703 feat(frontend): support specs and outputs creation from trigger response
  web/cypress/e2e/TestRunDetail/Outputs.spec.ts
  web/src/components/AttributeActions/AttributeActions.styled.tsx
  web/src/components/AttributeActions/AttributeActions.tsx
  web/src/components/AttributeActions/index.ts
  web/src/components/AttributeRow/AttributeRow.tsx
  web/src/components/HeaderRow/HeaderRow.tsx
  web/src/components/RunDetailTrigger/RunDetailTrigger.tsx
  web/src/components/RunDetailTriggerResponse/ResponseBody.tsx
  web/src/components/RunDetailTriggerResponse/ResponseHeaders.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.styled.ts
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponseFactory.tsx
Labels: frontend

#2708 fix(frontend): fix onboarding for test specs step
  web/src/components/TestResults/AddTestSpecButton.tsx
Labels: frontend

#2704 fix(backend): adding empty port as supported for tempo
  server/tracedb/datasource/http.go
  server/tracedb/tempodb.go
Labels: backend

#2706 fix(frontend): add AttributeActions icon to status and duration fields
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.styled.ts
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx
Labels: frontend

#2710 fix(frontend): fix test spec expression for header field
  web/src/components/HeaderRow/HeaderRow.tsx
  web/src/components/RunDetailTriggerResponse/ResponseHeaders.tsx
Labels: frontend

#2715 feature(frontend): adding enable switch for ingestor for Otel DataStores
  web/src/components/AnalyzerResult/AnalyzerResult.styled.ts
  web/src/components/DocsBanner/DocsBanner.styled.ts
  web/src/components/DocsBanner/DocsBanner.tsx
  web/src/components/DocsBanner/index.ts
  web/src/components/Settings/DataStoreDocsBanner/DataStoreDocsBanner.tsx
  web/src/components/Settings/DataStoreForm/DataStoreForm.styled.ts
  web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
  web/src/components/Settings/DataStorePlugin/forms/AwsXRay/AwsXRay.tsx
  web/src/components/Settings/DataStorePlugin/forms/AzureAppInsights/AzureAppInsights.tsx
  web/src/components/Settings/DataStorePlugin/forms/BaseClient/BaseClient.tsx
  web/src/components/Settings/DataStorePlugin/forms/ElasticSearch/ElasticSearch.tsx
  web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx
  web/src/components/Settings/DataStorePlugin/forms/HttpClient/HttpClient.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/Configuration.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/Ingestor.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.styled.ts
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.tsx
  web/src/components/Settings/DataStorePlugin/forms/SignalFx/SignalFx.tsx
  web/src/constants/Common.constants.ts
  web/src/constants/DataStore.constants.tsx
  web/src/models/DataStore.model.ts
  web/src/services/DataStore.service.ts
  web/src/services/DataStores/AzureAppInsights.service.ts
  web/src/services/DataStores/OtelCollector.service.ts
  web/src/types/DataStore.types.ts
Labels: frontend

#2731 feat(frontend): add errors filter and minor fixes for Analyzer results
  web/src/components/AnalyzerResult/AnalyzerResult.styled.ts
  web/src/components/AnalyzerResult/AnalyzerResult.tsx
  web/src/components/AnalyzerResult/CollapseIcon.tsx
  web/src/components/AnalyzerResult/GlobalResult.tsx
  web/src/components/AnalyzerResult/Plugins.tsx
  web/src/components/AnalyzerScore/AnalyzerScore.styled.ts
  web/src/components/AnalyzerScore/AnalyzerScore.tsx
  web/src/components/AnalyzerScore/Percentage.tsx
  web/src/components/AnalyzerScore/index.ts
  web/src/components/LintScore/LintScore.tsx
  web/src/components/LintScore/PercentageScore.tsx
  web/src/components/TestSpecForm/AssertionCheck.tsx
  web/src/components/TestSpecForm/AssertionCheckList.tsx
  web/src/components/TooltipQuestion/TooltipQuestion.tsx
  web/src/constants/Common.constants.ts
  web/src/services/Analyzer.service.ts
Labels: frontend

#2726 feature(CLI): Analyzer Resource Integration
  cli/actions/analyzer.go
  cli/cmd/config.go
  cli/formatters/analyzer.go
  cli/parameters/resources.go
  server/model/yaml/file.go
  testing/cli-e2etest/testscenarios/analyzer/apply_analyzer_test.go
  testing/cli-e2etest/testscenarios/analyzer/delete_analyzer_test.go
  testing/cli-e2etest/testscenarios/analyzer/get_analyzer_test.go
  testing/cli-e2etest/testscenarios/analyzer/list_analyzer_test.go
  testing/cli-e2etest/testscenarios/analyzer/resources/new-analyzer.yaml
  testing/cli-e2etest/testscenarios/demo/resources/another-demo.yaml
  testing/cli-e2etest/testscenarios/demo/resources/new-demo.yaml
  testing/cli-e2etest/testscenarios/demo/resources/updated-new-demo.yaml
  testing/cli-e2etest/testscenarios/environment/resources/another-environment.yaml
  testing/cli-e2etest/testscenarios/environment/resources/new-environment.yaml
  testing/cli-e2etest/testscenarios/environment/resources/one-more-environment.yaml
  testing/cli-e2etest/testscenarios/environment/resources/updated-new-environment.yaml
  testing/cli-e2etest/testscenarios/test/resources/environment-file.yaml
  testing/cli-e2etest/testscenarios/types/types.go
Labels: CLI

#2716 fix(cli): remove cli analytics
  .github/workflows/pull-request.yaml
  cli/actions/configure_action.go
  cli/analytics/analytics.go
  cli/cmd/apply_cmd.go
  cli/cmd/config.go
  cli/cmd/configure_cmd.go
  cli/cmd/dashboard_cmd.go
  cli/cmd/delete_cmd.go
  cli/cmd/export_cmd.go
  cli/cmd/get_cmd.go
  cli/cmd/list_cmd.go
  cli/cmd/server_install_cmd.go
  cli/cmd/test_export_cmd.go
  cli/cmd/test_list_cmd.go
  cli/cmd/test_run_cmd.go
  cli/cmd/version_cmd.go
  cli/config/config.go
  cli/installer/docker_compose.go
  cli/installer/installer.go
  cli/installer/kubernetes.go
  cli/parameters/configure.go
  docs/docs/ci-cd-automation/tekton-pipeline.md
  docs/docs/cli/configuring-your-cli.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-datadog.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-honeycomb.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-lightstep.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-new-relic.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-tekton.md
  docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store-with-manual-instrumentation.md
  examples/quick-start-tekton/install-and-run-tracetest.yaml
  examples/tracetest-lightstep-otel-demo/README.md
  examples/tracetest-new-relic-otel-demo/README.md
  examples/tracetest-synthetic-monitoring/.github/workflows/synthetic-monitoring.yaml
Labels: CLI

#2738 fix: Fixing Analyzer Rules and Updating Values
  server/linter/plugins/common/rules/enforce_dns.go
  server/linter/plugins/security/rules/enforce_secure_protocol.go
  server/linter/plugins/security/rules/ensures_no_api_key_leak.go
  server/linter/plugins/standards/rules/ensure_span_naming_rule.go
  server/linter/plugins/standards/rules/required_attributes.go
  web/src/assets/pokeshop.proto.json
Labels: backend

#2742 fix(frontend): adding default value for data store connection types
  web/src/components/Settings/DataStorePlugin/forms/AzureAppInsights/AzureAppInsights.tsx
  web/src/components/Settings/DataStorePlugin/forms/BaseClient/BaseClient.tsx
Labels: frontend

#2735 feat(frontend): add analyzer score summary
  api/tests.yaml
  cli/openapi/model_test_summary_last_run.go
  server/http/mappings/tests.go
  server/model/tests.go
  server/openapi/model_test_summary_last_run.go
  server/testdb/tests.go
  server/tests/transactions_test.go
  web/src/components/ResourceCard/ResourceCard.styled.ts
  web/src/components/ResourceCard/ResourceCardSummary.tsx
  web/src/components/ResourceCard/TestCard.tsx
  web/src/components/RunCard/RunCard.styled.ts
  web/src/components/RunCard/TestRunCard.tsx
  web/src/models/Summary.model.ts
  web/src/types/Generated.types.ts
Labels: frontend, backend

#2753 feature(frontend): Adding Automate Tab Skeleton
  web/src/components/Header/Header.styled.tsx
  web/src/components/RunDetailAutomate/RunDetailAutomate.styled.ts
  web/src/components/RunDetailAutomate/RunDetailAutomate.tsx
  web/src/components/RunDetailAutomate/index.ts
  web/src/components/RunDetailLayout/RunDetailLayout.styled.ts
  web/src/components/RunDetailLayout/RunDetailLayout.tsx
  web/src/constants/TestRun.constants.ts
Labels: frontend

#2763 feature(frontend): Automate Tab - Test Definition
  web/src/components/FileViewerModal/FileViewerModal.provider.tsx
  web/src/components/RunActionsMenu/RunActionsMenu.tsx
  web/src/components/RunCard/TestRunCard.tsx
  web/src/components/RunDetailAutomate/RunDetailAutomate.tsx
  web/src/components/RunDetailLayout/HeaderRight.tsx
  web/src/components/RunDetailLayout/RunDetailLayout.tsx
  web/src/components/TestDefinition/TestDefinition.styled.ts
  web/src/components/TestDefinition/TestDefinition.tsx
  web/src/components/TestDefinition/index.ts
  web/src/components/TransactionRunActionsMenu/TransactionRunActionsMenu.tsx
  web/src/hooks/useDefinitionFile.ts
  web/src/hooks/useJUnitResult.ts
  web/src/pages/Environments/EnvironmentCard.tsx
Labels: frontend

#2743 feat: improve analyzer errors
  api/linters.yaml
  cli/openapi/model_linter_result_plugin_rule.go
  cli/openapi/model_linter_result_plugin_rule_result.go
  cli/openapi/model_linter_result_plugin_rule_result_error.go
  server/http/mappings/linter.go
  server/linter/plugins/common/rules/enforce_dns.go
  server/linter/plugins/security/rules/enforce_secure_protocol.go
  server/linter/plugins/security/rules/ensures_no_api_key_leak.go
  server/linter/plugins/standards/rules/ensure_attribute_naming_rule.go
  server/linter/plugins/standards/rules/ensure_attribute_naming_rule_test.go
  server/linter/plugins/standards/rules/ensure_span_naming_rule.go
  server/linter/plugins/standards/rules/not_empty_attribute_rule.go
  server/linter/plugins/standards/rules/not_empty_attribute_rule_test.go
  server/linter/plugins/standards/rules/required_attribute_rule.go
  server/linter/plugins/standards/rules/required_attributes.go
  server/model/linter.go
  server/openapi/model_linter_result_plugin_rule.go
  server/openapi/model_linter_result_plugin_rule_result.go
  server/openapi/model_linter_result_plugin_rule_result_error.go
  web/src/components/AnalyzerResult/AnalyzerResult.styled.ts
  web/src/components/AnalyzerResult/Plugins.tsx
  web/src/components/Visualization/components/DAG/AnalyzerResults.styled.ts
  web/src/components/Visualization/components/DAG/AnalyzerResults.tsx
  web/src/models/LinterResult.model.ts
  web/src/providers/TestRun/TestRun.provider.tsx
  web/src/services/Span.service.ts
  web/src/types/Generated.types.ts
Labels: frontend, backend

#2791 feature(frontend): Automate Tab - Deep Link Technique
  web/package.json
  web/src/components/CodeBlock/CodeBlock.styled.ts
  web/src/components/CodeBlock/CodeBlock.tsx
  web/src/components/CodeBlock/FramedCodeBlock.tsx
  web/src/components/CodeBlock/index.ts
  web/src/components/FileViewerModal/FileViewerModal.styled.ts
  web/src/components/FileViewerModal/FileViewerModal.tsx
  web/src/components/RunDetailAutomate/RunDetailAutomate.tsx
  web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.styled.ts
  web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.tsx
  web/src/components/RunDetailAutomateMethods/RunDetailAutomateMethods.tsx
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/CliCommand.tsx
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/Controls.tsx
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/SwitchControl.tsx
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/hooks/useCliCommand.ts
  web/src/components/RunDetailAutomateMethods/methods/DeepLink/Controls.tsx
  web/src/components/RunDetailAutomateMethods/methods/DeepLink/DeepLink.styled.ts
  web/src/components/RunDetailAutomateMethods/methods/DeepLink/DeepLink.tsx
  web/src/components/RunDetailAutomateMethods/methods/DeepLink/Variables.tsx
  web/src/components/RunDetailAutomateMethods/methods/DeepLink/hooks/useDeepLink.ts
  web/src/components/RunDetailAutomateMethods/methods/DeepLink/index.ts
  web/src/components/RunDetailLayout/RunDetailLayout.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/Configuration.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.styled.ts
  web/src/components/TestDefinition/TestDefinition.styled.ts
  web/src/components/TestDefinition/TestDefinition.tsx
  web/src/pages/AutomatedTestRun/Content.tsx
  web/src/services/CliCommand.service.ts
  web/src/services/DeepLink.service.ts
  web/src/utils/Common.ts
Labels: frontend

#2801 2767 automate tab include deeplink technique update
  web/src/components/CodeBlock/CodeBlock.styled.ts
  web/src/components/CodeBlock/FramedCodeBlock.tsx
  web/src/components/Router/Router.tsx
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/Controls.tsx
  web/src/components/RunDetailAutomateMethods/methods/DeepLink/Controls.tsx
  web/src/components/RunDetailAutomateMethods/methods/DeepLink/DeepLink.styled.ts
  web/src/components/RunDetailAutomateMethods/methods/DeepLink/DeepLink.tsx
  web/src/components/WithAnalytics/WithAnalytics.tsx
  web/src/pages/AutomatedTestRun/AutomatedTestRun.tsx
  web/src/providers/Test/Test.provider.tsx
  web/src/services/DeepLink.service.ts
Labels: frontend

#2820 chore(docs): Adding App Insights Configuration Page
  docs/docs/configuration/connecting-to-data-stores/azure-app-insights.md
  docs/docs/configuration/img/appinsights-direct.png
  docs/docs/configuration/img/appinsights-otel.png
  docs/docs/configuration/opentelemetry-collector-configuration-file-reference.md
  docs/docs/configuration/overview.md
  docs/sidebars.js
  web/src/constants/CollectorConfig.constants.ts
Labels: documentation

#2827 fix(frontend): Fixing Resizable Panels UI bugs
  web/src/components/ResizablePanels/FillPanel.tsx
  web/src/components/ResizablePanels/LeftPanel.tsx
  web/src/components/ResizablePanels/ResizablePanels.styled.ts
  web/src/components/ResizablePanels/ResizablePanels.tsx
  web/src/components/ResizablePanels/RightPanel.tsx
  web/src/components/ResizablePanels/hooks/useResizablePanel.ts
  web/src/components/ResizablePanels/hooks/useResizablePanels.ts
  web/src/components/ResizablePanels/index.ts
  web/src/components/RunDetailTest/RunDetailTest.tsx
  web/src/components/RunDetailTest/SpanDetailPanel.tsx
  web/src/components/RunDetailTest/SpanDetailsPanel.tsx
  web/src/components/RunDetailTest/TestPanel.tsx
  web/src/components/RunDetailTrace/AnalyzerPanel.tsx
  web/src/components/RunDetailTrace/RunDetailTrace.styled.ts
  web/src/components/RunDetailTrace/RunDetailTrace.tsx
  web/src/components/RunDetailTrace/SpanDetailsPanel.tsx
  web/src/components/RunDetailTrace/TracePanel.tsx
  web/src/components/Visualization/components/DAG/AnalyzerResults.styled.ts
Labels: frontend

#2826 fix(tests): add analyzer resource to cli e2e table
  testing/cli-e2etest/README.md
Labels: CLI

#2821 chore(docs): Azure App Insights Recipes
  docs/docs/configuration/connecting-to-data-stores/azure-app-insights.md
  docs/docs/examples-tutorials/recipes.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-azure-app-insights-collector.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-azure-app-insights-pokeshop.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-azure-app-insights.md
  docs/sidebars.js
  examples/tracetest-azure-app-insights-collector/README.md
  examples/tracetest-azure-app-insights-pokeshop/README.md
Labels: documentation

#2830 chore(frotend): Test Definition Name Input
  web/src/components/InputOverlay/InputOverlay.styled.ts
  web/src/components/InputOverlay/InputOverlay.tsx
  web/src/components/InputOverlay/index.ts
  web/src/components/RunDetailAutomate/RunDetailAutomate.tsx
  web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.styled.ts
  web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.tsx
  web/src/components/RunDetailAutomateMethods/RunDetailAutomateMethods.tsx
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/CliCommand.tsx
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/Controls.tsx
  web/src/services/CliCommand.service.ts
Labels: frontend

#2828 chore(frotend): Updating Panel Splitter w/ Tooltip
  web/src/components/ResizablePanels/LeftPanel.tsx
  web/src/components/ResizablePanels/ResizablePanels.styled.ts
  web/src/components/ResizablePanels/RightPanel.tsx
  web/src/components/ResizablePanels/Splitter.tsx
  web/src/components/RunDetailTest/SpanDetailsPanel.tsx
  web/src/components/RunDetailTrace/SpanDetailsPanel.tsx
  web/src/constants/Theme.constants.ts
  web/src/styled.d.ts
Labels: frontend

#2833 fix(frontend): fix missing font-face
  web/public/SF-Pro-Text-Bold.otf
  web/public/SF-Pro-Text-Semibold.otf
  web/src/App.less
  web/src/components/DocsBanner/DocsBanner.styled.ts
  web/src/components/EditTest/EditTest.styled.ts
  web/src/components/EditTransaction/EditTransaction.styled.ts
  web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.styled.ts
  web/src/components/RunDetailAutomateMethods/RunDetailAutomateMethods.styled.ts
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.styled.ts
  web/src/components/RunEvents/RunEvents.styled.ts
  web/src/components/Settings/DataStore/DataStore.styled.ts
  web/src/components/Settings/DataStoreForm/DataStoreForm.styled.ts
  web/src/components/Settings/DataStorePlugin/DataStorePluginForm.styled.ts
  web/src/components/TestSpecForm/Fields/AttributeField.styled.tsx
  web/src/components/TestSpecForm/Fields/AttributeField.tsx
  web/src/components/TestSpecForm/Fields/useDropDownRenderComponent.tsx
  web/src/components/TransactionRunResult/TransactionRunResult.styled.ts
  web/src/pages/Environments/Environment.styled.tsx
  web/src/pages/Environments/EnvironmentCard.tsx
Labels: frontend

#2815 feat(frontend): add independent trace vs test data
  web/src/components/AssertionResultChecks/AssertionResultChecks.tsx
  web/src/components/AssertionResultChecks/ResultCheck.tsx
  web/src/components/AssertionResultChecks/index.ts
  web/src/components/AttributeList/AttributeList.tsx
  web/src/components/AttributeList/__tests__/AttributeList.test.tsx
  web/src/components/AttributeRow/AttributeRow.tsx
  web/src/components/AttributeRow/__tests__/AttributeRow.test.tsx
  web/src/components/SpanDetail/Attributes.tsx
  web/src/components/SpanDetail/Header.tsx
  web/src/components/SpanDetail/SpanDetail.tsx
  web/src/components/TestSpecDetail/SpanHeader.tsx
  web/src/components/Visualization/components/DAG/BaseSpanNode/BaseSpanNode.styled.ts
  web/src/components/Visualization/components/DAG/BaseSpanNode/BaseSpanNode.tsx
  web/src/components/Visualization/components/DAG/DAG.styled.tsx
  web/src/components/Visualization/components/DAG/DAG.tsx
  web/src/components/Visualization/components/DAG/SpanNode.tsx
  web/src/components/Visualization/components/DAG/TestSpanNode/Footer.tsx
  web/src/components/Visualization/components/DAG/TestSpanNode/TestSpanNode.tsx
  web/src/components/Visualization/components/DAG/TraceSpanNode/AnalyzerErrors.styled.ts
  web/src/components/Visualization/components/DAG/TraceSpanNode/AnalyzerErrors.tsx
  web/src/components/Visualization/components/DAG/TraceSpanNode/AnalyzerErrorsPopover.tsx
  web/src/components/Visualization/components/DAG/TraceSpanNode/TraceSpanNode.tsx
  web/src/components/Visualization/components/Timeline/SpanNode.tsx
  web/src/components/Visualization/components/Timeline/Visualization.tsx
  web/src/constants/DAG.constants.ts
  web/src/hooks/useSpanData.ts
  web/src/models/DAG.model.ts
  web/src/models/LinterResult.model.ts
  web/src/providers/TestRun/TestRun.provider.tsx
  web/src/redux/slices/DAG.slice.ts
  web/src/redux/slices/Trace.slice.ts
  web/src/redux/testOutputs/selectors.ts
  web/src/selectors/TestRun.selectors.ts
  web/src/selectors/TestSpecs.selectors.ts
  web/src/selectors/Trace.selectors.ts
  web/src/selectors/__tests__/TestSpecs.selectors.test.ts
  web/src/services/Span.service.ts
  web/src/services/SpanAttribute.service.ts
  web/src/services/TestRun.service.ts
  web/src/types/Assertion.types.ts
  web/src/types/DAG.types.ts
  web/src/types/Span.types.ts
  web/src/types/TestRun.types.ts
Labels: frontend

#2835 feature(frontend): Contact Us Modal
  web/src/assets/plushie.svg
  web/src/components/ContactUs/ContactUs.styled.ts
  web/src/components/ContactUs/ContactUs.tsx
  web/src/components/ContactUs/ContactUsModal.tsx
  web/src/components/ContactUs/ContactUsModalFooter.tsx
  web/src/components/ContactUs/index.ts
  web/src/components/PulseButton/PulseButton.styled.ts
  web/src/components/PulseButton/index.ts
  web/src/pages/Settings/Settings.tsx
  web/src/providers/DataStore/DataStore.provider.tsx
Labels: frontend

#2837 feat(frontend): trace vs test data for timeline and attribute list
  web/src/assets/error.svg
  web/src/components/AttributeList/AttributeList.tsx
  web/src/components/AttributeList/__tests__/AttributeList.test.tsx
  web/src/components/AttributeRow/index.ts
  web/src/components/ResizablePanels/Splitter.tsx
  web/src/components/RunDetailTest/SpanDetailsPanel.tsx
  web/src/components/RunDetailTest/Visualization.tsx
  web/src/components/RunDetailTrace/AnalyzerPanel.tsx
  web/src/components/RunDetailTrace/SpanDetailsPanel.tsx
  web/src/components/RunDetailTrace/Visualization.tsx
  web/src/components/SpanDetail/Attributes.tsx
  web/src/components/SpanDetail/BaseAttributeRow/AttributeTitle.tsx
  web/src/components/SpanDetail/BaseAttributeRow/BaseAttributeRow.styled.ts
  web/src/components/SpanDetail/BaseAttributeRow/BaseAttributeRow.tsx
  web/src/components/SpanDetail/BaseAttributeRow/__tests__/AttributeRow.test.tsx
  web/src/components/SpanDetail/Header.tsx
  web/src/components/SpanDetail/SpanDetail.styled.ts
  web/src/components/SpanDetail/SpanDetail.tsx
  web/src/components/SpanDetail/TestAttributeRow/TestAttributeRow.styled.ts
  web/src/components/SpanDetail/TestAttributeRow/TestAttributeRow.tsx
  web/src/components/SpanDetail/TestSubHeader/TestSubHeader.styled.ts
  web/src/components/SpanDetail/TestSubHeader/TestSubHeader.tsx
  web/src/components/SpanDetail/TraceAttributeRow/TraceAttributeRow.styled.ts
  web/src/components/SpanDetail/TraceAttributeRow/TraceAttributeRow.tsx
  web/src/components/SpanDetail/TraceSubHeader/TraceSubHeader.styled.ts
  web/src/components/SpanDetail/TraceSubHeader/TraceSubHeader.tsx
  web/src/components/SpanDetail/index.ts
  web/src/components/TestOutput/TestOutput.tsx
  web/src/components/TestOutputForm/TestOutputForm.tsx
  web/src/components/TestOutputMark/TestOutputMark.styled.ts
  web/src/components/TestOutputMark/TestOutputMark.tsx
  web/src/components/Visualization/components/DAG/TestSpanNode/TestSpanNode.tsx
  web/src/components/Visualization/components/Timeline/BaseSpanNode/BaseSpanNode.tsx
  web/src/components/Visualization/components/Timeline/BaseSpanNode/Collapse.tsx
  web/src/components/Visualization/components/Timeline/BaseSpanNode/Connector.tsx
  web/src/components/Visualization/components/Timeline/BaseSpanNode/Label.tsx
  web/src/components/Visualization/components/Timeline/Label.tsx
  web/src/components/Visualization/components/Timeline/SpanNodeFactory.tsx
  web/src/components/Visualization/components/Timeline/TestSpanNode/Header.tsx
  web/src/components/Visualization/components/Timeline/TestSpanNode/TestSpanNode.tsx
  web/src/components/Visualization/components/Timeline/Timeline.styled.ts
  web/src/components/Visualization/components/Timeline/Timeline.tsx
  web/src/components/Visualization/components/Timeline/TraceSpanNode/Header.tsx
  web/src/components/Visualization/components/Timeline/TraceSpanNode/TraceSpanNode.tsx
  web/src/components/Visualization/components/Timeline/Visualization.tsx
  web/src/components/Visualization/hooks/useShowSelectAsCurrent.ts
  web/src/constants/DAG.constants.ts
  web/src/constants/Visualization.constants.ts
  web/src/models/DAG.model.ts
  web/src/models/Timeline.model.ts
  web/src/redux/slices/DAG.slice.ts
  web/src/redux/slices/Trace.slice.ts
  web/src/redux/testOutputs/selectors.ts
  web/src/services/SpanAttribute.service.ts
  web/src/services/Timeline.service.ts
  web/src/services/__tests__/DAG.service.test.ts
  web/src/types/DAG.types.ts
  web/src/types/Timeline.types.ts
Labels: frontend
