Repository kubeshop/tracetest, pull requests merged in 2023-05, with the labels that each got.

#2461 fix(frontend): fix test specs snippets
  web/src/components/TestResults/AddTestSpecButton.tsx
  web/src/components/TestResults/Header.tsx
  web/src/components/TestSpecs/Empty.tsx
  web/src/components/TestSpecs/TestSpecs.styled.ts
  web/src/constants/Common.constants.ts
  web/src/pages/Home/Resources.tsx
Labels: frontend

#2442 fix(frontend): fix test spec name on edit mode
  web/src/components/TestSpecForm/TestSpecForm.provider.tsx
Labels: frontend

#2463 fix(frontend): fix test creation with curl command
  web/src/components/CreateTestPlugins/Curl/steps/ImportCommand/ImportCommand.tsx
  web/src/components/CreateTestPlugins/Curl/steps/ImportCommand/ImportCommandForm.tsx
  web/src/components/Editor/CurlCommand/CurlCommand.tsx
  web/src/services/Triggers/Curl.service.ts
Labels: frontend

#2466 fix(docs): fix connecting to datastores docs
  docs/docs/configuration/connecting-to-data-stores/lightstep.md
  docs/docs/configuration/connecting-to-data-stores/new-relic.md
  docs/docs/configuration/connecting-to-data-stores/opensearch.md
  docs/docs/configuration/connecting-to-data-stores/signalfx.md
Labels: documentation

#2476 chore(docs): updating docs to match environment changes
  docs/docs/cli/running-tests.md
  docs/docs/concepts/environments.md
  docs/docs/concepts/transactions.md
Labels: documentation

#2480 feature(backend): Enabling environment upsert endpoint when creating
  server/environment/manager.go
Labels: CLI

#2482 fix(frontend): update honeycomb notification
  web/src/constants/DataStore.constants.tsx
Labels: frontend

#2485 fix(installer): updating grpc host when installing the docker version with pokeshop
  cli/installer/tracetest.go
Labels: backend

#2489 fix(frontend): add polling mechanism for test run
  web/src/providers/TestRun/TestRun.provider.tsx
Labels: frontend

#2490 feature(cli): Adding dashboard command
  cli/cmd/dashboard_cmd.go
  cli/utils/common.go
Labels: CLI

#2496 fix(cli): fixing nested structs output format
  cli/formatters/config.go
  cli/formatters/datastore.go
  cli/formatters/demo.go
  cli/formatters/environment.go
  cli/formatters/polling.go
  cli/utils/api.go
  go.work.sum
Labels: CLI

#2498 fix(cli): fix datastore and environment deprecated commands
  cli/cmd/datastore_legacy_cmd.go
  cli/cmd/environment_legacy_cmd.go
Labels: documentation, CLI

#2503 fix: block fe analytics if TRACETEST_DEV is present
  server/app/app.go
  server/http/spa.go
  web/public/index.html
  web/src/services/Analytics/Analytics.service.ts
  web/src/types/Common.types.ts
  web/src/utils/Env.ts
Labels: frontend, backend

#2501 feature(cli): adding support for the all flag when listing resources
  api/config.yaml
  api/dataStores.yaml
  api/openapi.yaml
  cli/actions/config.go
  cli/actions/datastore.go
  cli/actions/polling.go
  cli/cmd/list_cmd.go
  cli/formatters/config.go
  cli/formatters/datastore.go
  cli/formatters/polling.go
  cli/openapi/api_resource_api.go
  cli/openapi/model_configuration_resource_list.go
  cli/openapi/model_data_store_list.go
  cli/openapi/model_polling_profile_list.go
  cli/utils/api.go
  server/config/configresource/config_resource.go
  server/config/configresource/config_resource_test.go
  server/executor/pollingprofile/polling_profile_resource.go
  server/executor/pollingprofile/polling_profile_resource_test.go
  server/openapi/api.go
  server/openapi/api_resource_api.go
  server/openapi/api_resource_api_service.go
  server/openapi/model_configuration_resource_list.go
  server/openapi/model_data_store_list.go
  server/openapi/model_polling_profile_list.go
  server/tracedb/datastoreresource/repository.go
  server/tracedb/datastoreresource/repository_test.go
  web/src/types/Generated.types.ts
Labels: backend, CLI

#2505 feature(cli): version display improvements
  api/openapi.yaml
  api/version.yaml
  cli/actions/action.go
  cli/actions/resource.go
  cli/actions/version.go
  cli/cmd/apply_cmd.go
  cli/cmd/config.go
  cli/cmd/configure_cmd.go
  cli/cmd/dashboard_cmd.go
  cli/cmd/delete_cmd.go
  cli/cmd/export_cmd.go
  cli/cmd/get_cmd.go
  cli/cmd/list_cmd.go
  cli/cmd/middleware.go
  cli/cmd/test_export_cmd.go
  cli/cmd/test_list_cmd.go
  cli/cmd/test_run_cmd.go
  cli/cmd/version_cmd.go
  cli/openapi/api_api.go
  cli/openapi/model_version.go
  server/app/app.go
  server/http/controller.go
  server/http/controller_test.go
  server/openapi/api.go
  server/openapi/api_api.go
  server/openapi/model_version.go
  web/src/types/Generated.types.ts
Labels: backend, CLI

#2524 fix(cli): fix default output for non-resources commands
  cli/cmd/config.go
Labels: bug, CLI

#2515 fix(frontend): fix otlp test connection message
  web/src/providers/DataStore/hooks/useDataStoreNotification.tsx
Labels: frontend

#2504 fix(frontend): highlight selected span
  web/src/components/Visualization/components/DAG/SpanNode.styled.ts
Labels: frontend

#2540 fix(frontend): fix empty body and headers in trigger tab
  web/src/components/CodeBlock/CodeBlock.tsx
  web/src/components/RunDetailTriggerResponse/ResponseBody.tsx
  web/src/components/RunDetailTriggerResponse/ResponseHeaders.tsx
  web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx
Labels: frontend

#2516 feat(server): add traceDB endpoints to event log
  server/executor/poller_executor.go
  server/executor/poller_executor_test.go
  server/model/events/events.go
  server/tracedb/awsxray.go
  server/tracedb/elasticsearchdb.go
  server/tracedb/jaegerdb.go
  server/tracedb/opensearchdb.go
  server/tracedb/otlp.go
  server/tracedb/signalfxdb.go
  server/tracedb/tempodb.go
  server/tracedb/tracedb.go
Labels: backend

#2558 fix(docs): fix docs related to data stores
  docs/docs/cli/creating-data-stores.md
  docs/docs/concepts/versioning.md
  docs/docs/configuration/connecting-to-data-stores/awsxray.md
  docs/docs/configuration/opentelemetry-collector-configuration-file-reference.md
Labels: documentation

#2593 fix(docs): fix cli transactions menu
  docs/docs/cli/creating-transactions.md
  docs/sidebars.js
Labels: documentation

#2594 fix(frontend): removing decross option for the dat layout
  web/src/services/DAG.service.ts
Labels: frontend

#2521 feat: enable/disable ssl cert verification in test trigger
  api/http.yaml
  cli/openapi/model_http_request.go
  server/executor/trigger/http.go
  server/http/mappings/http.go
  server/model/http.go
  server/model/yaml/http.go
  server/openapi/model_http_request.go
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetails.styled.ts
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsForm.tsx
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/SSLVerification.tsx
  web/src/models/HttpRequest.model.ts
  web/src/services/Triggers/Curl.service.ts
  web/src/services/Triggers/Http.service.ts
  web/src/types/Generated.types.ts
  web/src/types/Test.types.ts
Labels: frontend, backend

#2600 feature(cli): adding flag and parameter validations for commands
  cli/cmd/apply_cmd.go
  cli/cmd/config.go
  cli/cmd/configure_cmd.go
  cli/cmd/datastore_legacy_cmd.go
  cli/cmd/delete_cmd.go
  cli/cmd/environment_legacy_cmd.go
  cli/cmd/export_cmd.go
  cli/cmd/get_cmd.go
  cli/cmd/list_cmd.go
  cli/cmd/middleware.go
  cli/cmd/server_install_cmd.go
  cli/cmd/test_list_cmd.go
  cli/cmd/version_cmd.go
  cli/parameters/configure.go
  cli/parameters/installer.go
  cli/parameters/parameters.go
  cli/parameters/resources.go
Labels: CLI

#2605 fix(frontend): fix grpc test spec snippet
  web/src/constants/TestSpecs.constants.ts
Labels: frontend

#2598 feature(cli): adding server and cli version match
  cli/actions/version.go
  cli/cmd/config.go
  testing/cli-e2etest/testscenarios/version_test.go
Labels: CLI

#2613 fix(frontend): fix otel semantic conventions repository url
  web/src/redux/apis/OtelRepo.api.ts
Labels: frontend

#2606 fix(frontend): fix types for test specs
  web/src/models/Test.model.ts
  web/src/models/TestSpecs.model.ts
  web/src/redux/actions/TestSpecs.actions.ts
  web/src/services/Test.service.ts
  web/src/services/TestDefinition.service.ts
  web/src/services/__tests__/TestDefinition.service.test.ts
Labels: frontend
