Repository kubeshop/tracetest, pull requests merged in 2023-07, with the labels that each got.

#2846 feat(frontend): add analyzer errors by attribute
  web/src/components/AnalyzerErrorsPopover/AnalyzerErrorsPopover.styled.ts
  web/src/components/AnalyzerErrorsPopover/AnalyzerErrorsPopover.tsx
  web/src/components/AnalyzerErrorsPopover/Content.tsx
  web/src/components/AnalyzerErrorsPopover/index.ts
  web/src/components/AttributeList/AttributeList.tsx
  web/src/components/SpanDetail/Attributes.tsx
  web/src/components/SpanDetail/SpanDetail.tsx
  web/src/components/SpanDetail/TraceAttributeRow/TraceAttributeRow.styled.ts
  web/src/components/SpanDetail/TraceAttributeRow/TraceAttributeRow.tsx
  web/src/components/SpanDetail/TraceSubHeader/TraceSubHeader.styled.ts
  web/src/components/SpanDetail/TraceSubHeader/TraceSubHeader.tsx
  web/src/services/SpanAttribute.service.ts
Labels: frontend

#2847 feat(frontend): add test outputs mark to Timeline view
  web/src/components/Visualization/components/Timeline/TestSpanNode/Header.tsx
  web/src/components/Visualization/components/Timeline/TestSpanNode/TestSpanNode.tsx
  web/src/components/Visualization/components/Timeline/Timeline.styled.ts
Labels: frontend

#2851 feat(frontend): add select as current span in timeline
  web/src/components/CurrentSpanSelector/CurrentSpanSelector.tsx
  web/src/components/CurrentSpanSelector/index.ts
  web/src/components/Visualization/components/DAG/TestSpanNode/SelectAsCurrent.tsx
  web/src/components/Visualization/components/DAG/TestSpanNode/TestSpanNode.styled.ts
  web/src/components/Visualization/components/DAG/TestSpanNode/TestSpanNode.tsx
  web/src/components/Visualization/components/Timeline/BaseSpanNode/BaseSpanNode.tsx
  web/src/components/Visualization/components/Timeline/TestSpanNode/SelectAsCurrent.tsx
  web/src/components/Visualization/components/Timeline/TestSpanNode/TestSpanNode.tsx
  web/src/components/Visualization/components/Timeline/Timeline.styled.ts
  web/src/components/Visualization/components/Timeline/TraceSpanNode/TraceSpanNode.tsx
  web/src/components/Visualization/components/Timeline/Visualization.tsx
  web/src/components/Visualization/hooks/useSelectAsCurrent.ts
  web/src/components/Visualization/hooks/useShowSelectAsCurrent.ts
Labels: frontend

#2850 feature(frontend): Analyzer Configuration
  api/linters.yaml
  server/executor/linter_runner.go
  server/linter/analyzer/analyzer_entities.go
  server/linter/analyzer/analyzer_metadata.go
  server/linter/analyzer/analyzer_results.go
  server/linter/analyzer/analyzer_results_test.go
  server/linter/rules/not_empty_attribute_rule.go
  server/openapi/model_linter_resource_plugin.go
  server/openapi/model_linter_resource_rule.go
  web/src/components/AnalyzerResult/AnalyzerResult.styled.ts
  web/src/components/AnalyzerResult/GlobalResult.tsx
  web/src/components/AnalyzerResult/Plugins.tsx
  web/src/components/AnalyzerResult/Rule.tsx
  web/src/components/AnalyzerResult/RuleIcon.tsx
  web/src/components/Collapse/Collapse.styled.tsx
  web/src/components/Collapse/Collapse.tsx
  web/src/components/Collapse/CollapseIcon.tsx
  web/src/components/Collapse/index.ts
  web/src/components/Settings/Linter/Linter.tsx
  web/src/components/Settings/Linter/LinterForm.tsx
  web/src/components/Settings/Linter/Plugin.tsx
  web/src/components/Settings/Linter/PluginHeader.tsx
  web/src/components/Settings/Linter/Rule.tsx
  web/src/components/Settings/common/Settings.styled.ts
  web/src/models/Linter.model.ts
  web/src/models/LinterResult.model.ts
  web/src/types/Generated.types.ts
Labels: frontend

#2860 fix(frontend): fix analyzer score styles
  web/src/components/AnalyzerScore/AnalyzerScore.styled.ts
  web/src/components/AnalyzerScore/AnalyzerScore.tsx
  web/src/components/AnalyzerScore/Percentage.tsx
  web/src/components/ResourceCard/ResourceCardSummary.tsx
  web/src/components/RunCard/TestRunCard.tsx
Labels: frontend

#2873 feature(cli): Analyzer Configuration
  cli/cmd/config.go
  cli/openapi/model_linter_resource_plugin.go
  cli/openapi/model_linter_resource_rule.go
  cli/openapi/model_linter_result_plugin_rule.go
  cli/openapi/model_linter_result_plugin_rule_result_error.go
  server/linter/analyzer/analyzer_repository_test.go
  server/linter/linter_test.go
  server/linter/plugins/plugins_entities_test.go
  testing/cli-e2etest/testscenarios/analyzer/apply_analyzer_test.go
  testing/cli-e2etest/testscenarios/analyzer/get_analyzer_test.go
  testing/cli-e2etest/testscenarios/analyzer/list_analyzer_test.go
  testing/cli-e2etest/testscenarios/analyzer/resources/new-analyzer.yaml
  testing/cli-e2etest/testscenarios/types/analyzer.go
Labels: CLI

#2874 fix(docs): fix deprecated test command
  docs/docs/cli/configuring-your-cli.md
Labels: documentation

#2881 fix(frontend): fix otel semantic conventions path
  web/src/redux/apis/OtelRepo.api.ts
Labels: frontend

#2890 docs: add analyzer plugins and rules documentation
  docs/docs/analyzer/concepts.md
  docs/docs/analyzer/plugins/common-problems.md
  docs/docs/analyzer/plugins/otel-semantic-conventions.md
  docs/docs/analyzer/plugins/security.md
  docs/docs/analyzer/rules/attribute-naming.md
  docs/docs/analyzer/rules/no-api-key-leak.md
  docs/docs/analyzer/rules/no-empty-attributes.md
  docs/docs/analyzer/rules/prefer-dns.md
  docs/docs/analyzer/rules/required-attributes.md
  docs/docs/analyzer/rules/secure-https-protocol.md
  docs/docs/analyzer/rules/span-naming.md
  docs/docs/configuration/tracetest-analyzer.md
  docs/docusaurus.config.js
  docs/sidebars.js
Labels: documentation

#2903 feat: add analyzer documentation links
  api/linters.yaml
  cli/openapi/model_linter_result_plugin_rule.go
  server/http/mappings/linter.go
  server/linter/analyzer/analyzer_metadata.go
  server/linter/analyzer/analyzer_repository_test.go
  server/linter/plugins/plugins_entities_test.go
  server/linter/rules/ensure_span_naming_rule.go
  server/openapi/model_linter_result_plugin_rule.go
  testing/cli-e2etest/testscenarios/analyzer/apply_analyzer_test.go
  testing/cli-e2etest/testscenarios/analyzer/get_analyzer_test.go
  testing/cli-e2etest/testscenarios/analyzer/resources/new-analyzer.yaml
  web/src/components/AnalyzerErrorsPopover/Content.tsx
  web/src/components/AnalyzerResult/AnalyzerResult.styled.ts
  web/src/components/AnalyzerResult/Rule.tsx
  web/src/components/AnalyzerResult/RuleLink.tsx
  web/src/components/Visualization/components/DAG/TraceSpanNode/AnalyzerErrorsPopover.tsx
  web/src/constants/Common.constants.ts
  web/src/models/LinterResult.model.ts
  web/src/redux/apis/__tests__/useCreateTestMutation.tesx.tsx
  web/src/services/TestRun.service.ts
  web/src/types/Generated.types.ts
  web/src/types/Test.types.ts
  web/src/types/TestRun.types.ts
Labels: frontend, backend

#2888 feature(backend): Required Gates
  api/testRunner.yaml
  api/tests.yaml
  go.work.sum
  server/app/app.go
  server/app/facade.go
  server/executor/runner.go
  server/executor/runner_test.go
  server/executor/testrunner/main_test.go
  server/executor/testrunner/testrunner_entities.go
  server/executor/testrunner/testrunner_entities_test.go
  server/executor/testrunner/testrunner_repository.go
  server/executor/testrunner/testrunner_repository_test.go
  server/executor/transaction_runner.go
  server/executor/transaction_runner_test.go
  server/http/controller.go
  server/http/mappings/test_runner.go
  server/http/mappings/tests.go
  server/migrations/27_add_test_runner.down.sql
  server/migrations/27_add_test_runner.up.sql
  server/openapi/model_required_gates_result.go
  server/openapi/model_run_information.go
  server/openapi/model_supported_gates.go
  server/openapi/model_test_run.go
  server/test/run.go
  server/test/run_repository.go
  server/test/run_test.go
  server/test/test_entities.go
  server/transaction/transaction_run_entities.go
Labels: backend

#2923 fix(frontend): fix toggle on settings page
  web/src/components/Settings/Analytics/AnalyticsForm.tsx
  web/src/components/Settings/Demo/DemoForm.tsx
  web/src/components/Settings/common/Settings.styled.ts
Labels: frontend

#2924 fix(backend): fix analyzer rule error description
  server/linter/analyzer/analyzer_metadata.go
  server/linter/analyzer/analyzer_repository_test.go
Labels: backend

#2925 fix(frontend): fix analyzer config form for weight field
  web/src/components/Settings/Linter/Rule.tsx
Labels: frontend

#2928 fix(frontend): fix automate page to match new run cli command
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/CliCommand.styled.ts
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/Controls.tsx
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/SwitchControl.tsx
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/hooks/useCliCommand.ts
  web/src/services/CliCommand.service.ts
Labels: frontend

#2933 fix(frontend): fix container in OTel settings page
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/Configuration.tsx
  web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.tsx
Labels: frontend

#2934 feature(frontend): Adding Docker Host Url Prompt
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsUrlInput.tsx
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/UrlDockerTipInput.styled.ts
  web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/UrlDockerTipInput.tsx
  web/src/utils/Common.ts
Labels: frontend

#2931 feat(docs): update docs and examples with new run command
  docs/docs/ci-cd-automation/github-actions-pipeline.md
  docs/docs/ci-cd-automation/overview.md
  docs/docs/ci-cd-automation/tekton-pipeline.md
  docs/docs/ci-cd-automation/testkube-pipeline.md
  docs/docs/cli/configuring-your-cli.md
  docs/docs/cli/running-tests.md
  docs/docs/cli/running-transactions.md
  docs/docs/cli/undefined-variables.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-aws-terraform.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-datadog.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-honeycomb.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-lightstep.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-new-relic.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-step-functions-terraform.md
  docs/docs/examples-tutorials/recipes/running-tracetest-with-tekton.md
  docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store-with-manual-instrumentation.md
  docs/docs/getting-started/open.md
  docs/docs/live-examples/opentelemetry-store/use-cases/add-item-into-shopping-cart.md
  docs/docs/live-examples/opentelemetry-store/use-cases/check-shopping-cart-contents.md
  docs/docs/live-examples/opentelemetry-store/use-cases/checkout.md
  docs/docs/live-examples/opentelemetry-store/use-cases/get-recommended-products.md
  docs/docs/live-examples/opentelemetry-store/use-cases/user-purchasing-products.md
  docs/docs/live-examples/pokeshop/use-cases/add-pokemon.md
  docs/docs/live-examples/pokeshop/use-cases/get-pokemon-by-id.md
  docs/docs/live-examples/pokeshop/use-cases/import-pokemon.md
  docs/docs/live-examples/pokeshop/use-cases/list-pokemon.md
  docs/docs/tools-and-integrations/k6.md
  docs/docs/tools-and-integrations/keptn.md
  examples/observability-to-the-rescue/README.md
  examples/quick-start-github-actions/.github/workflows/start-and-test-on-main.yaml
  examples/quick-start-github-actions/.github/workflows/start-and-test-on-schedule.yaml
  examples/quick-start-net-core/README.md
  examples/tracetest-amazon-x-ray-adot/README.md
  examples/tracetest-amazon-x-ray-pokeshop/README.md
  examples/tracetest-amazon-x-ray/README.md
  examples/tracetest-aws-step-functions/README.md
  examples/tracetest-aws-step-functions/infra/README.md
  examples/tracetest-aws-terraform-serverless/README.md
  examples/tracetest-azure-app-insights-collector/README.md
  examples/tracetest-azure-app-insights-pokeshop/README.md
  examples/tracetest-azure-app-insights/README.md
  examples/tracetest-grafana-tempo-pokeshop/README.md
  examples/tracetest-jaeger/README.md
  examples/tracetest-k6/README.md
  examples/tracetest-lightstep-otel-demo/README.md
  examples/tracetest-new-relic-otel-demo/README.md
  examples/tracetest-opensearch/README.md
  examples/tracetest-provisioning-env/README.md
  examples/tracetest-signalfx/README.md
  examples/tracetest-synthetic-monitoring/.github/workflows/synthetic-monitoring.yaml
  examples/tracetest-tempo/README.md
  testing/cli-e2etest/README.md
Labels: documentation

#2942 feat(frontend): improve attribute selection in test outputs form
  web/src/components/TestOutputForm/TestOutputForm.tsx
Labels: frontend

#2954 docs(testkube): update links to testkube docs and YT vid
  docs/docs/ci-cd-automation/testkube-pipeline.md
  docs/docs/tools-and-integrations/testkube.md
  go.work.sum
Labels: documentation

#2943 fix(frontend): fix trace panel size
  web/src/components/RunDetailTrace/AnalyzerPanel.tsx
Labels: frontend

#2948 feat(frontend): add required gates to cli automate page
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/CliCommand.styled.ts
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/Controls.tsx
  web/src/components/RunDetailAutomateMethods/methods/CLICommand/SwitchControl.tsx
  web/src/components/Settings/TestRunner/RequiredGatesInput.tsx
  web/src/models/TestRunner.model.ts
  web/src/pages/TransactionRunAutomate/TransactionRunAutomate.styled.ts
  web/src/pages/TransactionRunOverview/TransactionRunOverview.styled.ts
  web/src/services/CliCommand.service.ts
Labels: frontend

#2957 fix(server): fix test search query
  server/test/test_repository.go
Labels: backend

#2980 feature(backend) Tenant ID support
  server/app/app.go
  server/config/demo/demo_repository.go
  server/datastore/datastore_repository.go
  server/environment/environment_repository.go
  server/executor/pollingprofile/polling_profile_repository.go
  server/executor/testrunner/testrunner_repository.go
  server/http/middleware/tenant.go
  server/http/middleware/tenant_test.go
  server/linter/analyzer/analyzer_repository.go
  server/migrations/28_add_tenant_id.down.sql
  server/migrations/28_add_tenant_id.up.sql
  server/pkg/sqlutil/tenant.go
  server/test/run_repository.go
  server/test/test_repository.go
  server/transaction/transaction_repository.go
  server/transaction/transaction_run_repository.go
Labels: backend

#2974 feat(frontend): prepare oss for submodule
  package-lock.json
  package.json
  web/.gitignore
  web/craco.config.js
  web/package-lock.json
  web/package.json
  web/src/App.css
  web/src/App.tsx
  web/src/BaseApp.tsx
  web/src/antd-theme/antd-customized.less
  web/src/antd-theme/tracetest-antd-theme.less
  web/src/assets/otel-demo.proto.json
  web/src/assets/pokeshop.postman_collection.json
  web/src/assets/pokeshop.proto.json
  web/src/components/Router/Router.tsx
  web/src/components/TestSpecForm/hooks/useGetOTELSemanticConventionAttributesInfo.tsx
  web/src/components/TestSpecForm/hooks/useOnFieldsChange.ts
  web/src/constants/Demo.constants.ts
  web/src/constants/TracetestAttributes.constants.ts
  web/src/constants/TracetestSemanticConventions.json
  web/src/constants/demos/otel-demo.proto.ts
  web/src/constants/demos/pokeshop.postman.ts
  web/src/constants/demos/pokeshop.proto.ts
  web/src/index.tsx
  web/src/parse-curl.d.ts
  web/src/redux/ReduxWrapperProvider.tsx
  web/src/redux/store.tsx
  web/src/services/Editor.service.ts
  web/src/services/Triggers/Curl.service.ts
  web/tsconfig.json
Labels: frontend

#3009 fix(frontend): fix build warnings related to typescript version
  web/.storybook/main.js
  web/.storybook/preview.js
  web/craco.config.js
  web/package-lock.json
  web/package.json
  web/src/components/CreateSteps/__stories__/CreateTestSteps.stories.tsx
  web/src/components/FileViewerModal/__stories__/FileViewerModal.stories.tsx
  web/src/components/PluginCard/__stories__/PluginCard.stories.tsx
Labels: frontend

#3013 fix(frontend): use Link component in transaction page
  web/src/components/TransactionHeader/TransactionHeader.styled.ts
  web/src/components/TransactionRunResult/ExecutionStep.tsx
Labels: frontend
